### ISSUE TITLE
PDA tgui error on power monitoring mode

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#14951] opened 2020-11-20 22:19 UTC
(Not my error, passing on)
TypeError: Unable to get property 'supply' of undefined or null reference  at h (http://127.0.0.1:56877/tmp25608/tgui.bundle.js:1:126406) at Anonymous function (http://127.0.0.1:56877/tmp25608/tgui.bundle.js:1:202840)  at Anonymous function (http://127.0.0.1:56877/tmp25608/tgui.bundle.js:1:202810)  at Se (http://127.0.0.1:56877/tmp25608/tgui.bundle.js:1:202788)  at Ee (http://127.0.0.1:56877/tmp25608/tgui.bundle.js:1:203924)  at Te (http://127.0.0.1:56877/tmp25608/tgui.bundle.js:1:203763)  at Se (http://127.0.0.1:56877/tmp25608/tgui.bundle.js:1:202652)  at Anonymous function (http://127.0.0.1:56877/tmp25608/tgui.bundle.js:1:202810)  at Se (http://127.0.0.1:56877/tmp25608/tgui.bundle.js:1:202788)  at Anonymous function (http://127.0.0.1:56877/tmp25608/tgui.bundle.js:1:202810)  User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; McAfee; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)

**Comment by AffectedArc07** [comment] 2020-11-20 22:22
Duplicate of about 5 other existing issues

**Closed by AffectedArc07** 2020-11-20 22:22 UTC
