### ISSUE TITLE
Mech cable layer does not cable lay

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#3716] opened 2016-02-26 23:51 UTC
**Problem Description**:
The Cable Layer for the mech does not lay cable.

**What did you expect to happen**: 
For it to lay cable.

**What happened instead**:
It did not lay cable.

**Why is this bad/What are the consequences:**
You can't use the item for it's purpose

**Steps to reproduce the problem**:
Have mech with cablelayer and 30 meters of cables. activate the cable layer, walk, deactivate the cable layer to cut the cables it is supposed to lay

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
I was trying to lay cable at the time.

**Comment by Tastyfish** [comment] 2016-02-26 23:56
A duplicate of your own issue report #3630

**Comment by Robertha89** [comment] 2016-02-27 00:10
Fixed

**Comment by Gummin** [comment] 2016-02-27 00:55
>makes duplicate of own issue
I've noticed multiple complaints about the cable layer not working. I'm not too sure why it isn't working though.

**Closed** 2016-03-07 01:19 UTC
Labels: Bug
