### ISSUE TITLE
Duke Purple Tea and Dutch Hot Cocoa sprites borken

### ISSUE THREAD

**Issue by HereticChurch** [ParadiseSS13/Paradise#5188] opened 2016-07-25 00:49 UTC
**Problem Description**:
The sprites for the two items in the title are missing.

**What did you expect to happen**: 
I expected to see my cocoa and tea.

**What happened instead**:
They have no sprite.

**Why is this bad/What are the consequences:**
It makes it hard to enjoy these specific hot beverages.

**Steps to reproduce the problem**:
Buy said products, notice they're missing. Be sad, buy hot chocolate instead, get fat.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Nothing I can think of, specifically.

**Comment by TheDZD** [comment] 2016-07-25 00:54
Duplicate of #5148, already fixed by #5161,

**Closed by TheDZD** 2016-07-25 00:54 UTC
Labels: Duplicate
