### ISSUE TITLE
Atmos magboots don't keep the person on the tile when unwrenching pressurised pipes

### ISSUE THREAD

**Issue by Miraviel** [ParadiseSS13/Paradise#19063] opened 2022-09-15 12:57 UTC
**Issue Description**:

When unwrenching a pressurised pipe, the player is thrown back and is dealt a significant amount of damage. Turning on magboots should stop this from happening, but it does not.

**What did you expect to happen**: 

Turn on atmos magboots, get warning of pipe being pressurised, do not fly away.

**What happened instead**:

Turned on atmos magboots, got warning of pipe being pressurised, got sent to Brazil.

![image](https://user-images.githubusercontent.com/33333517/190409127-3e318f2d-2709-4fe4-97c3-a451722bdb40.png)

**Why is this bad/What are the consequences**:

It is inconsistent, atmos magboots should keep the user in place (up to a certain point?)

**Steps to reproduce the problem**:

1. Fill pipe with gas
2. Turn on atmos magboots
3. Unwrench pipe

**When did the problem start happening**:

Unsure

**Extra information**:

None

**Comment by Contrabang** [comment] 2022-09-15 13:16
Likely caused by enabling atmos/CE magboots mid-unwrenching, should be as simple as moving this code block inside the do_after
![image](https://user-images.githubusercontent.com/91113370/190413235-bb5e1255-7d71-4152-9035-e6bd371ef2c4.png)

**Closed** 2022-09-17 09:53 UTC
