### ISSUE TITLE
Transparent terror webs stun when behind doors without opening them

### ISSUE THREAD

**Issue by Freakycrafter** [ParadiseSS13/Paradise#15704] opened 2021-03-12 17:14 UTC
**Issue Description**: When terrors create webs under doors (same tile as the door) they'll stun you, without even opening the door.

**What did you expect to happen**: To not be stunned by a web I can't even possibly see.

**What happened instead**: I got stunned by a transparent web that was below a door, even though I didn't even try to open the door.

**Why is this bad/What are the consequences**: I died because of this, as the terrors behind the door (not same tile) immideately dragged me further in and killed me.

**Steps to reproduce the problem**: Place a transparent web (or whatever type is the web that stuns you when you walk on a tile next to it) under a door and walk next to the door.

**When did the problem start happening**: The round this happened to me (on 12.03) was the first time I remember this happening, probably been like it since that type of web has been introduced.

**Extra information**:

**Comment by SabreML** [comment] 2021-03-12 17:24
*Not* a duplicate of #15691, although they're very similar issues.

**Comment by Kepplerx** [comment] 2021-03-13 20:30
Not limited to grey webs, seems its all webs

**Closed** 2021-03-15 20:42 UTC
