### ISSUE TITLE
Reactants occasionly fail to react when working with virology ingredients

### ISSUE THREAD

**Issue by BondedGunner** [ParadiseSS13/Paradise#8085] opened 2017-09-11 21:20 UTC
**Problem Description**:
In virology when mixing the virus food with the other ingredients( unstable mutagen with virus food .etc) occasionally the ingredients will not mix,
**What did you expect to happen**: 
I expected the ingredients to mix in 1:1 batch mixes

Why do you think this is a bug?
because it only happens occasionally. 
**What happened instead**:
the ingredients would not react. if added more of virus food or other component to the beaker it would bubble but there would always be at least 1 unit of unreacted virus food, or mutagen remaining.

**Why is this bad/What are the consequences:**
it ends up in the plasma dust and unstable mutagen getting wasted because it ruins the batch I'm mixing

**Steps to reproduce the problem**:
if you use a pipette to transfer 1 unit of virus food into a beaker and then transfer 1 unit of the 2nd ingredient into the same beaker, normally it will say the "solution begins to bubble", however if you continue to do this eventually the ingredients will just sit in the beaker instead of reacting

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: This was occurring during the Australian server issue that was present during sept 11 and earlier. so it is possible this bug is just the result of lag.
I was able to separate the ingredients using the chemistry pill maker machine but it is time consuming and tedious.

**Comment by taukausanake** [comment] 2017-09-12 00:09
Sounds like a duplicate of #7723

**Comment by Crazylemon64** [comment] 2018-08-28 06:34
Duplicate of #7723

**Closed by Crazylemon64** 2018-08-28 06:34 UTC
