### ISSUE TITLE
IPC Sprite bug

### ISSUE THREAD

**Issue by Jared12100** [ParadiseSS13/Paradise#7176] opened 2017-04-25 12:41 UTC
**Problem Description**:
When an IPC gets damaged and the sprite updates to show it being damaged it makes several red dots, which is normal. But once repaired the dots don't go away. This has happened to me consistently with the shellguard body and elite series head. If its true for all IPC models or not i can't say.

**What did you expect to happen**: 
It should restore to the default sprite. It didn't

**What happened instead**:
I still look damaged when I'm not.

**Why is this bad/What are the consequences:**
It can lead to misinterpretation at a glance of damage. Also RP.

**Steps to reproduce the problem**:
Get hurt as an IPC until the sprite updates. Repair the damage.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: None.

**Comment by Anoonki** [comment] 2017-04-25 17:14
That's actually "Blood" as far as I can tell.
Duplicate this, take a shower, then update your sprite.

Not to say IPCs should be generating blood, mind.

**Comment by Spacemanspark** [comment] 2017-04-25 21:38
Actually I'm fairly sure that's meant to be a damaged chassis, I know what he's talking about.

**Comment by Anoonki** [comment] 2017-04-25 22:50
Once damage is repaired it doesn't actually visually go away until you go and have a shower then cause a sprite update ((Change clothes or whatever)), afaik

**Comment by Henri215** [comment] 2023-08-12 23:31
Duplicate of https://github.com/ParadiseSS13/Paradise/issues/16682.

Closing since it has been fixed by https://github.com/ParadiseSS13/Paradise/pull/16976.

**Closed by Henri215** 2023-08-12 23:31 UTC
Labels: Bug
