### ISSUE TITLE
Atmospheric Tank Control computer unable to see updated pipenet

### ISSUE THREAD

**Issue by drsid** [ParadiseSS13/Paradise#9574] opened 2018-09-18 01:01 UTC
**Problem Description**:
A computer with Atmospheric Tank Control circuit unable to see deviced in same net (except a gas sensor) in Turbine room.

**What did you expect to happen**: 
Replace unary vent with second air injector and turn it on via computer (since computers are only way to turn on air injectors)

**What happened instead**:
Computer status: "ERROR: can not find input port"

**Why is this bad/What are the consequences:**
Cant make better turbine setup making it more usefull

**Steps to reproduce the problem**:
1) Replace unary vent with air injector. 2) Place a gas sensor 3) Create a computer with Atmospheric Tank Control circuit (or any other appropriate circuit) 4) Use multitool to connect devices

**Possibly related stuff

Quite a lot of bugs around atmos... I can name few more allready, but they are fixable during game. This one not. Multiple menthor and ahelps didnt helped... discord too...

**Comment by Sirryan2002** [comment] 2022-07-06 03:52
duplicate of #9495

**Closed by Sirryan2002** 2022-07-06 03:52 UTC
Labels: Bug
