### ISSUE TITLE
Karma Unlock cannot be cancelled.

### ISSUE THREAD

**Issue by iantine** [ParadiseSS13/Paradise#10650] opened 2019-01-14 11:16 UTC
**Problem Description**:
When unlocking a karma unlock, at the popup "Are you sure you want to unlock (x)?", after clicking "No" or "Yes", the window immediately pops back up. The only way this can be fixed is by closing and reopening the game.

**What did you expect to happen**: 
After clicking either button, I expected the window to close and stay closed.

**What happened instead**:
After initially clicking no, the dialogue window kept reopening until I closed the client. After reopening the client, I reattempted the dialogue window, and clicked yes. The same happened, the dialogue window immediately reopening itself. I didn't attempt a second yes, but clicked no. It reopened again, and continued on until I closed the client.

**Why is this bad/What are the consequences:**
It forces a client restart. Alt+f4ing the dialogue window won't work.

**Steps to reproduce the problem**:
1. Open the Karma subsection.
2. Select a Karma unlock.
3. Select Yes or No.
4. Watch as the window pops back up, asking Yes/No again.

**When did the problem start happening**:
Just now witnessed.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Witnessed on lobby screen. The only two karma unlocks I tested were Kidan and Drask (species unlocks).

**Comment by Quantum-M** [comment] 2019-01-15 03:15
The same occurred to me almost 24 hours ago, with unlocking Box for me.

**Comment by PidgeyThePirate** [comment] 2019-09-28 02:48
I can't replicate this on the main server. Whatever the problem was, it's gone now.

**Comment by Sirryan2002** [comment] 2022-07-07 15:29
This is either a duplicate of #17484 or no longer an issue because karma was ported to a TGUI menu, closing

**Closed by Sirryan2002** 2022-07-07 15:30 UTC
Labels: Bug
