### ISSUE TITLE
Shipping boxes can duplicate pAIs

### ISSUE THREAD

**Issue by Joonasm** [ParadiseSS13/Paradise#7053] opened 2017-04-05 00:11 UTC
**Problem Description**:
If a pAI is put into a shipping box and then folds out of it. if someone tears the shipping box open they will then find the pAIs carded form, if the pAI folds back into a card they become that card

**What did you expect to happen**: 
for the shipping box to be empty

**What happened instead**:
I folded out and the one who unfolded me got my carded form

**Why is this bad/What are the consequences:**
It could be abused to teleport pAIs and is very confusing

**Steps to reproduce the problem**:
Print a shipping box, put an active pAI inside, have them fold out and then tear the box open

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: the box was sealed and sent to another location though disposals

**Comment by FalseIncarnate** [comment] 2017-04-05 00:13
Your title says that it duplicates pAIs, but your explanation says that it causes the pAI to teleport.

Which is it in the end, two cards or pAI bluespacing?

**Comment by Joonasm** [comment] 2017-04-05 00:15
It is two pAIs which are the same, a Mobile form pAI and a Card form of that pAI. the player controls the mobile form one, if he folds down then he replaces the card form one where ever it might be. sorry, thought that kind of title would be fitting

**Comment by FalseIncarnate** [comment] 2017-04-05 00:26
So pAI bluespacing/teleportation.

Quantum entanglement at it's finest. Seems like the same sort of issue reported in #7040

**Comment by Crazylemon64** [comment] 2018-08-28 07:04
Yeah, same category. Duplicate of #7040

**Closed by Crazylemon64** 2018-08-28 07:04 UTC
Labels: Duplicate
