### ISSUE TITLE
Recall Spell Wierd Interactions

### ISSUE THREAD

**Issue by Banderblitz** [ParadiseSS13/Paradise#21704] opened 2023-07-16 04:17 UTC
**Issue Description**:
Recall (wizard spell & mining loot) recalls a modsuits storage as a seperate bag, not as the modsuit itself if you recall an item inside of it, as well as storage implants being removed and delted when items inside them are recalled.

**What did you expect to happen**: 
I expected to either recall the whole modsuit, as intended with containers, or have the item recalled into my hand.

**What happened instead**:
I used recall and created a plain backpack in my hand labeled "mod's storage" which was for all intents and purposes my modsuit storage that I could place wherever I felt, if I opened my bag the modsuit storage would disappear. As well as recalling and my storage implant being forcefully removed and the items placed below me on the ground.

**Why is this bad/What are the consequences**:
Having an item break consistency with how it works is bad, also, objects coming into existence that shouldnt exist is bad.

**Steps to reproduce the problem**:
Step 1: Get a modsuit/storage implant and recall.
Step 2: Mark an item with recall.
Step 3: Place the marked item into bag or storage.
Step 4: Use recall, modsuit storage should appear in your hand as a normal backpack. In case of storage implant, the implant is ripped out of you and the items dropped on the ground.>

**When did the problem start happening**:
Worked as of 7/15/2023, likely has existed since the modsuit addition and forever for storage implants.

**Comment by Contrabang** [comment] 2023-07-16 10:26
Thank you for this report! Unfortunately this is a duplicate of #21687, but I'll still bug QWERTY to fix it

**Closed by Contrabang** 2023-07-16 10:26 UTC
Labels: Bug, Testmerge Active
