### ISSUE TITLE
Cryogenic Oversight Strange Behavior

### ISSUE THREAD

**Issue by Rosebrandon0** [ParadiseSS13/Paradise#21352] opened 2023-06-15 21:23 UTC
**Issue Description**:

The text generated in viewing the Cryogenic Oversight's stored crew created duplicate entries infinitely.

**What did you expect to happen**: 

The Cryogenic Oversight monitor should only show one entry per stored crew member.

**What happened instead**:

![bug](https://github.com/ParadiseSS13/Paradise/assets/58378041/670074bb-2b9d-4693-9123-80f7b0c76c2e)
The same name was populating continuously in the dropdown to view stored crew members.

**Why is this bad/What are the consequences**:

This is a minor issue with little impact on gameplay.

**Steps to reproduce the problem**:

I do not know.

**When did the problem start happening**:

just now.

**Extra information**:

Thanks for all the hard work.

**Comment by Contrabang** [comment] 2023-06-15 21:28
Duplicate of #21109, but this issue has more information, I will be closing the other. This issue started happening when the Cryogenic Oversight console was made into TGUI. I've looked into it myself, and I'm not sure why this happens

**Comment by Sirryan2002** [comment] 2023-06-16 04:13
GAHH FUCKING JAVASCRIPT

**Closed** 2023-07-13 02:45 UTC
Labels: Bug, TGUI, The Spawn Of Satan
