### ISSUE TITLE
Fluorosurfacant division error, possibly gamebreaking if abused

### ISSUE THREAD

**Issue by lieric96** [ParadiseSS13/Paradise#7209] opened 2017-05-02 07:48 UTC
The reagent division calculation is done in the wrong order for fluorosurfacant, making it so that putting less reagent into fluorosurfacant yields more powerful results. For example, 1u of reagent will apply 5u of reagent in atmos, while 5u will apply only 1u. Putting 0.1u results in 50 and as you approach 0 you might be able to get near infinite amounts of chemicals applied.

Please fix the following file at line 933:
https://github.com/ParadiseSS13/Paradise/blob/463af0af7386c86d2b77b683b8458bc6b03515e2/code/game/objects/effects/effect_system.dm

Reverse the division in that line and it should fix everything up.

**Comment by SamHPurp** [comment] 2017-05-02 08:00
Thought this was still an issue, this was raised by @Anticept here #7118, but @Fox-McCloud closed it.

**Comment by Fox-McCloud** [comment] 2017-05-02 11:36
This is only half the equation; putting in 5 units does not result in 1 unit, likewise, putting in 0.0001 units doesn't result in 50,000 units.

This just passes the fraction amount to `reaction`, where it takes that number and multiplies it by the individual reagent's volume.

In the case of the 0.0001 unit example, this is what will happen:

fraction = 5 / 0.0001 (this is 50,000)
reaction will pass with an argument of 50,000
reaction takes the individual reagent's volume and multiplies it by the above argument.

The end result, no matter what amount of reagents you use is that it's going to clamp the value to 5, meaning it's going to apply, via touch, 5 units of the contain reagents. This is working as intended; it does, indeed, multiply reagents, but it doesn't multiply it to the insane degree implied here.

This ensure that a lot of various chems actually *work* in foam while also limiting their upper impact. 

Please note that when I say it "multiplies reagents" I don't mean any reagent is actually getting duplicated; it's just clamping its *impact* to 5.

**Closed** 2017-05-03 02:28 UTC
