### ISSUE TITLE
Relocated Rechargers don't work

### ISSUE THREAD

**Issue by StreakyHaddock** [ParadiseSS13/Paradise#275] opened 2015-02-09 20:49 UTC
If you wrench a recharger and move it to another location and wrench it back into place again, it doesn't work. Today there was a Blob round and we had two rechargers in the Bridge. One, the recharger that starts in the bridge, and another which had been relocated from arrivals. The arrivals recharger would not work despite being wrenched down and in a powered room (but would accept guns and show the 'charging' sprite).

This is despite them both being in the same, fully powered room.

**Comment by Markolie** [comment] 2015-02-10 00:45
Can't reproduce.

**Comment by StreakyHaddock** [comment] 2015-02-11 17:08
I can't explain what caused it either, but one recharger worked and the other didn't.

**Comment by mwerezak** [comment] 2015-02-12 06:47
Was the recharger originally obtained from a room that was unpowered?

**Comment by Markolie** [comment] 2015-02-14 03:58
@StreakyHaddock See above. Otherwise, I'll just close this until we can pin down a cause.

**Closed** 2015-02-16 14:10 UTC
Labels: bug, cannot reproduce
