### ISSUE TITLE
Jump boots allow you to literally move faster through space then anything else.

### ISSUE THREAD

**Issue by Drobe50** [ParadiseSS13/Paradise#12122] opened 2019-08-28 23:31 UTC
**Issue Description**:
Using Jump boots in space allows you to move faster than anything else in the code.

**What did you expect to happen**: 
To not go faster through space than anything else.

**What happened instead**:
Allows players to move faster than even ghosts.

**Why is this bad/What are the consequences**:
Could probably cause server lag considering the player is traversing multiple z levels within seconds.

**Steps to reproduce the problem**:
Be space proof, wear jump boots, use them in a direction not facing the station. 

**When did the problem start happening**:
Ever since jump boots were added to the code.

**Extra information**:

**Comment by matttheficus** [comment] 2022-06-22 16:56
Duplicate of #13065

**Closed by matttheficus** 2022-06-22 16:56 UTC
Labels: Duplicate, (99% Sure) Not A Bug
