### ISSUE TITLE
Shock Crate does not shock

### ISSUE THREAD

**Issue by ppi13** [ParadiseSS13/Paradise#9142] opened 2018-06-26 18:49 UTC
**Problem Description**:
The shock crate does not shock when opened.

**What did you expect to happen**: 
I expected people without insulated gloves to be shocked

**What happened instead**:
It just straight up opened like it was a normal crate and not a shock crate

**Why is this bad/What are the consequences:**
Opening things people drag is bad, this is something that exists to punish just that, without it being a proximity bomb, it's good manners not to open the closets and crates being dragged, and this kinda subconciously added it.

**Steps to reproduce the problem**:
Step 1. Build/find a crate.
Step 2. Close crate if open, hit with a cable coil of 30
Step 3. Turn on the electropack and add it to the still closed crate.
Step 4. Open crate while not wearing anything that provides protections against electric shock.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Nope

**Comment by Plotron** [comment] 2018-06-26 22:08
I didn't even know that such a thing existed!
Shame to see it broken.

**Comment by Citinited** [comment] 2018-06-27 14:19
This happens because rigged crates call `electrocute_act` on `mob/living`. The issue is that `mob/living/electrocute_act` `return`s without doing anything else, whereas relevant electrocution stuff happens on a `mob/living/carbon` level. I will put up a fix for this when I return home today

**Comment by KasparoVy** [comment] 2018-06-27 15:15
It's hilarious dragging shock crates around because you know shitters just love to open stuff.

**Comment by Crazylemon64** [comment] 2018-06-27 22:20
@Citinited That's not how dynamic typing in BYOND works. If you call `electrocute_act` on a `/mob/living/carbon` that is stored in a variable casted of type `/mob/living`, you'll still call the `/mob/living/carbon` version.

**Comment by Citinited** [comment] 2018-06-27 22:34
Tested and shocked myself, so this isn't a bug. You were probably wearing insulated gloves or something

**Comment by Plotron** [comment] 2018-06-27 23:45
Fantastic.

**Comment by alexkar598** [comment] 2018-07-02 10:29
@tigercat2000 issue is non existant

**Closed** 2018-07-02 20:55 UTC
Labels: Cannot Reproduce
