### ISSUE TITLE
follow verb disappears under tcomms scripting

### ISSUE THREAD

**Issue by Ar3nn** [ParadiseSS13/Paradise#4461] opened 2016-05-18 22:36 UTC
**Problem Description**:
What is the problem?
When a translator script is applied to the radio telecomms, the follow verb disappears

**What did you expect to happen**: 
Why do you think this is a bug?
Because why get rid of the follow verb?

**What happened instead**:
How is what happened different from what you expected?
The follow verb should definitely be there, because its there all the time otherwise.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It's not THAT big a deal, you can still use follow_<name> in the chatbar to do the same thing, but since its there, it should be there.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Be ghost. Have translation script added to tcomms. Watch radio chatter. Notice you can't jump to people because the button is not there.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Nothing I haven't already stated. Other than an example of the occurrence?

![example of chat bug](http://img.prntscr.com/img?url=http://i.imgur.com/CfUcGOU.png)

**Comment by Spacemanspark** [comment] 2016-05-19 02:25
RemoveTcommsscripting2k16

**Comment by FlattestGuitar** [comment] 2016-05-21 08:59
This actually only happens with the language translation scripts.

Because `$language` is a read-only var, the best thing you can do to translate something is `broadcast` the massage with its original `$source` and `$content`. This basically means that it's not an actual person speaking, but the server itself, just pretending to be that person. No point in being able to follow the server, is it?

Not a bug, just a result of the inner workings on tcomms.

**Comment by IK3I** [comment] 2016-05-23 20:47
perhaps this could be fixed by making the $source var within tcomms be the follow argument, rather than the true source

**Closed** 2019-04-28 18:00 UTC
Labels: Bug
