### ISSUE TITLE
Cyborg radio not working after EMP

### ISSUE THREAD

**Issue by MisterOkapi** [ParadiseSS13/Paradise#13240] opened 2020-04-02 03:10 UTC
**Issue Description**:
Cyborg radio no longer works at all after EMP'd. 

**What did you expect to happen**: 
That turning radio off and back on again would fix the issue

**What happened instead**:
Radio ceased to work and turning on and off and replacing the component didn't fix it.

**Why is this bad/What are the consequences**:
Cyborg permanently loses ability to use radio for rest of round

**Steps to reproduce the problem**:
1. Be cyborg
2. Get EMP'd by singularity

**When did the problem start happening**:
Noticed it today. April 1, 2020. 

**Extra information**:

**Comment by Kyep** [comment] 2020-08-09 23:55
Tested (spawned borg, manually called emp_act(1) and emp_act(2) on self).
Cannot reproduce. @AffectedArc07 I suggest closing this. At least until a better reproduction is available, if it still happens.

**Comment by AffectedArc07** [comment] 2020-08-10 08:05
Cannot reproduce. You likely got your radio component damaged in the process of being EMP'd repeatedly.

**Closed by AffectedArc07** 2020-08-10 08:05 UTC
