### ISSUE TITLE
New ghost put into ghosted holoparasite's mob is not able to move

### ISSUE THREAD

**Issue by Dovixx** [ParadiseSS13/Paradise#11072] opened 2019-03-18 15:09 UTC
**Problem Description**:
When the ghost that gets put into a ghosted holoparasite they cannot move when manifested.

**What did you expect to happen**: 
For the holoaparsite to be able to move.

**What happened instead**:
Holoparasite was not able to move.

**Why is this bad/What are the consequences:**
Not moving when you should be able is generally a bad thing.

**Steps to reproduce the problem**:
Step 1. Get a holoparasite in you
Step 2. The holoparasite ghosts
Step 3. Get a new ghost in the holoparasite
Step 4. Holoparasite manifests and is unable to move.

**When did the problem start happening**
Probably since holoparasites were added. The cause was only found today.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Agent round.

**Comment by SpessX** [comment] 2019-03-22 14:01
Did you try hitting rest? Some mobs go into rest mode when ghosted out but have no rest sprite, so people are often clueless about needing to stand up.

**Comment by dovydas12345** [comment] 2019-03-22 14:22
Well i was not the holoparasite so i didn't, but that does sound like it could be the case.

**Comment by Henri215** [comment] 2023-04-30 00:31
Duplicate of https://github.com/ParadiseSS13/Paradise/issues/9794.

**Closed by Henri215** 2023-04-30 00:31 UTC
Labels: Duplicate
