### ISSUE TITLE
checkTurfVis errors with carded AIs

### ISSUE THREAD

**Issue by Kyep** [ParadiseSS13/Paradise#9386] opened 2018-08-19 21:18 UTC
**Problem Description**:
As a carded AI, clicking on things can generate "failed checkTurfVis on AI click of" errors to all online admins.

**What did you expect to happen**: 
I expected that carded AIs don't generate warnings due to clicking nearby things.

**What happened instead**:
They generated warnings.

**Why is this bad/What are the consequences:**
It dilutes the value of these warnings and causes admins to generally ignore them.

**Steps to reproduce the problem**:
Be a carded AI.
Be in an area without cameras.
Click on things.

**Comment by Crazylemon64** [comment] 2018-08-28 02:52
Duplicate of #8630

**Closed by Crazylemon64** 2018-08-28 02:52 UTC
Labels: Administration, Duplicate, Oversight
