### ISSUE TITLE
Slime People take absurd slimecore damage from defibrillation, to the point where it's almost always fatal.

### ISSUE THREAD

**Issue by EvadableMoxie** [ParadiseSS13/Paradise#10086] opened 2018-11-01 06:17 UTC
**Problem Description**:
The amount of damage Slime People take to their core from being defibulated is absolutely absurd, to the point where they will almost always require surgery after being defibbed.

**What did you expect to happen**: 
Defibs do brain damage after the subject has been dead for 60 seconds and scale upward based on how long they've been dead, with an RNG element thrown in. It would make sense for there to be some amount of brain damage from being dead.

**What happened instead**:
The damage is so high at any slime dead for over 60 seconds to trigger the damage at all is highly likely to die.  I tested on a slime that was dead for about 90 seconds and they took _135_ brain damage the first test, and _193_ brain damage the second test.  For reference, subjects instantly die at 60 brain damage.  This is just absurd.

**Why is this bad/What are the consequences:**
Defibbing slimes basically requires a surgery room now, as well more advanced medical knowledge.  Most doctors don't know what the problem is or how to fix it, resulting in dead slime people on the Medbay floor instead of living slimes lewdly squishing the halls.

**Steps to reproduce the problem**:
Kill a slime. Wait at least 60 seconds.  Defib a slime.  Check the damage in a body scanner. Keep in mind it's random so you might get a few lucky results with low damage, more so if you defib faster.

**When did the problem start happening**:
I can't really recall.  I was able to repoduce on my copy I downloaded on August 23, so at least that long.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 

I'd recommend a damage cap, maybe something like 20-30 brain damage. That's still very high considering you die at 60, enough to severely impair the subject.

*squish

**Comment by Mitchs98** [comment] 2018-11-01 06:33
This is due to an absurdly high(unlisted) 2.5x brain damage modifier that they have. The only way I can think to fix it is like you said, capping the brain damage that defibs can do. It's kinda shit and definitely makes reviving them/getting revived kinda hard or even impossible if medbay doesn't know how to fix the core/what the death message means.

**Comment by taukausanake** [comment] 2018-11-01 12:37
Duplicate of #9143. I think it's a "will not fix".

Also, tasing slimes just sounds so pleasing when you realize they are 100% water

**Closed** 2018-11-01 16:53 UTC
