### ISSUE TITLE
Spacepods don't lose their items when removed

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#4711] opened 2016-06-18 19:27 UTC
**Problem Description**:
What is the problem?

When you take a spacepod componoent it does not get removed entirely. The component will go into your hand. But the pod will still believe it has it inside. The only way to totally remove it so to destroy the component in the disposal system or sing.

**What did you expect to happen**: 
Why do you think this is a bug?

Components stay when they shouldn't.

**What happened instead**:
How is what happened different from what you expected?

Components should be removed and not listed on the Spacepod's internal component list.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

You cannot replace a spacepod component without destroying it.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Crowbar open a spacepod. Remove component. Set it on the ground away from the pod. Go back to the menu and remove the same component. It will magically warp to your hand.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

Powercells are not affected.

**Comment by TheDZD** [comment] 2016-06-18 20:37
Duplicate of #4582, already fixed, we just haven't patched yet.

**Closed by TheDZD** 2016-06-18 20:37 UTC
