### ISSUE TITLE
Ghosts [obviously] can't turn pages in bundled papers

### ISSUE THREAD

**Issue by Plotron** [ParadiseSS13/Paradise#3090] opened 2016-01-02 22:41 UTC
They need to have the paper in their active hand. Ghosts do not have hands.
Result: ghosts can only read the first page in bundled papers. It'd be swell if we could have a feature that would let ghosts access all the other pages. It should be visible only to them, of course, as we do not want ghosts to interact with the real world.
And yes, let's not forget that humans should still have to turn the pages physically, so no magical page-turning with hands cuffed.

**Comment by tigercat2000** [comment] 2016-01-08 16:23
Baycode.

**Comment by Sirryan2002** [comment] 2022-07-27 19:14
I'm closing this as a feature request as ghosts by design are not supposed to be able to interact with world objects. This also requires a complete refactor for how paper related UIs are handled.

**Closed by Sirryan2002** 2022-07-27 19:14 UTC
Labels: Feature Request, Usability, Requires Refactor
