### ISSUE TITLE
Atmos computer ain't showing up air alarms

### ISSUE THREAD

**Issue by LazySpaceman** [ParadiseSS13/Paradise#5578] opened 2016-08-30 18:02 UTC
**Problem Description**:
Atmos computer is only showing "UO45 Mining" as an air alarm. All other air alarms on station aren't showing. 

**What did you expect to happen**: 
Computer should read air alarms from station and not gateway. 

**What happened instead**:
Well, it doesn't even show up air alarms on the map. 

**Why is this bad/What are the consequences:**
Atmos will have bad time trying to keep an eye on oxygen level and air alarms onboard the station. 

**Steps to reproduce the problem**:
Well, it just is. I turned computer on and it doesn't show anything other than that UO45 Mining. Disassembling and reassembling computer didn't help. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Not a clue. Maybe cicuit board for computer is reading the wrong map?

**Comment by GeneralChaos81** [comment] 2016-08-31 06:10
Do you know if it was affecting both the one in the engineering control room, and the one in atmos control room?

**Comment by IAmBigCoat** [comment] 2016-08-31 08:00
Wasn't this a known issue with versions of Windows before 7 having trouble with nanoui? What's your current operating system?

**Comment by LazySpaceman** [comment] 2016-08-31 14:45
I don't know if it was affecting engineering control room. My os is Windows 7. Also computer started to show things up properly after air alert went off somewhere.

**Comment by yusiangpotato** [comment] 2016-12-13 06:57
Is this a dupe of #2571 ?

**Closed** 2020-03-17 19:21 UTC
Labels: Bug
