### ISSUE TITLE
Theft Objective Location

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#11560] opened 2019-05-20 16:24 UTC
**Problem Description**:
The theft objective for certain items can give the last known location at the Admin or central command Z level.

**What did you expect to happen**: 
For the theft objective location to only reference on station or player accessible areas.

**What happened instead**:
Advanced magboots at admin testing room got referenced for theft.

**Why is this bad/What are the consequences:**
Not good for players to have a hint for the location they cannot go to.

**Steps to reproduce the problem**:
Random chance for the hint to assign the location hint for admin area if the item is there.

**When did the problem start happening**:
Most likely when the theft hints were added in.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Traitor gamemode 
![steal objective](https://user-images.githubusercontent.com/24213815/58036905-ca39bf80-7af1-11e9-87c9-6c07eee86582.PNG)

**Comment by taukausanake** [comment] 2019-05-20 18:21
Duplicate of #11010 I believe

**Closed** 2019-06-28 13:04 UTC
