### ISSUE TITLE
Are vox chameleons in disguise?

### ISSUE THREAD

**Issue by ExitGame** [ParadiseSS13/Paradise#4960] opened 2016-07-10 00:25 UTC
**Problem Description**:
Doing some things like putting on a paramedic vest or getting handcuffed/stunbatoned somehow change your vox tail color.

**What did you expect to happen**: 
Well, I wouldn't think that doing some things change your tail color.

**What happened instead**:
Well,some things did change your tail color.

**Why is this bad/What are the consequences:**
It's ugly AF.

**Steps to reproduce the problem**:
1. Do certain things as vox (ex. put on paramedic vest or get stunbatoned/handcuffed [not sure which]).
2. Random vox tail color, yay.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Um well, there may be a lot more things that do this other than the two I mentioned, so go diggin', coders.

**Comment by TheDZD** [comment] 2016-07-10 00:36
@KasparoVy

**Comment by KasparoVy** [comment] 2016-07-10 11:29
I'm yet to figure out exactly what causes this myself. With a fully updated branch on a local test server I've been unable to trigger a tail colour change no matter what happens-- various combinations of damage to various bodyparts triggered by numerous differing situations, getting stunned, cuffed, thrown, hit, disarmed, tabled, wearing clothes, not wearing clothes, having it put on and taken off by other people-- It seems to happen when there's a large amount of people.

I've been digging at it ever since the PR went live in a legit patch but I'm really quite stumped. I'll keep looking.

**Comment by KasparoVy** [comment] 2016-07-10 22:19
I've seen a fair few other people with this bug going on. If it ever happens to you, please report the exact circumstances of what happened: What damage you took, what you did when it happened, what someone did to you when it happened, where you were, etc.

**Comment by ExitGame** [comment] 2016-07-15 12:07
Appearently it's fixed?
It hasn't happened since 4 days now. What?

**Comment by KasparoVy** [comment] 2016-07-15 15:21
Yeah, see-- that's what I mean. It's super weird! As far as I know there wasn't a PR deliberately targeting this issue. Don't get me wrong, I'm glad it's 'fixed'-- but I can't help but think the underlying issue hasn't gone away.

**Comment by ExitGame** [comment] 2016-07-16 14:59
It may be that the problem is within the character creation panel, wasn't there a PR that wanted to make the vox tail colour the same as the actual skin colour? Shit, either that or there are runtimes happening in the SQL database that save the characters that fuck up due to the PR in high pop due to well, high data traffic.

**Comment by ExitGame** [comment] 2016-07-19 18:23
OH MY FUCK ITS HAPPENING AGAIN WHAT THEFUCK

**Comment by Crazylemon64** [comment] 2016-07-19 20:35
Does it always change to the same color? <a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/human/update_icons.dm#L1145-L1166>It looks like tail sprite code doesn't take skin tone into account.</a>

**Comment by ExitGame** [comment] 2016-07-20 08:40
It's not always the same colour, sometimes it turned into brown, sometimes into emerald.

**Comment by ExitGame** [comment] 2016-07-22 22:25
Quick update, it is still happening, and not only to me but also other people.
It triggers mostly when you put on something like a labcoat or anything that fits in the suit slot.
Editing the VV does nothing, so, shit. I don't know anymore.

**Comment by KasparoVy** [comment] 2016-07-24 16:52
@Crazylemon64 Skin tone doesn't need to be handled in tails at all because of what goes down in https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/human/species/station.dm#L365. The skin tone is only used to decide which icons and tail are reassigned to icobase, deform and tail

**Comment by KasparoVy** [comment] 2016-07-24 17:22
I think I might've figured out why this happens. I neglected to port the 'species mob reference' portion from the VG icon based skin tones PR which attaches a mob to its species with the intention of allowing a check to see if, during a species' handle_post_spawn, its mob reference is equal to the argument given to that proc (which is a mob, and should be the same mob as the species' mob reference) and then updatespeciescolour, but if it isn't, return. Going to add that in and run a particular test on a local branch where I spawn in as a Vox with an icon skin tone, aghost, and keep spawning in as other Voxes and see if their tails break. If they don't, I'm going to go back to master and test it again without the fix to see if that's really the cause.

**Comment by KasparoVy** [comment] 2016-12-04 07:36
Still busted as tastyfish's species refactor PR never came out. Thinking of reviewing this issue and re-opening the fix PR.

**Comment by KasparoVy** [comment] 2017-02-12 03:40
No idea why I didn't think of this method sooner 🤦‍

**Closed** 2017-02-15 07:24 UTC
Labels: Bug, Sprites
