### ISSUE TITLE
Laptop Text Files go missing

### ISSUE THREAD

**Issue by StreakyHaddock** [ParadiseSS13/Paradise#7910] opened 2017-07-30 16:22 UTC
**Problem Description**:
When I create a text file in my laptop or tablet in the file manager, it deletes itself not soon afterwards. The Paper Scanner also seems to eat the paper but never produce any file.

**What did you expect to happen**: 
Because it would make the ability to print and create text files and scan paper utterly worthless, as well as the P2P file system. Empty text files seem to last, though.

**What happened instead**:
I expected the files to remain, so I could print them off when needed, or scan in evidence or transcripts for easy file management.

**Why is this bad/What are the consequences:**
I have no use for laptops anymore.

**Steps to reproduce the problem**:
Create a New Data File in the NTOS File Manager. Name it. Click view. Then Edit. Put text inside the new file and click 'close'. The file will remain for about 16-20 seconds before it will delete itself from the viewer.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
I installed standard power/battery stuff, the network card and the printer module. I didn't install the tesla power thing, or the command shuttle recall thing or whatever. 
It is worth mentioning that files that are created, but are NOT edited seem to remain as one would expect.
The Files also delete themselves whether you put an IA Template in there, or simply one word.

**Comment by MarsM0nd** [comment] 2017-07-31 12:34
Duplicate of #7049

**Comment by tigercat2000** [comment] 2017-08-14 18:26
#7966

**Closed by tigercat2000** 2017-08-14 18:26 UTC
