### ISSUE TITLE
Can change suit sensors while being garroted

### ISSUE THREAD

**Issue by Shadow-Quill** [ParadiseSS13/Paradise#10579] opened 2019-01-02 06:16 UTC
**Problem Description**:

Title.

**What did you expect to happen**: 

Someone not being able to change their suit sensors while being garroted.

**What happened instead**:

They were able to change their suit sensors.

**Why is this bad/What are the consequences:**

1) Garrote Sec Officer.
2) Disable sensors.
3) DETECTIVE COMES KNOCKING ASKING YOU TO OPEN THE CABINET WITH THE BODY IN IT.

**Steps to reproduce the problem**:

1) Garrote.
2) As garrotee, change suit sensors.
3) Notice how you can do that even though you're focused on how easy it is to breath around the garrote.

**When did the problem start happening**:

Not sure when.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**

no

**Comment by KasparoVy** [comment] 2019-01-02 13:05
Just open it up mate

**Comment by FunnyMan3595** [comment] 2024-03-23 09:10
Seems to be working fine. Can change sensors before the grip is reinforced, but not after. Either fixed in the intervening years, or was always working as intended.

**Closed by FunnyMan3595** 2024-03-23 09:10 UTC
Labels: Bug
