### ISSUE TITLE
Audio recorder stop working when implanted in the chest using cavity sugery

### ISSUE THREAD

**Issue by Lariag** [ParadiseSS13/Paradise#7722] opened 2017-07-06 00:51 UTC
**Problem Description**:
What is the problem?
The audio recorder tape is full when extracted, but no more audio is recorded. Only the audio before the the implanting.

**What did you expect to happen**: 
The recorder would record the heartbeat and at least, everything the implanted person said.

Why do you think this is a bug?
It's a recorder, it should record the sound from the surroundings. Like the heartbeat or the voice of the implanted character. I guess the game stops processing implanted objects?

**What happened instead**:
How is what happened different from what you expected?
When we extracted the recorder and printed the transcript, it only had the words that we said before putting it inside the chest cavity.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It would be really useful to implant a recorder to spy conversations in an undetectable way.

**Steps to reproduce the problem**:
1. Get an audio recorder, with an empty tape.
2. Turn it on.
3. Implant in someone's chest using cavity surgery.
4. Wait a while, talk and do regular life.
5. Extract the recorder and print the transcript.
6. Read the transcript.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
I washed the recorder before putting it in and the tape was full when I took it out.

This is the transcript:
![recorderchest](https://user-images.githubusercontent.com/20671585/27891421-042a7a80-61fa-11e7-86cc-2784368f04a7.png)

**Comment by taukausanake** [comment] 2017-07-06 01:07
> I guess the game stops processing implanted objects?

Working as Intended? Pretty sure we don't have heartbeat to text. At the very least it would be interesting for it to record sounds from _outside_ the body but that would be better suited for a real implant I feel

**Comment by tigercat2000** [comment] 2017-07-06 01:08
The heartbeat portion of this is definitely a feature request; However, it seems like there might be something wrong with the recursive hear_say checks in saycode. Objects shouldn't stop listening just because they're inside a mob's... implanted list?

**Comment by Alriac** [comment] 2017-07-06 01:13
The heartbeat makes sense but looks like a bad feature, it would just spam the entire transcription.
Maybe the recorder is incapable to get sounds while inside the body and what we actually need is a new implant, ready to hear the surrounding area from inside a body as you say.

**Comment by Rumiluntti** [comment] 2017-07-10 19:41
It should also record farts when inside you.
For consistency.

**Comment by Crazylemon64** [comment] 2018-08-28 06:56
Heartbeat is definitely a feature request. The `hear_say` stack needs to be repaired, here, however.

**Comment by JimKil3** [comment] 2023-10-02 12:57
fixed by #18016

**Closed by JimKil3** 2023-10-02 12:57 UTC
Labels: Bug
