### ISSUE TITLE
Decapitated changeling missing their [null] on examine.

### ISSUE THREAD

**Issue by Christer2222** [ParadiseSS13/Paradise#18740] opened 2022-08-07 20:25 UTC
**Issue Description**:

Examine message of a decapitated changeling does not display what they are missing properly.

**What did you expect to happen**: 

To show that the changeling is missing their head.

**What happened instead**:

The message did not properly get displayed.

**Why is this bad/What are the consequences**:

Null strings are bad looking.

**Steps to reproduce the problem**:

(This is just what I saw, I am not sure if the extra points matter)
1. Spectate and orbit a changeling.
(1.1 Have the changeling die.)
(1.2 Have the changeling enter stasis and revive.)
2. Have the changeling decapitated.
3. Examine body.

**When did the problem start happening**:

Noticed it today 07.08.2022.

**Extra information**:

![image](https://user-images.githubusercontent.com/25958019/183309262-9434269c-2e5a-42d5-b277-dcfa42d8d3aa.png)

**Comment by lewcc** [comment] 2022-08-07 20:26
I've also seen this a lot recently on people who get early ejected from cloning. Probably the same sort of issue.

**Comment by Sirryan2002** [comment] 2022-08-08 04:21
duplicate of #10136

**Closed by Sirryan2002** 2022-08-08 04:21 UTC
Labels: Bug
