### ISSUE TITLE
SR has a chance to break

### ISSUE THREAD

**Issue by LtDiggs** [ParadiseSS13/Paradise#9331] opened 2018-08-08 10:51 UTC
**Problem Description**:
Currently certain chems tend to be weird from time to time. SR sometimes likes to break leaving the chemical in the body and not reviving them.

**What did you expect to happen**: 
When someone is fed a pill of SR it should show one of two messages: "[Person] rises from the dead!" or something along the lines; "[Person] seems to not react, maybe try again later?"

**What happened instead**:
Instead of either, no prompt was given and the unit of SR remained in the body. The SR reacts to nothing so the body does not gain genetics damage. Adding more will just add on to the amount of units in the body. 

![sr broke](https://user-images.githubusercontent.com/41313156/43832589-494ea3a8-9b4b-11e8-80a5-dcc4fa16fd0d.PNG)

**Why is this bad/What are the consequences:**
When SR does this it makes the already dead body unrevivable. Meaning any vox are doomed and slimes and plasmamen are screwed.

**Steps to reproduce the problem**:
Reproducing this is hard because it's kind of random for it to happen. Upon writing this I have experienced it twice. The first time was near the end of round so I was forced to debrain them. Both times also did happen on vox. It's not fully broken though since its worked on other vox.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: During the same round I was able to revive a different vox using SR and for some reason it also mended their bones fully.
![sr weird](https://user-images.githubusercontent.com/41313156/43833009-a2361fcc-9b4c-11e8-81fa-0eec41546cdc.PNG)
![sr weird2](https://user-images.githubusercontent.com/41313156/43833018-a76b2348-9b4c-11e8-92a9-c603557cb829.PNG)

**Comment by Citinited** [comment] 2018-08-08 14:00
maybe this is a feature, it is *strange* reagent after all

**Comment by Pennwick** [comment] 2018-08-10 21:26
The second Vox's bones were fixed by the Adminordrazine. So it looks like the SR just acted as intended.

**Comment by Fox-McCloud** [comment] 2018-08-13 02:12
Where they husked or suiciding?

If they were, SR is going to fail.

**Comment by LtDiggs** [comment] 2018-08-15 06:35
Nope, they were just dead. Both were basically the same except the SR on the first one just didn't react.

**Comment by Crazylemon64** [comment] 2018-08-28 01:48
Without instructions on how to reliably reproduce, this is not going to be easily fixed.

**Closed** 2018-10-31 23:59 UTC
Labels: Cannot Reproduce, Needs Info
