### ISSUE TITLE
Mining shuttle hull connects with station walls

### ISSUE THREAD

**Issue by Accinator50** [ParadiseSS13/Paradise#21040] opened 2023-05-06 17:24 UTC
**Issue Description**:

The hull of the mining shuttle melts into the wall of the station.

**What did you expect to happen**: 
That this wouldn't happen.

**What happened instead**:
It happened.
![grafik](https://user-images.githubusercontent.com/44909173/236638345-ca6546bc-d991-4e3e-9982-e35a72d16f64.png)

**Why is this bad/What are the consequences**:
The mining shuttle doesn't look like a shuttle.

**Steps to reproduce the problem**:
Look at the mining shuttle.

**When did the problem start happening**:
Unknown but probably recently.

**Comment by Contrabang** [comment] 2023-05-06 17:26
Caused by #20795 , I've been meaning to make a bug report for this, thanks!

**Comment by Sirryan2002** [comment] 2023-06-11 00:03
duplicate of #20948

**Closed by Sirryan2002** 2023-06-11 00:03 UTC
Labels: Bug
