### ISSUE TITLE
Antag HUD displaying for borged vampies

### ISSUE THREAD

**Issue by DarkPyrolord** [ParadiseSS13/Paradise#4661] opened 2016-06-13 15:08 UTC
**Problem Description**:
Antag HUD displays for borged vampires if you have a diagnostic HUD active.

**What did you expect to happen**: 
Just expected to see normal borg status bars.

**What happened instead**:
Got the status plus a big red antag HUD symbol beside the borg.

**Why is this bad/What are the consequences:**
Well, antag HUD shouldn't really be a thing that diagnostic HUDs can pick up...

**Steps to reproduce the problem**:
Get Diagnostic HUD/NV Diagnostic HUD.
Borg vampire.
Watch as an antag HUD symbol shows up.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 

Normal vampire round, all but an adminbus shadowling near the end which was unrelated.
Also screenshot of this in action:
![VampHUD](http://i.imgur.com/iuQHVsU.png)

**Comment by Ar3nn** [comment] 2016-06-13 19:48
Spray it with holy water!

**Comment by KasparoVy** [comment] 2016-06-15 16:19
I think this is the case because the mob's mind still registers it as a vampire.

If that is so, then I don't believe this to be a bug-- but instead, wholly intentional, as putting that vampire's brain back into a body (should? haven't confirmed) grant them the ability to continue antagging again as per usual whereas if you cleared their antag mind status and thus, make them invisible on antagHUD, they won't be able to be a vampire again even if they get put back into a body.

**Comment by LittleBigKid2000** [comment] 2016-06-17 22:00
Considering vampires can be tested and such, I'd write this off as Working as Intended™.

Also, I did some testing.
Cultists and non-head revs are deconverted.
Shadowlings and shadowling thralls are silently (As in, no message) deconverted/lose their shadowling status.
Changelings lose their changeling status, but their icon is shown for a second.
Headrev MMIs are refused.
Vampires, traitors, nuclear operatives, wizards, and abductors are shown as such on the diagnostic hud. Vampires aren't able to use their abilities, wizards are, provided the ability doesn't require the wizard outfit to be worn.

**Comment by Ar3nn** [comment] 2016-06-21 07:38
Wait but in what scenario could a wiznerd be borged? Wizard death ends the round.

**Comment by LittleBigKid2000** [comment] 2016-06-21 09:11
Ragin' mages and apprentices

**Comment by theColdflame** [comment] 2016-09-13 01:15
@Fox-McCloud @TheDZD 

(assumedly) fixed by #5128

**Closed** 2016-10-11 00:24 UTC
Labels: Bug
