### ISSUE TITLE
Strange crematorium camera bug

### ISSUE THREAD

**Issue by lirdos** [ParadiseSS13/Paradise#12822] opened 2019-12-18 21:57 UTC
**Issue Description**:
If you orbit someone, and then disconnect, and then that someone gets cremated, your camera will no longer lock onto you, the player.

**What did you expect to happen**: 
Camera should stay locked on my ghost.

**What happened instead**:
Camera stayed inside the crematorium.

**Why is this bad/What are the consequences**:
Pretty inconvenient if you wanted to observe the round, I'd imagine.

**Steps to reproduce the problem**:
-Orbit someone
-at this point my internet shut off, so my client was disconnected
-Have someone cremate that someone. Don't open the crematorium.
-Come back, click-teleport outside the crematorium, camera no longer focused on you

**When did the problem start happening**:
Not sure. Probably an older bug?

**Extra information**:
I've included a screenshot, to explain the result better, if that helps.
![image](https://user-images.githubusercontent.com/59033413/71126196-8c4f6780-21b6-11ea-970e-559c2f628707.png)

**Comment by meow20** [comment] 2020-11-05 07:55
Will happen in morgue trays too

**Comment by matttheficus** [comment] 2022-06-22 14:34
Fixed by #17221 and a duplicate of #10840 , albeit a subtype of the trays.

**Closed by matttheficus** 2022-06-22 14:34 UTC
Labels: Bug, Duplicate
