### ISSUE TITLE
Syndie Comms Agent Camera Bug

### ISSUE THREAD

**Issue by ChewedPencil** [ParadiseSS13/Paradise#13225] opened 2020-03-30 06:21 UTC
**Issue Description**:
WHen the Syndie COmms agent uses the camera in an area with static, it will show everything there as if it were xray vision or ghost.

**What did you expect to happen**: 

**What happened instead**:

**Why is this bad/What are the consequences**:

**Steps to reproduce the problem**:
open the camera console from the syndie outpost in an area without cameras

**When did the problem start happening**:

**Extra information**:
when someone walks by and refreshes the tiles, it will go back to static if they have lights on

**Comment by Henri215** [comment] 2023-05-11 00:28
Duplicate of https://github.com/ParadiseSS13/Paradise/issues/13948, closing this since the newer issue report is more detailed.

**Closed by Henri215** 2023-05-11 00:28 UTC
Labels: Bug, Duplicate
