### ISSUE TITLE
Krav Maga gloves let you disarm undroppable things to some very broken effects

### ISSUE THREAD

**Issue by SkeletalElite** [ParadiseSS13/Paradise#11084] opened 2019-03-20 15:44 UTC
**Problem Description**:
See title

**What did you expect to happen**: 
For krav maga to not take things out of someones hand if they have no drop

**What happened instead**:
The krav maga user gets the item in their hand and the item duplicates. Resutiling in the krav maga user having a new item in hand that they cant drop but the person with no drop also still has the item.

**Why is this bad/What are the consequences:**
You can kind of fuck yourself over by getting stuff stuck in your hand. Also it just doesn't make sense and means you cant disarm someone with no drop in an attempt to go for a push.

**Steps to reproduce the problem**:
Disarm spam someone with a no drop item. I know the mime finger gun works and so does any item combined with an anti drop implant.

**When did the problem start happening**:
Unsure, I first noticed on the  mime finger gun so it could have been around that time.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**: 

probably something to do with the fact that disarming with krav maga puts what you disarm right into your hand. Probably doesn't check for no drop when doing this. Also it doesn't even seem to necesarily "duplicate" the item because the stun baton that I found this out with seemed to share properties with the one in the anti drop persons hand.

**Comment by Ralta** [comment] 2019-03-20 16:07
Similar in concept to this:

https://github.com/ParadiseSS13/Paradise/issues/8178

Removing the hand of someone with no-drop causes them to drop the item, but the item is still flagged as undroppable, so you can then pick it up and become unable to drop it.

**Comment by taukausanake** [comment] 2019-03-20 16:16
Also duplicate of #11005

**Closed** 2019-03-20 19:20 UTC
