### ISSUE TITLE
THERES A PIECE OF SNOW UNDER THE DOOR OF MR CHANGS

### ISSUE THREAD

**Issue by pinatacolada** [ParadiseSS13/Paradise#8564] opened 2018-01-17 20:08 UTC
![5bd7ee6db0](https://user-images.githubusercontent.com/13833056/35064476-18833aaa-fbc2-11e7-8af4-30e1a5a551e1.png)

![2ab4c9b7a7](https://user-images.githubusercontent.com/13833056/35064492-248ef82a-fbc2-11e7-95fc-2d8ebad7e669.jpg)

@FreeStylaLT THIS MAKES ME VERY UNCOMFORTABLE PLS ADVISE

**Comment by taukausanake** [comment] 2018-01-17 20:14
Duplicate of #8557, but this one has an image

**Comment by FreeStylaLT** [comment] 2018-01-17 20:32
![img](https://i.warosu.org/data/g/img/0481/86/1432756870303.png)

**Closed** 2018-03-08 20:54 UTC

**Comment by taukausanake** [comment] 2018-03-09 06:46
Uhhhh are you sure about that @tigercat2000? I mean I haven't checked lately but I'd like to know

**Comment by FreeStylaLT** [comment] 2018-03-09 07:53
this will forever haunt us won't it

**Comment by taukausanake** [comment] 2018-03-09 13:57
It must not be an issue anymore I guess ¯\_(ツ)_/¯
