### ISSUE TITLE
Target recognised as cryoing, causing new objectives rolled despite being dead/husked.

### ISSUE THREAD

**Issue by ItsMarmite** [ParadiseSS13/Paradise#16283] opened 2021-07-01 23:46 UTC
**Issue Description**:
Despite target being dead, objectives randomised as if the target had cryoed.

**What did you expect to happen**: 
As per normal, objectives only randomise upon the target actually cryoing or being SSD for longer than 20 minutes.

**What happened instead**:
Upon leaving on the shuttle to CC, the target randomised in my objectives.

**Why is this bad/What are the consequences**:
How else are people supposed to get the epic greentext? In reality, its definitely an issue when your objectives can change randomly despite having completed them

**Steps to reproduce the problem**:
Kill target as Changeling. Board right most arrivals pod. Shuttle leaves, alongside the pods. Objective changes.

**When did the problem start happening**:
Happened last round. Apparently there was no Admin involvement in the traitor panel according to Matt so it seems like there's a bug in regards to targets being recognised as cryoing.

**Extra information**:
Given it was the end of the round, its possible the guy who played Bob Oakland closed his client, thus causing it to recognise as him 'cryoing'? Unsure.

https://cdn.discordapp.com/attachments/565872046312259594/860298134026715146/unknown.png
https://cdn.discordapp.com/attachments/565872046312259594/860298336292700200/unknown.png

**Comment by farie82** [comment] 2021-07-02 06:15
Most likely caused by a bug fixed in #14335 where objectives which failed to create stick around and randomly causing target got lost changes.
Will need to double check though

**Comment by matttheficus** [comment] 2022-06-21 18:15
Hard to reproduce as well as stale.

**Closed by matttheficus** 2022-06-21 18:15 UTC
