### ISSUE TITLE
Cyborg magnetic grippers not functioning properly with APCs.

### ISSUE THREAD

**Issue by Norwes1** [ParadiseSS13/Paradise#12627] opened 2019-10-22 04:05 UTC
**Issue Description**:

When using a magnetic gripper on a station maintenance drone, I was unable to insert a battery properly. The battery disappeared from the gripper, but the APC I was inserting it into did not update.

**What did you expect to happen**: 

Normally, the battery should disappear from the gripper's inventory, and the APC should update both its sprite and in-game menu showing that a battery is now inserted.

**What happened instead**:

The battery disappeared from the gripper, and the APC sprite was unchanged. I assessed and confirmed that I was able to pick up and drop the battery appropriately before attempting to insert it, and that another player (Fatbackwards) encountered the same bug when attempting to do so as a maintenance drone.

**Why is this bad/What are the consequences**:

This effectively prevents cyborgs and maintenance drones from constructing or repairing APCs without admin intervention.

**Steps to reproduce the problem**:

This original bug was tested on the Assembly Line of Boxstation, west of Engineering. I recommend spawning in as a maintenance drone, grabbing a spare battery from the EngiVend south of the drone fabricator, then heading west to the un-constructed APC frame at the Assembly line. Finish its construction (place on wall, wire, electronics, screwdriver), then try inserting a battery. The APC sprite should be unchanged while the battery disappears from the gripper.

**When did the problem start happening**:

I just noticed it as of submitting this report.

**Extra information**:

**Comment by SteelSlayer** [comment] 2019-10-22 04:23
Duplicate of #12541
And got a fix coming in #12592

**Closed** 2020-04-11 05:21 UTC
