### ISSUE TITLE
You can pick up emitter beams and create an invisible deathtrap

### ISSUE THREAD

**Issue by Citinited** [ParadiseSS13/Paradise#11754] opened 2019-06-25 21:54 UTC
**Problem Description**:
I can pick up emitter beams via alt-click, giving me an emitter projectile that I can drop, hit people with, give to other people, etc.

This projectile doesn't despawn (or despawns after a very long time) and is invisible (I can't even see it in my hand), but doesn't despawn, allowing me to do all manner of awesome broken stuff with it. It can still be stripped by people clicking the correct hand in the strip menu

**What did you expect to happen**: 
I shouldn't be able to pick up projectiles via alt-click

**What happened instead**:
I can pick up the emitter shot

**Why is this bad/What are the consequences:**
It's insanely OP if you can pile up a couple of these on one turf, and completely invisible damage dealers should just never be a thing

**Steps to reproduce the problem**:
The easiest way to do this is as follows:
1. Set up an active emitter.
2. Construct two reflector cubes pointing into each other and have the emitter fire into one of them
3. Alt-click the tile between them
4. When an emitter shot appears on the menu, click it and wait until its sprite disappears.
5. You now have an emitter projectile in your hand and can do whatever with it!

See video below:
https://imgur.com/f1DQrmi

**When did the problem start happening**:
I actually discovered this bug a few years back but never bothered to report it at the time, so at least since then

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Easiest to do with reflector cubes, but you can also do it with dead IPCs strapped to chairs

**Comment by Sihsse** [comment] 2019-06-25 23:38
I would like a bit of clarification on the possibly related stuff.
When recreating this effect exactly how are you implementing dead IPCs strapped to chairs in order to substitute the reflector cubes.

**Comment by Citinited** [comment] 2019-06-26 00:08
You just strap an IPC to a chair in the way of the emitter beam, wait a bit and eventually one of the emitter beams will sort of lag out and not properly connect - this is when you can pick it up via alt-click. The IPC has to be dead (not sure why this is important but it seems to be a required part of the process)

**Comment by farie82** [comment] 2022-06-18 22:47
Unable to reproduce using current code, must have gotten fixed in a PR I can't quickly find. emitter projectiles are `ABSTRACT` and thus prevent you picking them up. Along with some other things but the `ABSTRACT` flag is the first thing that causes it not to work

**Closed by farie82** 2022-06-18 22:47 UTC
