### ISSUE TITLE
NTOS Fatal Error from brig timers

### ISSUE THREAD

**Issue by MysticLiger** [ParadiseSS13/Paradise#14561] opened 2020-10-08 01:05 UTC
**Issue Description**:
Observing and I clicked a brig timer and it gave me the equivalent of a BSOD but for TGUI
Said to put this in:
TypeError: Unable to get property 'length' of undefined or null reference
   at t.BrigTimer (http://127.0.0.1:56508/tmp16152/tgui.bundle.js:5:78285)
   at Anonymous function (http://127.0.0.1:56508/tmp16152/tgui.bundle.js:1:183941)
   at Anonymous function (http://127.0.0.1:56508/tmp16152/tgui.bundle.js:1:183911)
   at Se (http://127.0.0.1:56508/tmp16152/tgui.bundle.js:1:183889)
   at Anonymous function (http://127.0.0.1:56508/tmp16152/tgui.bundle.js:1:183831)
   at Se (http://127.0.0.1:56508/tmp16152/tgui.bundle.js:1:183773)
   at Fe (http://127.0.0.1:56508/tmp16152/tgui.bundle.js:1:191037)
   at De (http://127.0.0.1:56508/tmp16152/tgui.bundle.js:1:191276)
   at Anonymous function (http://127.0.0.1:56508/tmp16152/tgui.bundle.js:1:114568)
   at Anonymous function (http://127.0.0.1:56508/tmp16152/tgui.bundle.js:1:114293)

User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0

**What did you expect to happen**: 
For brig timers to show me.. y'know what it would normally show me. It was an active timer by the way.

**What happened instead**:
The TGUI equivalent to a BSOD. Pretty spooky not gonna lie.
Said this:
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Please remain calm. Get to the nearest NTNet workstation and send the copy of the following stack trace to: https://github.com/ParadiseSS13/Paradise. Thank you for your cooperation. 

**Why is this bad/What are the consequences**:
Uhhh....

**Steps to reproduce the problem**:
>Be around, ghost or player I dunno, I was ghost at the time.
>Click on brig timer
>Have bad luck? I dunno, it gave me the NTOS Fatal Error so.
>Be led here since it says to go here.

**When did the problem start happening**:
This is the only time it's happened to me.

**Extra information**:
🤷  First time filling one of these in and if I didn't even need to make an issue here then woops.

**Comment by Spacemanspark** [comment] 2020-10-08 01:10
Mystic broke the game again

**Comment by Kyep** [comment] 2020-10-08 01:37
Not able to reproduce this.
The only .length checks in BrigTimer.js are data.spns.length, and that's set in door_timer/tgui_static_data(), so it should always be defined.

**Comment by AffectedArc07** [comment] 2021-03-04 16:28
Should be fixed. Feel free to re-open if not.

**Closed by AffectedArc07** 2021-03-04 16:28 UTC
