### ISSUE TITLE
Records are still horribly broken

### ISSUE THREAD

**Issue by AceMcLazer** [ParadiseSS13/Paradise#3053] opened 2015-12-30 03:04 UTC
The Constant Crashes makes playing Sec or Updating Medical files Nearly unplayable. It can Ruin high-tension or high action sequences by putting the breaks on suddenlly to restart the client. I nearly died the last time I crashed from changing records do to a antag sneaking up on me. Its not a Bug that makes the game unplayable. but Really puts a damper on it because you have to PLAN on crashing to get anything done as warden, detective a officer with a Laptop on the go, or a doctor updating medical files.

**Comment by Fox-McCloud** [comment] 2015-12-30 03:45
Which version of BYOND are you using?

**Comment by TheDZD** [comment] 2015-12-30 06:39
Duplicate of #3046

**Closed by TheDZD** 2015-12-30 06:39 UTC
Labels: Duplicate

**Comment by AceMcLazer** [comment] 2015-12-31 00:17
@Fox-McCloud The most recent version I think. is that have somothing to do with it?
