### ISSUE TITLE
When assassination targets cryos as changeling the target is rolled twice and invalid

### ISSUE THREAD

**Issue by Christer2222** [ParadiseSS13/Paradise#19673] opened 2022-11-12 00:37 UTC
**Issue Description**:

Played changeling, had my target cryo, got 2 rerolls, but the target was invalid and I had to ahelp for a new target.

**What did you expect to happen**: 

To get a proper target.

**What happened instead**:

Improper target.

**Why is this bad/What are the consequences**:

You want to kill your target.

**Steps to reproduce the problem**:

1. Play changeling.
2. Have assassination objective.
3. Have target cryo.

**When did the problem start happening**:

Noticed today 12.11.2022.

**Extra information**:

Evan Ludwig was my original target. Then I got 2 rerolls (note the target was the same both times), and the final target wasnt even there, so I had to ahelp to get a new one.
![image](https://user-images.githubusercontent.com/25958019/201447684-c96920b9-640b-4c4b-962f-8ac820e1deec.png)

**Comment by GDNgit** [comment] 2022-11-12 00:42
probably the same as #19433

**Comment by silverplatedelta** [comment] 2024-11-29 23:04
Closing this as a duplicate of #19433

**Closed by silverplatedelta** 2024-11-29 23:04 UTC
Labels: Bug
