### ISSUE TITLE
Hijackers Can't Buy Hijack Items

### ISSUE THREAD

**Issue by Eric6426-Blossom** [ParadiseSS13/Paradise#19822] opened 2022-12-01 23:42 UTC
**Issue Description**:

Hijacker-only items are not purchaseable by hijackers

**What did you expect to happen**: 

They aren't

**What happened instead**:

They got told they can't purchase them

**Why is this bad/What are the consequences**:

Hijackers should have access to their unique toys that are locked behind hijack only

**Steps to reproduce the problem**:

be hijack, try to buy hijack item

**When did the problem start happening**:

Yesterday, seems like, at least to me, few people encountering this issue

**Extra information**:

**Comment by Calyxman** [comment] 2022-12-01 23:53
:((((((
I was said hijacker
Both times I had to ahelp
Admins had to spawn it in
I just want my fun kill bang pow toys

**Comment by SteelSlayer** [comment] 2022-12-02 01:54
Unfortunately I cannot reproduce this. I'm able to buy hijack items if I have a hijack objective. Any other information you guys can give? @Calyxman, were you just a round-start traitor who automatically received a hijack objective?

**Comment by Eric6426-Blossom** [comment] 2022-12-04 19:11
@SteelSlayer Yeah, they had Hijack from the roundstart roll, two shifts in two different days (I was there, in both, their luck is surprising) but in neither case they could buy the items as far as they reported.

**Comment by Contrabang** [comment] 2023-06-05 19:06
Not able to reproduce after 6+ months, gonna close this

**Closed by Contrabang** 2023-06-05 19:06 UTC
Labels: Cannot Reproduce

**Comment by Contrabang** [comment] 2023-06-05 19:07
I meant to close this as incomplete, whoops.
