### ISSUE TITLE
Morgue Trays are not updating with correct status

### ISSUE THREAD

**Issue by Komrad822** [ParadiseSS13/Paradise#20429] opened 2023-02-14 23:07 UTC
**Issue Description**:

Currently, morgue trays do not update their signal status whether the ghost is in the body of not. If the ghost is not in the body upon initial morgueing, the tray will stay red even if they re-enter their corpse.

**What did you expect to happen**: 

I expected to enter my corpse and the morgue tray light turn green.

**What happened instead**:

The tray light stayed red.

**Why is this bad/What are the consequences**:

The trays are meant to update depending on the status of the body and ghost, THUS these should be updating quickly as theres not always a coroner to monitor said trays and people only have a small chance of being revived after being morgue'd. People who are not DNR'd basically become dnr'd.

**Steps to reproduce the problem**:

1. Die
2. Leave your body
3. Have your body be placed in a body bag and then into a morgue tray
4. Notice the light is red.
5. Re-enter your corpse
6. Notice again the light doesnt change.

**When did the problem start happening**:

Unknown but for a good few weeks now.

**Extra information**:

I asked Gachapod to confirm it wasn't a visual bug on my end as for them as well, the light wasnt updating.

![image](https://user-images.githubusercontent.com/94168850/218883317-5a37dae2-274d-450e-b1a0-89ac027c6945.png)

![image](https://user-images.githubusercontent.com/94168850/218883337-c5a8718b-a5d6-4680-a487-829bf4ad8a73.png)

**Comment by Vi3trice** [comment] 2023-02-14 23:30
That's not how the morgues work. Ghosts only need to be connected at the minimum.

If it's red in the first place, that means it's completely unrevivable. Either you commited suicide, your body has somehow lost its ref to its mind or client, or the ghost is not allowed to actually reenter the body proper.

**Comment by Komrad822** [comment] 2023-02-15 04:11
> If it's red in the first place, that means it's completely unrevivable. Either you committed suicide, your body has somehow lost its ref to its mind or client, or the ghost is not allowed to actually reenter the body proper.

None of these things happened though. I was a ghost, I was connected to server, I died via clawing and batong. At the least it should have been purple.

NOTE: for this round, this was a body (cultist) that was offered up as the original owner had gone SSD. Thus even then, im still now tied to said body and should be revivable, thus if this was the issue, then thats another can of worms.

**Comment by warriorstar-orion** [comment] 2023-02-15 20:39
The situation you're describing sounds like exactly the sort of thing that might cause what Vi3 suggested--unexpected behavior when a mind that was a ghost is transferred to a body and then that body is killed. That said, one would expect this to crop up more often if that were the case, since taking offered up bodies isn't an uncommon practices. Perhaps the person whose body it was originally did something weird to it before you gained possession of it.

So if it could be reproduced, that would be ideal.

**Comment by Vi3trice** [comment] 2023-02-15 23:22
> None of these things happened though. I was a ghost, I was connected to server, I died via clawing and batong. At the least it should have been purple.

And there's the gist of your problem. Your body met the requirements for unrevivable, not connected ghost somehow. So either the body lost the mind at some point, or it somehow doesn't even think it has a ghost, or worse, it doesn't even think you're connected.

**Comment by Komrad822** [comment] 2023-02-16 00:07
> So if it could be reproduced, that would be ideal.

Ill get on this then.

**Comment by Komrad822** [comment] 2023-02-21 05:35
I have video proof that not only will offered bodies in trays not work, they also break revival mechanics. Darren and I went to testing it.

**Comment by Vi3trice** [comment] 2023-02-21 06:45
Well that's not the trays being broken then. It's the state of the mob not being revivable at all when offering them to someone else. Keep it simple.

**Comment by Komrad822** [comment] 2023-02-21 17:41
To note, trays only update when they are opened and closed, personally dont like but its intended.

Shall I make another issue report with what I discovered or edit the current issue?

**Comment by warriorstar-orion** [comment] 2023-02-22 03:44
> To note, trays only update when they are opened and closed, personally dont like but its intended.
> 
> Shall I make another issue report with what I discovered or edit the current post?

File it as a separate issue, please. Thanks for taking the time to verify the behavior you're seeing.

**Closed** 2023-02-22 13:03 UTC
Labels: Need Verification
