### ISSUE TITLE
Reports of people not getting blob alert (peersonally unconfirmedd

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#18857] opened 2022-08-18 23:16 UTC
**Issue Description**:

Blob alert not displaying, only sound playing, from reports

**What did you expect to happen**: 

Sound AND text to show

**What happened instead**:

Only sound apperently

**Why is this bad/What are the consequences**:

People not knowing they are blobs until bloated text

**Steps to reproduce the problem**:

Spawn as blob, see if text message shows

**Comment by Sirryan2002** [comment] 2022-08-18 23:23
duplicate of #2890 theory is that byond just eats messages sometimes

**Closed** 2023-09-06 17:08 UTC
Labels: Bug, Need Verification
