### ISSUE TITLE
Changeling Resonant Shriek does nothing if restrained but still uses chemicals

### ISSUE THREAD

**Issue by Lariag** [ParadiseSS13/Paradise#17942] opened 2022-06-10 22:23 UTC
**Issue Description**:
As a changeling with Resonant Shriek  ability, using it while being handcuffed and dragged by someone does nothing but uses the chemicals anyway.

**What did you expect to happen**: 
Either the Resonant Shriek ability activates or no chemicals are used, depending on the intended behavior.

**What happened instead**:
The ability didn't activate and the chemicals were used.

**Why is this bad/What are the consequences**:
If caught, you can waste all of your chemicals for nothing and are left helpless without the opportunity to activate another ability.

**Steps to reproduce the problem**:
1. Be a changeling and get the Resonant Shriek ability.
2. Get restrained.
3. Get dragged away.
4. Activate the ability.

**When did the problem start happening**:
My last changeling play, although I never used that ability in a similar situation before.

**Extra information**:
I don't remember the exact date, but I ahelped to ask if it was a bug. I guess someone can check the logs and get the date and round.

**Comment by SteelSlayer** [comment] 2022-06-19 01:34
I'm unable to reproduce this issue. There are no checks for being restrained or pulled when using this ability, even before my refactor in #17774.

When you say it does nothing, what do you mean exactly? Did you hear the shriek sound go off when you used the ability? This ability does not affect people who have good enough ear protection and it would appear to do nothing to them, if that's what you mean.

**Comment by Burzah** [comment] 2023-08-15 22:07
Could not reproduce this one. As no additional information was provided to the questions above and it has been over a year since reported, I am going to close this issue. Thank you for making the report.

**Closed by Burzah** 2023-08-15 22:07 UTC
Labels: Cannot Reproduce
