### ISSUE TITLE
Pod Weapon Replication

### ISSUE THREAD

**Issue by TullyBurnalot** [ParadiseSS13/Paradise#4582] opened 2016-06-03 21:36 UTC
**Problem Description**:
Upon removing a Weapon System from the pod, you cannot install another one, as it says that it already has one installed. Throwing away removed Weapons Systems allows you to spawn unlimited amounts of them

**What did you expect to happen**: 
Being capable of swapping ONE Weapons System for another.

**What happened instead**:
Physics broke, and the pod is apparently still capable of using disablers after a million of them were removed.

**Why is this bad/What are the consequences:**
No lethal option for pods, and infinite replication capabilities.

**Steps to reproduce the problem**:
Crowbar pod, remove Weapons System, try exchanging.

**Comment by FlattestGuitar** [comment] 2016-06-03 23:24
@IK3I

**Comment by ScratKnapp** [comment] 2016-06-04 19:37
This also goes for the passenger seat and lootbox things. Once you put one in, it can never be taken out, and IIRC the lootbox doesn't even work either.

**Comment by Twinmold93** [comment] 2016-06-12 01:14
This issue is fixed with https://github.com/ParadiseSS13/Paradise/pull/4637. The issue isn't duplication, but pulling the same module out. If you set it on the ground, it will teleport to your hand when you take it out again. This merge will fix it on next patch.

**Closed** 2016-06-12 05:53 UTC
Labels: Bug
