### ISSUE TITLE
Able to put a bag of holding inside of another bag of holding

### ISSUE THREAD

**Issue by SkullyRoberts** [ParadiseSS13/Paradise#8759] opened 2018-03-14 01:12 UTC
Reported to me by Blessedtuna
**Problem Description**:
What is the problem?
You are able to put a bag of holding inside of another bag of holding without it causing a singularity to spawn. I had seen Tuna's character with stacked bags of holding, and I asked him how he managed it.

**What did you expect to happen**: 
Why do you think this is a bug?
When a bag of holding is put inside of another bag of holding, a singularity is suppossed to spawn.

**What happened instead**:
How is what happened different from what you expected?
In the right situation, you can put a bag of holding inside another one with no negative consequences

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It allows players to hold an infinite amount of items on their person, limited only by the number of bags they can create.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
According to Tuna:
1) Take bag of holding in one hand, with other bag of holding on your back.
2) Insert it using the E hotkey, rather than the mouse GUI.
3) Fail to create a singularity.
4) Have security search you, find nested bags of holding and give them an aneurism

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Birdtalon** [comment] 2018-03-14 12:03
Duplicate of #8129

**Closed** 2018-03-19 18:54 UTC
