### ISSUE TITLE
Surgery Infections Guaranteed

### ISSUE THREAD

**Issue by Onutsio** [ParadiseSS13/Paradise#7868] opened 2017-07-24 23:32 UTC
**Problem Description**:
No matter how sterile the operating room is made, a patient will always be infected from the drops of blood from opening a incision. Their own blood. From the past few weeks or so of surgeries, nearly every surgery I've done has resulted in a acute infection. I figure this is from the fact that blood on the floor causes infections, and that the patient dropping blood from there being a open incision.

**What did you expect to happen**: 
Doctors should be able to perform clean surgery without having guaranteed infections.

**What happened instead**:
Infections all around!

**Why is this bad/What are the consequences:
Doctors are unable to complete surgeries without always having to administer spaceaccilin.

**Why do you think this is an important issue?
Makes surgery a much bigger hassle than it should be.

**Steps to reproduce the problem**:
Attempt to do surgery, patient bleeds on the ground under them (even after being hemo'd), patient likely gets an infection during the process.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

All of my surgeries in the past week or so have been in brig medical. Though, with a actual surgical table, gloves, and a face mask. And being sure to clean the entire medical area with soap prior to starting a new one.

**Comment by SamHPurp** [comment] 2017-07-24 23:41
@pinatacolada

**Comment by Crazylemon64** [comment] 2017-07-24 23:47
Upon making the initial incision, <a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/surgery/generic.dm#L47>the limb is considered "Open"</a>.

When the limb is open, <a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/surgery/organs/blood.dm#L80-L81>the patient begins to bleed</a>, leaving blood decals on their own tile.

When there are blood decals near the patient, <a href=https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/surgery/surgery.dm#L207-L210>the patient begins to develop an infection</a>.

This can be resolved by making the patient's own blood not tick up the germ rate, in the last snippet there.

**Comment by pinatacolada** [comment] 2017-07-25 00:09
i'm very skeptical it's blood decals doing this, if you're going straight to acute infections. You'd need the room to literally be covered in blood, no one wearing masks, using blood stained tools, and like 3 people breathing over the guy. Still I'll keep an eye out, but it's working as intended afaik. For reference, a single blood drop will increment 'germs' by 1 for each surgery step, where a mild infection is at 100 'germs'

One thing though, the hemostat step should stop the bleeding, since, ykno, it *clamps bleeders*

**Comment by Onutsio** [comment] 2017-07-25 00:18
Hemostat doesn't stop the bleeding. Just have tested. That could be the main issue.

**Comment by alexkar598** [comment] 2017-07-25 01:00
I recently tested it and if the patient is clean , there is no blood in room and you are wearing a sterile mask there should not be any infections

**Comment by pinatacolada** [comment] 2017-07-25 01:01
i just tested with like 5 drops of blood in the vicinity and nothing happened

**Comment by Onutsio** [comment] 2017-07-25 01:03
The issue is that blood is coming from the patient. So It's very difficult to keep clean.

**Comment by Denthamos** [comment] 2017-07-25 04:05
I have encountered this as well.  Could clean yourself completely, the patient, the room, and stop the patient from bleeding before putting them on the table, yet they will still become infected.  Even made sure to clean the tools before surgery and clean them once the surgery is completed, but infections still occur.

**Comment by Crazylemon64** [comment] 2017-07-25 06:00
The issue wouldn't be the patient immediately going to acute, but rather always developing a subsequent infection. If the germ level is elevated past 50 points, the infection will proceed to slowly increase until the patient succumbs to it.

However, this would require the patient having germs be spread to them 50 times, which would be rather... unlikely. Normally, there should only be 1 blood splatter per floor tile, which would mean there would only be 1 mess within range of the patient. To result in an infection, 50 steps would need to be attempted, unless the surgeon themself brought the germs along themself. Only if you're operating in highly messy conditions, like a table covered in gore from failed xeno egg removals, would this come into play. The most likely source of infection would then either be the unmasked breathing people in the room, blood-covered tools, or the doctor not being adequately clean.

**Comment by Onutsio** [comment] 2017-07-25 06:08
Blood splatters can stack on floor tiles. Usually leaving 5 or so below a patient after a surgery.

**Comment by alexkar598** [comment] 2017-07-25 11:07
@Denthamos were you wearing a sterile mask? If not its a guarentured mild infection on the internal organs

**Comment by Jountax** [comment] 2017-07-25 22:11
I have caused infections in patients while not wearing a mask. But I was also an IPC at the time, so... Do things that not breathe still need masks?

**Comment by alexkar598** [comment] 2017-07-25 22:21
I tested this today and a 100% sterile room with no blood,the surgeon hands washed and everybody wearing sterile mask in the room and your patient will have no infections

**Comment by ktoma36** [comment] 2017-07-26 01:42
I have been seeing a rising number of patients with infections since the new blood system, up to the point were medical runs out of spacilin almost halfway through the shift. I have done surgeries were the patient hasn't gotten any infections though.

**Comment by Landerlow** [comment] 2017-07-28 11:12
If you take the following steps:

Nitrite/latex gloves
Wash hands
Wear face mask
Wear surgical cap
Clean OR

There should be no infection after surgery most of the time.

**Comment by alexkar598** [comment] 2017-07-28 12:28
Thisis my no infection surgery setup:

Clean OR
Sterile mask
Washed hands
No blood on anybody in the room
No body that's not a doctor in the room
Nitrile gloves(the blue ones)
Clean tools

**Comment by alexkar598** [comment] 2017-07-28 12:29
Also always watch for blood under the surgery table and blood under the damn unclean able body scanner (unless you have the praised medical soap)

**Comment by Onutsio** [comment] 2017-07-29 19:40
Blood occurs under the surgery table during surgery because the patient bleeds onto the ground. Even if you started out clean.

**Comment by matt81093** [comment] 2017-08-02 06:44
@Jountax If IPC's cause infection by 'breathing' then, that itself is an oversight in the code.

**Comment by SamHPurp** [comment] 2018-10-14 11:06
This can be closed really. Been a bunch of PRs to fix this.

**Closed** 2018-10-14 11:10 UTC
Labels: Oversight
