### ISSUE TITLE
You can't remove certain items from inside storage implants

### ISSUE THREAD

**Issue by Sikroth** [ParadiseSS13/Paradise#11326] opened 2019-04-19 05:25 UTC
**Problem Description**:
If you put an object that requires drag&drop to be picked up (for example, paper bins or card decks) inside a storage implant, there's no way to take them out.

**What did you expect to happen**: 
You should be able to remove any item from storage implants.

**What happened instead**:
Drag&dropping into your character or into your hand slot does nothing. Clicking works for paper bins (you take a paper out), while card decks do nothing at all.

**Why is this bad/What are the consequences:**
It can accidentally cause you to pocket an useless item and lose valuable storage space.

**Steps to reproduce the problem**:
- Implant yourself with traitor's storage implant.
- Get a paper bin or deck of cards
- Place inside storage implant pocket.
- Try to take them out.

**When did the problem start happening**:
No idea. Probably a while ago.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Tested in local testserver just now, though I recall this happening to me about a month or two ago in live server with a deck of cards. I think a chat message along the lines of "you can't reach this" showed at that time, but I didn't see anything testing it today.

EDIT: Fun fact I discovered while testing the next issue. If you use package wrapper on an item that's inside the implant pocket, the package will fall to the floor. So I guess that's one way to un-stuck these items.

**Comment by farie82** [comment] 2022-07-01 20:48
This happens because the `item` override of the `Adjacent` proc uses a recurrence depth of 1. So we have a depth like this:
bin -> bluespace pocket -> storage implant -> mob/user
Since the recurrence depth is 1 it will only go to bluespace pocket and then see that its `loc` ain't the user. Thus it fails

A solution would be to override how Adjacent works for the bluespace pocket

**Comment by Christer2222** [comment] 2022-07-25 06:44
I want to add that this seems to happen in all nested inventories. Tried this with a deck of cards inside a box inside my backpack. The deck could be remove once I took the box out of my backpack, while other items could be removed while nested.

**Comment by Sirryan2002** [comment] 2022-07-28 17:44
Confirmed still an issue, appears to be happening with bells aswell

**Comment by Daylight2** [comment] 2024-06-01 15:52
Tested this again, and it seems fixed as of #24699

**Comment by matttheficus** [comment] 2024-06-01 15:53
Fixed as per above.

**Closed by matttheficus** 2024-06-01 15:53 UTC
Labels: Bug, Good First Issue
