### ISSUE TITLE
Unable to use any keybinds outside of WASD

### ISSUE THREAD

**Issue by Contrabang** [ParadiseSS13/Paradise#18617] opened 2022-07-28 08:02 UTC
**Issue Description**:

Unable to use any keybinds outside of WASD (T for say, X for swap hands, etc)

**What did you expect to happen**: 

To be able to properly speak or swap hands

**What happened instead**:

Pressing T or X does nothing

**Why is this bad/What are the consequences**:

you cant play the game really

**Steps to reproduce the problem**:

It occurs randomly... I dont know what causes it but the only way to fix it is to reboot your client

**When did the problem start happening**:

After Hotkeys got merged, but has only been happening recently in the past 2 days

**Extra information**:

**Comment by Miraviel** [comment] 2022-07-28 08:17
I noticed it happening very often when I am interfacing with tgui. While doing RND or chemistry, I often lose my hotkeys.

This is a wild guess but I think #18537 causes this, as it started happening after it got merged

**Comment by hal9000PR** [comment] 2022-07-28 12:03
![image](https://user-images.githubusercontent.com/69320440/181500300-1b1218e7-5908-43f5-952d-0434b310fc6c.png)
I opened and closed TGUI menus for ages, spamming them, checking if other macros worked. they all did. can you give any extra info?

**Comment by hal9000PR** [comment] 2022-07-28 13:09
bug is caused by alt tabbing while having a TGUI window focused. this leaves the `alt` key as "pressed" which breaks your macros

**Closed** 2022-07-31 20:50 UTC
Labels: Bug
