### ISSUE TITLE
Tiles in HoP line are wrong.

### ISSUE THREAD

**Issue by Birdtalon** [ParadiseSS13/Paradise#9798] opened 2018-10-09 22:09 UTC
![dreamseeker_2018-10-09_23-08-17](https://user-images.githubusercontent.com/25027759/46701640-4e50ce00-cc18-11e8-8d5e-064de1b19a36.png)

Arrows are pointing the wrong ways.

**Comment by SamHPurp** [comment] 2018-10-09 22:15
These are mapped correctly, somethings going on during new/initialize

**Comment by SamHPurp** [comment] 2018-10-21 14:13
Duplicate of #9715

**Closed** 2018-10-21 20:31 UTC
Labels: Map Issue
