### ISSUE TITLE
Organ manipulation on eyes does not work

### ISSUE THREAD

**Issue by uraniummeltdown** [ParadiseSS13/Paradise#5542] opened 2016-08-24 15:30 UTC
**Problem Description**:
Organ manipulation surgery on eyes stops working after the preparation phase
**What did you expect to happen**: 
the scalpel makes an incision

**What happened instead**:
Scalpel does not work at all

**Why is this bad/What are the consequences:**
Cannot do any implants like welding shield, xray, etc.

**Steps to reproduce the problem**:
Scalpel in hand, target the eyes and do organ manipulation

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Tried this two different rounds, same outcome

**Comment by TheDZD** [comment] 2016-08-24 15:38
@Crazylemon64

**Comment by Crazylemon64** [comment] 2016-08-24 17:41
I'm not able to reproduce this. Could you provide any more information about your target, or other information about your circumstance?

**Comment by Lady-Luck** [comment] 2016-08-24 18:30
@uraniummeltdown

You need to be in help intent the entire time.

**Comment by Fox-McCloud** [comment] 2016-08-25 01:01
@Crazylemon64 

We haven't patched since your fixes went in, so I'm going to close this, for now; it's probably fixed, but just not on live, yet.

**Closed by Fox-McCloud** 2016-08-25 01:01 UTC
