### ISSUE TITLE
Ventilation pipes bug.

### ISSUE THREAD

**Issue by Wolfsyndrome** [ParadiseSS13/Paradise#8666] opened 2018-02-09 11:54 UTC
**Problem Description**:
There's a bug with the ventilation pipes leading into/out of the Brig, depending on which side you go INTO the pipes as a drone.

**What did you expect to happen**: 
I expected the pipes to stay visible on the 'other' side, meaning on which side you DIDN'T go into the ventilation pipes. 

**What happened instead**:
The pipes on the 'other side' disappear, making it very difficult to navigate them. 

**Why is this bad/What are the consequences:**
Very difficult to get around!

**Steps to reproduce the problem**:
As a drone, enter the vent pipes close to the brig (not IN the brig) and just approach the Brig. Similarly, enter the vents in the Brig, and attempt to leave. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
No related stuff except the video I recorded; 
https://youtu.be/bx-2ZO_V658

**Comment by Citinited** [comment] 2018-02-09 13:34
Duplicate of #7389

**Comment by Wolfsyndrome** [comment] 2018-02-09 13:43
You are indeed correct! That post was made almost an entire year ago though, if that counts for anything.

**Comment by Citinited** [comment] 2018-02-09 13:58
I mean, it's usually better to post on the issue, but don't worry about it :P

**Comment by taukausanake** [comment] 2018-02-10 05:20
Let's just use these as reminders that there is an issue still. This might be fixed with #8469 hopefully

**Comment by IK3I** [comment] 2018-02-10 07:04
there's no code change to ventcrawl in that pr unfortunately, I guess I can add it to the list of things to look into after I finish with my current projects.

**Comment by taukausanake** [comment] 2018-02-10 07:11
Oh yeah, I see why. And the pipe refactor isn't going to change it much.
![image](https://user-images.githubusercontent.com/1978025/36059462-fa68bf96-0dfe-11e8-8dad-ffb31c83065b.png)
This way it's a completely separate pipe net due to being capped off on the other end.

**Comment by FalseIncarnate** [comment] 2018-02-10 07:43
The image that taukausanake posted is exactly responsible, for what you are experiencing, and this is not a bug. This is simply how switching between a supply and generic pipe network works, and that section was specifically designed like that on purpose.

Consider it a limitation of the ventcrawling system that can't really be fixed without changing how the system fundamentally handles displaying things (aka, a rewrite of pretty much the whole deal).

**Comment by DesolateG** [comment] 2018-02-14 11:06
Two separate pipe nets. What ends up happening is you can only view the brig pipes while in them, and only view the rest of the station while in those.

It is pesky though, as you can't see the path to take to get in and out of brig pipes as the others are invisible till you're in them.

**Comment by Citinited** [comment] 2018-02-14 17:34
A potential fix would be to refresh the pipenet every `Life()` cycle e.g.
```
if(pipenet != original_pipenet)
    refreshpipenet()
```
Not sure how complicated that would be though. Probably not too difficult?

**Comment by Crazylemon64** [comment] 2018-08-28 02:45
Duplicate of #7389

**Closed by Crazylemon64** 2018-08-28 02:45 UTC
Labels: Duplicate
