### ISSUE TITLE
Borg brain "dies" when a mining borg goes into an ashstorm. 

### ISSUE THREAD

**Issue by Rexdyer1** [ParadiseSS13/Paradise#17042] opened 2021-11-06 09:31 UTC
**Issue Description**:A borg brain "died" inside a borg. that borg being me. the borg was still alive and able to move around but the brain itself is noted as being dead. this became apparent when the borg body was deconstructed and the brain that came out caused me to ghost. Then another person signed up for that brain and was immediately ghosted by the brain

because it causes an error that repeatedly spawns in borg ghosts and sends them back

**What did you expect to happen**: To be deconstructed from a borg and be a living robo brain

Because it can cause issues with gameplay and cause coding errors

**What happened instead**:The borg brain was lifeless upon borg deconstruction. all future ghost borg roles were destroyed the moment they were selected

**Why is this bad/What are the consequences**:it causes a bug with the borg code and can make a part of the game unusable.

**Steps to reproduce the problem**:Go out as a mining borg during an ash storm, go back to the station after the borg robo brain death message, get deconstructed, try to reapply for ghost role

**When did the problem start happening**:the moment I was in the ash storm as a borg

**Extra information**:thats about it.

**Comment by chafla** [comment] 2021-11-08 03:40
Pretty sure this is a duplicate of #13926

**Closed** 2021-11-12 12:36 UTC
