### ISSUE TITLE
Visions of plants in hydroponics trays (plant images will not leave trays)

### ISSUE THREAD

**Issue by Tango-Mike** [ParadiseSS13/Paradise#23137] opened 2023-11-02 23:23 UTC
**Issue Description**:
Plants that have been grown in hydroponics appear to still be in tray even after harvesting or uprooting. If a new plant is placed into the tray, it stacks its images overlapping images, always starting with the last plant to be planted. This image overlapping also applies with the plant in its different grow cycles. So I'll see ever cycle of a plant in the same tray at once (after its grown up). Leaving and rejoining server does not fix this issue. 

**What did you expect to happen**: 
That the plant images would coincide with their different states and go away once harvested, died or uprooted.

**What happened instead**:
Any images of the plants found in the trays remain despite needed to be replaced in accordance with their status.

**Why is this bad/What are the consequences**:
Visually its a mess and and it makes it a lot harder to determine what I've planted and which trays are actually empty.

**Steps to reproduce the problem**:
In this case...join the server at round start. The problem was immediate once me and my fellow botanist started planting. He didn't seem to notice the problem, however.

**When did the problem start happening**:
Round start.

**Comment by DGamerL** [comment] 2023-11-02 23:31
Could you add some images of it happening?

**Comment by Tango-Mike** [comment] 2023-11-02 23:39
I hope this is adequate. 
![dreamseeker_aEToiFPczD](https://github.com/ParadiseSS13/Paradise/assets/149736719/85cf1a7e-fe42-47a5-8382-db7d3e73b485)

**Comment by Tango-Mike** [comment] 2023-11-02 23:40
Ah, I forgot to mention the same issue is apply to the jug of robust I had on me. Sadly being a ghost makes retrieving it from the pile of lumber...difficult.

**Comment by DGamerL** [comment] 2023-11-03 01:01
Oh that is quite bad, I agree. This might be related to some other issues (but most likely not). Thanks for adding the pictures!

**Comment by DGamerL** [comment] 2023-11-04 02:19
With more information, a lof ot these issues seem to be the cause of the server running on an outdated version of Byond, which will be fixed on monday! Thanks for reporting!

**Comment by farie82** [comment] 2023-11-07 10:15
Fixed in #23186

**Closed** 2023-11-07 10:14 UTC
Labels: Bug, BYOND Issue
