### ISSUE TITLE
Robots (drones/borgs) cannot replace glass/reinforced glass floors

### ISSUE THREAD

**Issue by red031000** [ParadiseSS13/Paradise#17366] opened 2022-01-24 00:34 UTC
**Issue Description**:
Robots (drones/borgs) cannot replace glass/reinforced glass floors

**What did you expect to happen**: 
Crowbarring the reinforced floor with metal in one of the other two slots would replace the floor as it would for an organic mob

**What happened instead**:
An error message of `You also need to hold two sheets of metal to dismantle the reinforced glass floor!` is displayed instead, and no matter the combination of items in hands, the floor cannot be replaced

**Why is this bad/What are the consequences**:
Accidental glass floor placements cannot be undone

**Steps to reproduce the problem**:
> be drone/borg
> replace floor with a glass or reinforced glass floor
> try to dismatle

**Extra information**:

**Comment by SteelSlayer** [comment] 2022-01-28 01:34
Duplicate of #17286. Although this issue mentions borgs.

**Closed** 2022-02-18 17:14 UTC
