### ISSUE TITLE
Syndicate collaborators can the assassination target of the person they are collaborating with

### ISSUE THREAD

**Issue by NotSchwann** [ParadiseSS13/Paradise#10468] opened 2018-12-17 09:07 UTC
**Problem Description**:
Rarely collaborators can be the assassination target for the agent they are working with.

**What did you expect to happen**: 
I expected to collaborate and maybe be thrown in the brig for producing very illegal equipment.

**What happened instead**:
I was brutally murdered in xenobiology by the agent I was assigned to.

**Why is this bad/What are the consequences:**
Doesn't really fit with the concept of the collaborator. Why would I work with an agent when they might end up turning around and immediately killing me with the very scary gun I just gave them?

**Steps to reproduce the problem**:
1). Become a collaborator

2). Be extremely unlucky

**When did the problem start happening**:
Shift start.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Traitor. Nothing out of the ordinary aside from my own horrible death.

**Comment by Agameofscones** [comment] 2018-12-17 09:20
Traitors can also be assigned to each other as potential collaborators as well as targets.

Source: Went to collaborate as a traitor, got pizza bombed by traitor collaborator. kthnxbye

**Comment by variableundefined** [comment] 2018-12-17 10:35
Not a bug

**Closed by variableundefined** 2018-12-17 10:35 UTC
Labels: Not a Bug
