### ISSUE TITLE
Pinpointer/AI camera tracking lagspikes while scrolling.

### ISSUE THREAD

**Issue by ATP-Engineer** [ParadiseSS13/Paradise#20383] opened 2023-02-07 19:10 UTC
**Issue Description**:

When scrolling through the pinpointers available targets, the game significantly lags for a short period of time, unsure if its just oldcode being shit, or because its something to do with the scrolling itself.

I also have noticed this applied to the AI cameras when you use the tracking system.

**What did you expect to happen**: 

Selecting a person from a simple scrolling menu not creating the same force of lag of 'woody got wood' chatspam, allowing for a smooth scroll up and down the items selection.

**What happened instead**:

Creating a very brief but horrible clientside lagspike while scrolling through the selection, the lag ceasing when you stop.

**Why is this bad/What are the consequences**:

Pinpointers causing short lagspikes can doom antags if they're using them on the fly, and its a general pain in the ass for any other medical roles using them, such as paramedic.

It also makes tracking people as AI hard seeing as it tracks people if they're on cameras regardless of sensors, seeing as there's more, its even laggier.

(unsure about this but it might also cause time dilation if i'm correct? No idea how that works)

**Steps to reproduce the problem**:

Buy a pinpointer from the medivend, open it when 15+ people are on max sensors, scroll through it.

Play AI, open tracking camera, scroll.

**When did the problem start happening**:

I assume it's always been around, but there's no open issues to document it so someone makes a fancy radial UI pr to update it.

**Extra information**:

N/A

**Comment by AffectedArc07** [comment] 2023-02-07 19:11
>  so someone makes a fancy radial UI pr to update it.

This will never be a radial menu. They are bad enough with 7 things, let alone 37

**Comment by DGamerL** [comment] 2023-10-21 00:59
Duplicate of #6898 , any large list to scroll through will lag your client out considerably.

**Closed by DGamerL** 2023-10-21 00:59 UTC
Labels: Cannot/Will Not Fix, BYOND Issue
