### ISSUE TITLE
Virus Culture Bottles have no sprite

### ISSUE THREAD

**Issue by stutwoby** [ParadiseSS13/Paradise#5712] opened 2016-09-25 22:30 UTC
**Problem Description**:
When creating a virus Culture Bottle in the Pandemic 2200 there bottles have no sprite (can still be identified on right click)

**What did you expect to happen**: 
I expected to see a sprite of the usual chemistry bottle with the blood sample.

**What happened instead**:
Nothing appeared until inspection

**Why is this bad/What are the consequences:**
Can't pinpoint the bottle without inspecting.

**Steps to reproduce the problem**:
In my test I used the rhinovirus and tried to create a virus culture bottle, it gets renamed flu.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Round start so nothing out of the ordinary happend. Can still be loaded into the virus smart storage and unloaded, but still no sprite.

**Comment by Codingale** [comment] 2016-09-26 01:27
Duplicate of #5702 (Which I don't think was fixed in [ffc0083](https://github.com/ParadiseSS13/Paradise/pull/5691/commits/ffc0083098fd2f93e884e6c8747423547a13fdc9))

I'll test in the morning to see if it's just not live, or if it isn't fixed.

**Closed** 2016-10-04 12:42 UTC
