### ISSUE TITLE
Upgrading turbine with good science parts break its

### ISSUE THREAD

**Issue by GelatinousGlob** [ParadiseSS13/Paradise#3671] opened 2016-02-22 04:58 UTC
The atmospherics turbine worked great until I upgraded it with the BRPD from science with top level parts Manipulators and capacitors. It briefly jumped from 100K watts to 400K watts for about a tick and then went to zero. Turbine stopped working after that.

**Comment by FalseIncarnate** [comment] 2016-02-22 06:18
Duplicate of your own report #2746

**Closed** 2016-02-22 06:32 UTC
