### ISSUE TITLE
Changeling "Augmented Eyesight" feature has a weird lighting effect

### ISSUE THREAD

**Issue by Chicken12341** [ParadiseSS13/Paradise#1375] opened 2015-06-23 23:36 UTC
With Augmented Eyesight on:
http://gyazo.com/7e799966ad04f34ab8dacdc8ef87a8f9

With Augmented Eyesight off:
http://gyazo.com/6faa2fbfa11a094f3dd40fc9d619d19e

**Comment by PJB3005** [comment] 2015-06-26 08:51
Goddamnit.

It's caused by this: https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/carbon/human/life.dm#L1152

Fixing this will require unfucking of Life() at the least

**Comment by tigercat2000** [comment] 2015-09-28 03:14
This should be fixed by #2146 when it's merged

**Closed** 2015-09-29 15:44 UTC
Labels: Bug
