### ISSUE TITLE
GPSes cannot be turned on or off

### ISSUE THREAD

**Issue by BiancaWilkson** [ParadiseSS13/Paradise#21850] opened 2023-07-28 06:15 UTC
**Issue Description**:

The TGUI switch for turning GPSes on and off does not work, thus cannot be turned back on if EMPed

**What did you expect to happen**: 

The button to swap the on/off state

**What happened instead**:

It did nothing instead

**Why is this bad/What are the consequences**:

Button should generally work

**Steps to reproduce the problem**:

Grab GPS, attempt to turn it off through the TGUI menu

**When did the problem start happening**:

Unsure, within the last year. It could possibly have been the modsuit TM but I'm not certain about that either.

**Extra information**:

Possibly a TM issue

**Comment by CinnamonSnowball** [comment] 2023-07-28 08:12
Duplicate of #21511

**Comment by Contrabang** [comment] 2023-07-30 23:53
I'd say they're not exact duplicate of #21511, as that one seems to be relating more to stationary GPSs, while this one specifically mentions the EMPing

**Comment by tipoima** [comment] 2023-07-31 04:05
> I'd say they're not exact duplicate of #21511, as that one seems to be relating more to stationary GPSs, while this one specifically mentions the EMPing

That wasn't my intention, but since that report is pretty much buried and dead, might as well keep this one

**Comment by warriorstar-orion** [comment] 2023-08-08 16:10
Qwerty confirmed this and #21511 were due to the modsuit TM and have been addressed.

**Closed by warriorstar-orion** 2023-08-08 16:10 UTC
Labels: Bug
