### ISSUE TITLE
viral injector is no longer stealthy

### ISSUE THREAD

**Issue by DoctorDrugs** [ParadiseSS13/Paradise#17384] opened 2022-02-04 03:53 UTC
**Issue Description**:
The stealthily antag virus injector/pipette isn't so stealthy anymore

**What did you expect to happen**: 
to be stealthy without a big warning text pop up

**What happened instead**:
BIG RED TEXT WARNING

**Why is this bad/What are the consequences**:
This is not what the tool tip states for it being stealthy and makes it not worth using

**Steps to reproduce the problem**:
locate poor soul to inject without their knowledge, go to inject without them knowing, notice big red warning text, scream internally that it takes a long ass time with warning text.

**When did the problem start happening**:
Unknown when it started exactly

**Extra information**:
https://gyazo.com/b504768e7a0d35d828971c9ce6fe0914 image for reference for the warning message output

**Comment by AffectedArc07** [comment] 2022-02-04 09:13
Duplicate of https://github.com/ParadiseSS13/Paradise/issues/16638

**Closed** 2022-02-04 09:13 UTC
