### ISSUE TITLE
pAI device racist to Kitten.pAI

### ISSUE THREAD

**Issue by Trubuss** [ParadiseSS13/Paradise#5036] opened 2016-07-13 22:52 UTC
**Problem Description**:
Crew members get notification that there is a pAI available, but the pAI device shows nothing.

**What did you expect to happen**: 
You should be able to download Kitten.AI

**What happened instead**:
pAI device refuses to have Kitten.pAI (blank screen, shows nothing)

**Why is this bad/What are the consequences:**
Everyone needs Kitten.pAI, even you Admins.

**Steps to reproduce the problem**:
Saved pAI file, Loaded pAI file, created a new pAI file and submitted with no success

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
It's been proven that crew depression gets serve without Kitten.pAI in there life.

**Comment by Plotron** [comment] 2016-07-13 23:17
It's confusing when it happens, yes.

**Comment by Spacemanspark** [comment] 2016-07-13 23:52
Ya, sometimes people can't download Spark.
Then they die.

**Comment by Trubuss** [comment] 2016-07-14 15:48
Kitten most important though. :P

**Comment by Spacemanspark** [comment] 2016-07-14 16:28
That's not how you spell "Spark"

**Comment by Trubuss** [comment] 2016-07-14 17:54
No, no, the word was Kitten, as in how many people love Kitten.pAI. >:3

**Comment by Spacemanspark** [comment] 2016-07-14 19:22
That's not how you spell "Spark 5.5m is amazing"

**Comment by KasparoVy** [comment] 2016-07-15 05:03
edgy memes

**Comment by Trubuss** [comment] 2016-07-15 20:10
Kitten.pAI owns Spark.

**Comment by Davdichan** [comment] 2016-07-16 00:00
After reading these comments I'm not sure how the original issue is even a problem.

**Comment by Trubuss** [comment] 2016-07-16 00:05
Then you didn't read it, Davdichan.

**Comment by Spacemanspark** [comment] 2016-07-16 00:23
:^)

**Comment by counterfeitguise** [comment] 2016-07-21 13:13
Ignoring the comments, it's an actual problem. pAI grabbing is a fickle mistress.

**Comment by TheDZD** [comment] 2016-08-19 22:04
Likely fixed by #5496, since it was saving that was broken.

**Comment by TheDZD** [comment] 2016-08-19 22:06
Nevermind, apparently not.

**Comment by alexpkeaton** [comment] 2017-01-07 17:53
This is an unexpectedly hilarious issue thread.

**Comment by Spacemanspark** [comment] 2017-01-07 22:03
Spark is still the best pAI

**Comment by Trubuss** [comment] 2017-01-07 22:37
Clearly, it is not Spark, but Kitten being best pAI.

**Comment by Davdichan** [comment] 2017-01-09 15:06
The best pAI is the one bound to the recycler.

**Comment by Spacemanspark** [comment] 2017-01-09 17:07
I'll bind you to the recycler.

**Comment by Davdichan** [comment] 2017-01-09 17:24
Kinky

**Comment by Crazylemon64** [comment] 2017-01-09 22:05
Is this actually a thing

The steps provided are insufficient to reproduce it

**Comment by Spacemanspark** [comment] 2017-01-09 22:46
I think it's been fixed honestly.

**Comment by Crazylemon64** [comment] 2017-01-09 22:50
Yell if this comes up again, preferably with more details/a ping to join the server, so I can inspect this closer than what this issue tells me.

**Closed by Crazylemon64** 2017-01-09 22:50 UTC
Labels: Bug
