### ISSUE TITLE
Slime People Racial Abilities reappearing as Changeling

### ISSUE THREAD

**Issue by stankydooky9000** [ParadiseSS13/Paradise#16130] opened 2021-06-04 17:30 UTC
**Issue Description**:

As a changeling when you transform from a slime person, to any other race, then back to slime person, you get copies of your abilities flooding the top bar. This will persist throughout the entire round.

**What did you expect to happen**: 

Clutters the top of the screen and makes it harder to play/

**What happened instead**:

I didn't expect to see 2 of the same ability to be stuck there the whole round.

**Why is this bad/What are the consequences**:

Makes it harder to play as a changeling because they have no spell menu tab and it's just kind of annoying to have half of your screen blotted out by useless buttons.

**Steps to reproduce the problem**:

1. Be slime person changeling
2. Transform into anyone else (human for a fact works every time as well as vulp)
3. Transform back into a Slime Person
4. Your top bar should now have 2 sets of Regrow Limbs and Toggle Recolor

**When did the problem start happening**:

This started happening on 4/6/21

**Extra information**:

**Comment by SteelSlayer** [comment] 2021-06-04 17:33
Duplicate of #15913

**Comment by Sirryan2002** [comment] 2021-06-04 17:59
being fixed in #15936

**Closed** 2021-07-08 21:34 UTC
