### ISSUE TITLE
pAI PDA Messaging able to receive but not send messages.

### ISSUE THREAD

**Issue by Dinarzad** [ParadiseSS13/Paradise#4053] opened 2016-03-31 11:58 UTC
**Problem Description**:
What is the problem?
Tried to send several PDA messages to various crew all shift, and so far it seemed like they all just kinda.... vanished into the void. Did a test with my Master's PDA while on their person and sure enough, no PDA messages received from it.

**What did you expect to happen**: 
Why do you think this is a bug?
Because PDA messaging should send a PDA message.

**What happened instead**:
How is what happened different from what you expected?
It didn't send a PDA message. I could RECEIVE them, but not SEND/REPLY to them.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Because the entire Digital Messenger suite is sorta pointless if it doesn't work, and it's one of the few major functions a pAI can do. 

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
I tried to send a PDA message, via the Digital MEssenger Suite of the pAI software, and it was not sending them, they were just... gobbled up. Several test runs proved this to be consistantly the case, entirely non-functional.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
I tried testing it in several situations. Both folded, unfolded, on person, off person, messaging my master as well as other people.
In every instance, total silence from their PDA's.

**Comment by Tastyfish** [comment] 2016-03-31 19:50
Could not reproduce with latest code, was likely fixed in https://github.com/ParadiseSS13/Paradise/pull/4040 when I cleaned up some of the pAI PDA code.

**Closed** 2016-03-31 20:34 UTC
Labels: Cannot Reproduce
