### ISSUE TITLE
Runtime in unsorted, 2037.

### ISSUE THREAD

**Issue by lass9030** [ParadiseSS13/Paradise#9786] opened 2018-10-09 14:55 UTC
Runtime in landmarks.dm and unsorted.dm
Full server log attached.
https://pastebin.com/Myg8gibv

EDIT:
This happened later in the same round, might be related.
https://pastebin.com/EbZntBgT

I have tested this, it only seems happens on spacehotel.dmm.

**Comment by Birdtalon** [comment] 2018-10-09 14:57
Runtime in landmarks.dm,279 is a duplicate of #9735

**Comment by Birdtalon** [comment] 2018-10-09 14:57
Duplicate of #9735

**Comment by lass9030** [comment] 2018-10-09 17:13
The issue in unsorted.dm might also be related to #9736.

**Comment by SamHPurp** [comment] 2018-10-10 21:09
These are dupes and can be closed

**Closed** 2018-10-11 11:01 UTC
Labels: Runtime
