### ISSUE TITLE
Sleeping Carp Not "Fully" Deflecting Ballistics

### ISSUE THREAD

**Issue by granodd** [ParadiseSS13/Paradise#7517] opened 2017-06-10 04:05 UTC
![image](https://user-images.githubusercontent.com/22057974/26999800-665033a6-4d70-11e7-9be2-bb400f327374.png)

**Problem Description**:
Ballistic projectiles still stick into the body even when deflected with sleeping carp.

**What did you expect to happen**: 
The bullet to be fully and properly deflected, and not still hit.

**What happened instead**:
The bullets are deflected and do not do their proper damage, but they still somehow stick into the person and can jostle around to do damage that way.

**Why is this bad/What are the consequences:**
It seems counter-intuitive that you can deflect ballistic projectiles, yet still have them stick into you. A bit strange to think that the one type of projectile that you'd think carp is meant to deflect (solid projectiles vs lasers of all things) in actuality turns out to be its counter, and I hardly doubt this was intended. It harkens back to the whole "still hit by an object that I caught" ordeal that was recently fixed by TG's move code.

**Steps to reproduce the problem**:
Have sleeping carp, have anyone with a ballistic weapon fire it at you enough times that the RNG sticks a bullet in you as shrapnel rather than outright deflection.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: The only time you could get this sort of thing is during traitor, though I doubt that has anything to do with the functionality of it all.

**Comment by Fox-McCloud** [comment] 2017-06-10 04:07
Yeah, it's a big problem.

**Comment by Twinmold93** [comment] 2017-06-14 21:02
I think, simply put, you fire buckshot at someone close enough they won't be able to deflect all pellets. The code does need some clean and fixing, but I like that part.

**Comment by Fox-McCloud** [comment] 2017-06-15 10:58
It's a bug, plain and simple; there's not an "IC" explanation for this, and that's not how shrapnel works, anyway.

**Comment by Twinmold93** [comment] 2017-06-23 20:49
Except the cause of shrapnel is pellets and if you're firing 5 or 6 pellets into someone simutaniously at really close range, I don't care how fast they move, something is going to hit them. The ONLY thing is the pellets you DO block shouldn't be sticking, which is a problem. However, not every pellet in a case like this should be blockable. Hence code needs cleaned and fixed.

**Comment by Fox-McCloud** [comment] 2017-06-24 05:56
each pellet is a bullet projectile, all projectiles are reflected. This isn't up for debate: bullets causing embedding or any other effects when the project doesn't connect ***Is a bug***.

**Comment by Twinmold93** [comment] 2017-06-26 05:23
I'm not saying something being deflected should embed: if you deflect it, it should not embed. I just find it unrealistic to have 10 bullets from different people all be deflected in a split second.

**Comment by scrubmcnoob** [comment] 2017-09-27 03:41
This can be closed. @tiger

**Comment by tigercat2000** [comment] 2017-09-27 03:41
Fixed by #7480

**Closed by tigercat2000** 2017-09-27 03:41 UTC
Labels: Bug
