### ISSUE TITLE
Arm malfunction inside spacepod loses item.

### ISSUE THREAD

**Issue by GelatinousGlob** [ParadiseSS13/Paradise#4196] opened 2016-04-14 06:26 UTC
Had a suspicious toolbox in the pod with me, slightly damaged robotic arm randomly shorts out dropping the item inside the pod making it irretrievable.

**Comment by tigercat2000** [comment] 2016-04-14 06:39
this is more of a problem of "spacepods and mechs have no way to get items out of their contents"

**Comment by Fox-McCloud** [comment] 2016-04-14 06:42
>this is more of a problem of "spacepods and mechs have no way to get items out of their contents"

Along with a billion other things.

**Comment by GelatinousGlob** [comment] 2016-04-14 06:48
I figured, but thought I would post it anyways since i was already here.

**Comment by Fox-McCloud** [comment] 2016-04-14 07:08
more or less a duplicate of: https://github.com/ParadiseSS13/Paradise/issues/3260

**Closed by Fox-McCloud** 2016-04-14 07:08 UTC
