### ISSUE TITLE
weird pressure in heiro arena

### ISSUE THREAD

**Issue by Magentaformula0** [ParadiseSS13/Paradise#12602] opened 2019-10-17 00:08 UTC
**Issue Description**: about half of the arena is pressurized like it is space now for no reason. 

Thats not how it used to be and without a hardsuit you take a decent amount of damage from it. 

**What did you expect to happen**: 

Not taking damage constantly by walking into an area of tiles. 

**What happened instead**:

Now having that happen would be nice. 

**Why is this bad/What are the consequences**:

You take damage. You shouldnt need a hardsuit arbitrarily for half of the heiro arena. 

**Steps to reproduce the problem**:

Walk into the area in the middle of the heiro arena without a hardsuit. you should be taking damage.

**When did the problem start happening**:

I think since the last change merge a couple of days ago. 

**Extra information**:

**Comment by TDSSS** [comment] 2019-10-17 00:09
duplicate of #12597

**Closed** 2019-10-25 21:31 UTC
