### ISSUE TITLE
Couldnt convert a mindshieldless crew with two cultists.

### ISSUE THREAD

**Issue by Alantodne** [ParadiseSS13/Paradise#14150] opened 2020-08-26 07:04 UTC
**Issue Description**:
Two cultists stood next to a binding rune with a mindshieldless crew and when trying to activate the rune, it said it needed two invokers.

**What did you expect to happen**: 
I expected to convert the crew to be cult.

**What happened instead**:
The rune pulsed saying it failed and claimed that it needed a 2nd invoker, even though we were both within range of the rune to be invokers.

**Why is this bad/What are the consequences**:
If toko hadnt played along it could have gotten cult spotted.

**Steps to reproduce the problem**:
Races involved. Invokers Shawna Lupix. Vulpkanin. Meek, a Grey. 
Victim. Tokorizo, Vox.
We had placed Toko onto the binding rune, which was under a table. Me and Meek stood next to it, and when pressed the rune it complained of us not having enough invokers. 
If place matters the rune was under the monkey box in xenobio(same spot where it spawns.) and me and meek were on the chairs left of it.

**When did the problem start happening**:
The cult round that happened at 12:15AM EST 8/26/2020 was when I noticed it.

**Extra information**:
We later tried to combined souls summon toko and it gave similar results of. Grey and Vulpkin not being able to summon toko.

**Comment by datlo** [comment] 2020-08-26 07:44
This is most likely caused by this piece of code : 
```
if(req_cultists > 1 || allow_excess_invokers)
		for(var/mob/living/L in range(1, src))
			if(iscultist(L))
				if(L == user)
					continue
				if(ishuman(L))
					var/mob/living/carbon/human/H = L
					if(!H.can_speak())
						continue
				if(L.stat)
					continue
				invokers |= L
```
https://github.com/ParadiseSS13/Paradise/blob/1cdf827efc85462e91f714b4cc2ffbdd393ce204/code/game/gamemodes/cult/runes.dm#L120
The (H.can_speak) check is probably some leftover code as this is only checked for additional invokers and I dont think any other cult magic requires being able to speak, not even cult comms. It has been removed from blood cult, fixing the issue once that's merged.

**Comment by datlo** [comment] 2020-08-26 15:46
Confirmed by alantodne that one of the cultist was mute.

**Closed** 2020-11-07 01:41 UTC
