### ISSUE TITLE
Human skin tone

### ISSUE THREAD

**Issue by BorisLemons** [ParadiseSS13/Paradise#2333] opened 2015-10-09 10:25 UTC
Human skin tone seems to be borked, regardless of the value set up in character set up, it will appear as default. This is independent of slot used.

**Comment by tigercat2000** [comment] 2015-10-09 14:02
Hm. This was probably fixed by #2323, try again after server patches.

**Comment by BorisLemons** [comment] 2015-10-11 08:52
The bug has not been resolved.

**Comment by tigercat2000** [comment] 2015-10-11 17:10
Can't reproduce locally as of commit c2ffc3196320e

We probably still haven't patched the main server.

**Comment by Fox-McCloud** [comment] 2015-12-28 04:23
likely fixed; please re-report if this is an issue.

**Closed by Fox-McCloud** 2015-12-28 04:23 UTC
Labels: Bug
