### ISSUE TITLE
Changelings "Last Resort" bug

### ISSUE THREAD

**Issue by Sixzma** [ParadiseSS13/Paradise#17132] opened 2021-11-18 08:32 UTC
**Issue Description**:
Using the "Last Resort" Changeling ability, after injecting eggs inside a body and hatching, The cling will respawn as a monkey with the option to humanize, After being humanized you can’t access the cling abilities anymore.

**What did you expect to happen**: 
Being able to use changeling abilities.

**What happened instead**:
I was reborn as a regular human, nothing "changeling" like

**Why is this bad/What are the consequences**:
The cling won’t be able to use any of its abilities, screwing their game over. 

**Steps to reproduce the problem**:
1- Be cling
2- Buy Last resort
3- Bite a dead body and die
4- Revive as a monkey
5- Humanize
![Issue 1](https://user-images.githubusercontent.com/94600484/142379248-61c9e3ca-5a9a-484f-8334-522134bc01cc.PNG)
![Issue 2](https://user-images.githubusercontent.com/94600484/142379274-09c49ef0-4478-4d0c-a5be-e7734ea05a91.PNG)

**When did the problem start happening**:
I have no idea.

**Comment by nok-ko** [comment] 2021-11-18 19:16
Bug might be here, or somewhere along the chain of storing a cling's purchased powers in the headslug, and then in the monkey.

https://github.com/ParadiseSS13/Paradise/blob/f0841b36294baccc2c5ac18678bd898defb8583d/code/modules/mob/living/simple_animal/hostile/headslug.dm#L90-L96

The actual “humanize” action doesn't touch the purchased powers in any way other than removing itself from the user when used, so probably not the culprit.

**Comment by nok-ko** [comment] 2021-11-18 19:21
Probably a duplicate of #16437.

**Comment by SteelSlayer** [comment] 2022-06-19 00:53
Fixed this in #17774, but I forgot to write it.

**Closed by SteelSlayer** 2022-06-19 00:53 UTC
