### ISSUE TITLE
Maint drone using UPA to change from supply/scrubber can no longer see what pipe they're in

### ISSUE THREAD

**Issue by iantine** [ParadiseSS13/Paradise#10439] opened 2018-12-11 07:13 UTC
**Problem Description**:
Whilst playing a maintenance drone, if a player enters a Universal Pipe Adapter from a pipe network and leaves through a different pipe network (for this example, let's say the drone enters from a scrubber network and leaves through a supply network), the visual will not update to show the drone's current pipe position as being highlighted.

**What did you expect to happen**: 
I expected the drone's path to be highlighted as it entered the new network.

**What happened instead**:
Upon changing networks via UPA the first time (the UPA I used was the one above atmospherics distro) my screen stopped showing a highlighted pipe network at all. Realising that either an error or an oversight was in effect, I went back to the original network (scrubber) and attempted again, entering from scrubber to supply via UPA. This time, though I was in the supply pipe network, the scrubber network remained highlighted.

**Why is this bad/What are the consequences:**
A drone player can get lost in the pipes, unable to see where they are going.

**Steps to reproduce the problem**:
1. Play as maint drone (unsure if this works with other vent-crawling mobs)
2. Enter either scrubber or supply network.
3. Use a UPA to change paths into another pipe network (supply if scrubber, and vice versa).
4. Observe as your proper pipe path is no longer highlighted on screen.

**When did the problem start happening**:
This problem was noticed 10/December/2018.

**Possibly related stuff**:
Boxstation. Can't recall gametype or if it was relevant. Related image: actual location of the maint drone inside the piping is the red cross.
![maintdrone](https://user-images.githubusercontent.com/26665535/49784119-56400200-fd70-11e8-953e-20eff8b9331b.png)

**Comment by Squirgenheimer** [comment] 2018-12-11 10:05
I suspect this happens to all mobs that can ventcrawl. I've primarily noticed it by going into security's vents as a terror spider.

**Comment by Citinited** [comment] 2018-12-11 11:09
Duplicate of many issues

Please use the search feature next time

**Comment by Citinited** [comment] 2018-12-11 12:55
Duplicate of #7389

**Closed** 2022-07-09 14:07 UTC
Labels: Bug
