### ISSUE TITLE
Hivelord remains replace robotic limbs with organic ones

### ISSUE THREAD

**Issue by DavidRossii** [ParadiseSS13/Paradise#1967] opened 2015-09-06 10:52 UTC
Thought it'd be best for my first post!

When you use hivelord remains to fix up, your robotic limbs are replaced with organic ones upon using.

Unsure if this is intentional or not?

**Comment by TheDZD** [comment] 2015-09-06 15:04
That would be due to the fact that it uses the revive proc, which is also used by admin rejuvenate, and regenerates all of  your limbs.

**Comment by Spacemanspark** [comment] 2015-09-06 16:26
I'd let this remain, honestly.

**Comment by DavidRossii** [comment] 2015-09-06 19:57
Would it regenerate limbs of people who set robotic limbs as a pre-set standard in character setup?

**Comment by M3hillus** [comment] 2015-09-06 20:54
@DavidRossii It does. Confirmed as playing medusa as shaftminer and ganking hivelords for heals, getting hurt later and hurting myself trying to fix my non-existent robolimbs.

**Comment by Taaketa** [comment] 2015-09-07 09:31
Does it bug up limb repair then or does the robo limbs fall off?

**Comment by M3hillus** [comment] 2015-09-07 10:13
it just turns them into non robotic limbs.

**Comment by SpaceTimeNow** [comment] 2015-09-11 09:44
That's kinda funny, maybe just expand on that. Drop the robotic limbs on the floor, let biological ones grow, add some flavor text and call it a feature.

But probably should be fixed for the admin rejuvenate.

**Comment by Fox-McCloud** [comment] 2016-02-21 04:06
this is a large issue with rejuvinate.

**Closed** 2016-07-29 23:08 UTC
Labels: Oversight
