### ISSUE TITLE
Blob Spore Gas Harms Other Spores

### ISSUE THREAD

**Issue by VeteranKyl** [ParadiseSS13/Paradise#12636] opened 2019-10-23 01:30 UTC
**Issue Description**:
Blob spores are harmed by the gas released by killed spores.

**What did you expect to happen**: 
Blob spores should be immune to the gas released by killed spores, especially if they're of the same chemical type.

**What happened instead**:
When a killed spore releases its gas, the gas harms all other blob spores in range.

**Why is this bad/What are the consequences**:
Not only does it not make sense for a blob spore to not be immune to its own chemical, but the harm caused by the spore gas can kill nearby spores, which means less minions to hold off any attacking crew.

**Steps to reproduce the problem**:
1. Play blob.
2. Create a blob factory.
3. Group up the spores that spawn.
4. Kill one of the spores while other spores are in range of the gas.
The surrounding spores will be damaged by the gas.

**When did the problem start happening**:
Unknown.

**Extra information**:
The spore gas may potentially harm blobernaughts. Didn't test it.

**Comment by Denthamos** [comment] 2019-10-23 02:21
Duplicate of https://github.com/ParadiseSS13/Paradise/issues/12129

**Comment by matttheficus** [comment] 2022-06-22 16:31
Duplicate of #12129

**Closed by matttheficus** 2022-06-22 16:31 UTC
Labels: Duplicate
