### ISSUE TITLE
Bugged Gloves/Hand Sprite

### ISSUE THREAD

**Issue by Kepplerx** [ParadiseSS13/Paradise#16467] opened 2021-08-01 17:08 UTC
**Issue Description**:
The clothes menu showed gloves even when I had none, and especially not insulated combat gloves. I did wear the chameleon suit at the time, with the SOO disguise.

**What did you expect to happen**: 
For it not to show any gloves, and especially not when the menu is laid down

**What happened instead**:
Not only did it show I had gloves, the gloves also remained overlayed when the menu was laid down.

**Why is this bad/What are the consequences**:
Potentially being shocked because you thought you had gloves on

**Steps to reproduce the problem**:
Unsure, havent tested it

**When did the problem start happening**:
Unsure, havent seen it before

**Extra information**:
![image](https://user-images.githubusercontent.com/65926304/127779515-a311c095-35f5-46f3-bdec-f8153b3b2f65.png)

**Comment by Spacemanspark** [comment] 2021-08-04 21:53
This tends to happen on very rare occasion if you pick up an item, equip it, drop it and then someone else grabs it and does the same. I don't know why this happens, but opening and closing the equipment menu usually works to fix it at least.

**Comment by SabreML** [comment] 2021-08-11 00:13
This may have been fixed in #16411 (929041d97ccb08cd5bbaa7763a13dc435175d53a), assuming it was caused by the same thing.

**Comment by matttheficus** [comment] 2022-06-21 17:00
Stale. Possibly fixed?

**Closed by matttheficus** 2022-06-21 17:00 UTC
