### ISSUE TITLE
Vampires are unable to use Chameleon Skin gene

### ISSUE THREAD

**Issue by tipoima** [ParadiseSS13/Paradise#17915] opened 2022-06-03 15:22 UTC
**Issue Description**:
Vampires do not become invisible when using Chameleon Skin. (No vampire class has been picked when I encountered the bug).

**What did you expect to happen**: 
For the vampire to become invisible.

**What happened instead**:
Gene had no effect beyond the "You feel like you're fading into your surroundings" message. 

**Why is this bad/What are the consequences**:
Frankly speaking, it's not a common issue, but it's likely something that will make a vampire geneticist sad.

**Steps to reproduce the problem**:
Be a vampire. Get the gene. See yourself still not being invisible.

**When did the problem start happening**:
Presumably it's a leftover from the old vampires, who had Darkness Cloak (and which is incompatible with Chameleon), which is now restricted to Umbrae. 

**Extra information**:

**Comment by SteelSlayer** [comment] 2022-06-19 06:21
The issue is here on line 285. This proc gets called every every couple seconds and set's the vampires visibility back to maximum:

![Code_RB7EGVjrIP](https://user-images.githubusercontent.com/42044220/174468536-3b85f944-18d1-4b59-b533-c0575cb57613.png)

@hal9000PR Any ideas on the proper way this should be fixed?

**Closed** 2024-09-26 18:10 UTC
Labels: Bug
