### ISSUE TITLE
perma blind from cloning

### ISSUE THREAD

**Issue by restedwaves** [ParadiseSS13/Paradise#18197] opened 2022-07-03 15:45 UTC
**Issue Description**:

after cloning the player can be permanently blinded

**What did you expect to happen**: 

the blindness wears off or can at least be fixed

**What happened instead**:

forever blind, unable to see the horrors before me

**Why is this bad/What are the consequences**:

players cant play

**Steps to reproduce the problem**:

signed up to be revived via cloning, the cloner was out of material so it took awhile, after being revived i was permanently blind, occuline did not help nor did replacing my eyes with cybernetic ones in the end an admin fixed it

**When did the problem start happening**:

7/3/2022 to my knowledge

**Extra information**:

round id 31920 if that helps

**Comment by Inadvizable** [comment] 2022-07-03 16:53
Could have been caused by a random blindness mutation, which is fixed by mutadone. Do you remember whether you were given that?

**Comment by restedwaves** [comment] 2022-07-03 21:45
no but when i asked the admin they claimed it was a bug

**Comment by Spaghetti-bit** [comment] 2024-07-01 09:07
https://github.com/ParadiseSS13/Paradise/pull/25127, fixed. Hasn’t been an issue since the cloning pod rework.

**Closed by Spaghetti-bit** 2024-07-01 09:07 UTC
Labels: Bug
