### ISSUE TITLE
SMES units do not show their load propperly

### ISSUE THREAD

**Issue by Bram961** [ParadiseSS13/Paradise#7463] opened 2017-06-04 17:24 UTC
**Problem Description**:
SMES units will always show their output level in the output load bar even if the load is supposed to be lower

**Why is this bad/What are the consequences:**
Engineers cannot easily troubleshoot their SMES unit's.

**Steps to reproduce the problem**:
Open up the menu of any SMES unit that has an output load lower than the current output level

**Comment by SamHPurp** [comment] 2017-06-04 17:34
Can you provide images of the concern? I'm pretty sure the SMES's bar shows the current max output you are allowing, not actual load... which isn't an issue, changing this would be more 'feature'.

**Comment by Taaketa** [comment] 2017-06-04 21:36
I think the confusion here is that on Paradise SMES show max power output. But other servers show actual power output to the grid.

This was a deliberate change if I recall correctly. To give grid status consoles more meaning and engineer's PDAs.

**Comment by Anticept** [comment] 2017-06-04 23:17
Yes, on paradise, SMES always show total output. On other servers, they show loads. This is currently by design, something I hope to change with a new powergrid design I am working on.

**Comment by Bram961** [comment] 2017-06-10 15:08
@SamHPurp  
@Taaketa 
@Anticept 
If it is by design than this is my mistake however I am sure that the lower bar on the SMES units showed the load some time ago, Grid status consoles and Engineers PDA's still have a lot of meaning in determining where cables are cut.

Whether or not by design the issue still stands, the bar says "Output load" but doesn't display the Output load but the max power output (which is also displayed by another bar above it)

**Comment by SabreML** [comment] 2021-04-12 15:35
Presumably fixed by #14058, since that reworked the entire UI.

**Closed** 2021-07-08 21:34 UTC
Labels: User Interface
