### ISSUE TITLE
Medbay airalarm placement

### ISSUE THREAD

**Issue by Allfd** [ParadiseSS13/Paradise#9059] opened 2018-05-23 01:11 UTC
**Problem Description**:
Medbay air alarm is blocked during emergencies.

**What did you expect to happen**: 
The air alarm to receive updated information.

**What happened instead**:
If the fire shutters close, the air alarm is cut off from receiving new air samples.

**Why is this bad/What are the consequences:**
Unpredictable atmospherics behavior.

**Steps to reproduce the problem**:
Pull the fire alarm.

![image](https://user-images.githubusercontent.com/8165455/40398198-b75df94a-5e04-11e8-95dc-9ffb9f756aa0.png)

**Comment by FreeStylaLT** [comment] 2018-05-23 01:18
They're for Engi+ only, this enforces that properly.
![img](https://cdn.discordapp.com/emojis/422715225662554113.png?v=1)

**Comment by Crazylemon64** [comment] 2018-08-28 02:34
duplicate of #8823

**Closed by Crazylemon64** 2018-08-28 02:34 UTC
Labels: Boxstation, Map Issue
