### ISSUE TITLE
Plasmaman Wizards are getting rooked from the start.

### ISSUE THREAD

**Issue by KingPhilipIII** [ParadiseSS13/Paradise#8679] opened 2018-02-13 01:20 UTC
**Problem Description**:
Since plasmamemes need a pressurized suit to not, you know, burst into flames, when spawning as a wizard you are automatically equipped with one. As a result, you can't wear your oh so important wizard robes to cast spells without spending two points on the No-Clothes ability.

**What did you expect to happen**: 
For the plasmaman suit wizards receive to allow me to cast spells so things are fair. (Admin said it was supposed to work so when it didn't I got screwed.)

**What happened instead**:
In my moment of desperation, I tried to use my mobility spells to escape the harm baton, only to find I could not. He promptly ripped my suit off and beat my flaming body to death.

**Why is this bad/What are the consequences:**
I understand different races face different challenges, like IPC wizards and their oh so loveable EMP weakness, but I feel like not being able to choose certain spells is a far cry from either having to waste two points because of your species or to have to only choose spells and equipment that don't require robes.

**Steps to reproduce the problem**:
Be plasmaman.
Spawn as Wizard.
Try to cast robe requiring spell without the no-clothes spell.
Profit?

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nope nope.

If you ask me this is an oppurtunity to just make an entirely new plasmaman suit for wizards so they're identifiable (If the assistant suit gains the ability to cast spells as robes you've just got a free two points in essence since you're not immediately obvious and you can cast spells. ) and we settle this matter.

**Comment by Fullofskittles** [comment] 2018-02-13 20:29
I actually did sprite some plasmaman wizard suits for anyone who wants to try fixing this. I just sprite, I don't code so here they are for anyone interested in tackling this: [Sprites](https://www.dropbox.com/s/y0e00nvu3231s65/Plasmaman_WizardOutfit2.dmi?dl=0)

![wizardplasmeme](https://user-images.githubusercontent.com/12588966/36172001-6c3ee728-10b9-11e8-8680-b1ed75ee0520.png)

It comes in standard blue, red, black and there's purple too if you wanna get crazy with colors.

**Comment by IK3I** [comment] 2018-02-13 20:50
When something like this happens, ask the admins to give you no clothes since this is clearly unintended behavior. As for a fix, should just be a wiz suit with the right flags attached.

**Comment by KingPhilipIII** [comment] 2018-02-13 20:53
I didn't know it didn't work like that until it was too late, this is just solving a future problem without the need for administrative interference each time.

**Comment by datlo** [comment] 2018-10-02 12:34
AFAIK this issue is fixed by #9473 and should be closed

**Closed** 2018-10-06 07:33 UTC
Labels: Bug
