### ISSUE TITLE
Ammo casing icons aren't updated when ejected

### ISSUE THREAD

**Issue by AugRob** [ParadiseSS13/Paradise#4405] opened 2016-05-09 16:01 UTC
**Problem Description**:
ammo casings don't do what they should when ejected

**What did you expect to happen**: 
update_icon() should be called on ammo casings when ejected by projectile weapons, including shotguns

**What happened instead**:
casings are ejected looking as if unspent when they really _are_ spent

**Why is this bad/What are the consequences:**
confusing and a waste of all those pretty spent shell icons

**Steps to reproduce the problem**:
shoot any automatic weapon or pump a shotgun

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:

**Comment by FalseIncarnate** [comment] 2016-05-12 05:35
Duplicate of https://github.com/ParadiseSS13/Paradise/issues/4244

**Closed** 2016-05-12 15:38 UTC
Labels: Bug, Sprites
