### ISSUE TITLE
#7639 not resolved - flagged jobs

### ISSUE THREAD

**Issue by Ralta** [ParadiseSS13/Paradise#7657] opened 2017-06-28 18:55 UTC
**Problem Description**:
Flagged jobs that are full should not show as flagged any more:

http://puu.sh/wwCnu/7095d4d8c3.png

**What did you expect to happen**: 
As per #7630 :
That once the slot was full, it would no longer be considered a priority.

**What happened instead**:
It continues to state that X, Y and Z jobs are high priority.

**Why is this bad/What are the consequences:**
Inconsistency. Nothing major beyond that.

*Steps to reproduce the problem**:
Late-join a round where jobs have been set as a priority but those specific roles are already full.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: This was supposedly fixed in #7639 but just noticed it occur now.

@Kyep

**Comment by Ralta** [comment] 2017-06-28 18:58
Better screen cap:
http://puu.sh/wwCES/a4b8b231c1.png

**Comment by Kyep** [comment] 2017-06-28 20:37
Three possible explanations:
1) My fix (although it worked in testing) failed somehow.
2) You don't have the required # of hours to play some of the jobs, so they don't show up in the joinable list for you even though there *are* slots open.
3) The HoP/Captain priorizied a job, then closed its job slots, resulting in a full job that is nevertheless still prioritzed.

Given that the job in your example is Captain... and it has the highest playtime requirement of all jobs... explanation (2) seems to be the most likely one. Can you verify that you really do have enough playtime to play Captain?

**Comment by Ralta** [comment] 2017-06-28 21:04
Yes. Definitely.

**Comment by Kyep** [comment] 2017-06-29 04:18
Well, I suppose the first thing for me to do is to fix possible cause 3, and then see if it still happens.
If it still happens at that point, the cause is either 1 or 2.

**Closed** 2017-07-09 00:32 UTC
