### ISSUE TITLE
GRASS

### ISSUE THREAD

**Issue by NTSAM** [ParadiseSS13/Paradise#3067] opened 2015-12-31 20:33 UTC
GRASS SOUNDS LIKE PLATING WHEN YOU WALK ON IT
Footsteps are funny

Steps to reproduce

1) Grow you some of that green stuff
2) Turn that into a tile by activating it in hand
3) Place that grass on some plating.
4) Smoke some kush and take a walk in your own artificial park
5) OH FUCK THE GRASS IS MADE OF METAL

I can probably record some sound of me walking over grass if we're gonna fix this or if we just let it be or whatever.

**Comment by TheDZD** [comment] 2015-12-31 20:52
I believe it's because @tigercat2000 only implemented footstep sounds for metal plating, and because the issue where footstep sounds are heard after removing a floor tile and replacing it was never fixed.

**Comment by NTSAM** [comment] 2015-12-31 20:57
Oh.

**Comment by CrAzYPiLoT-SS13** [comment] 2015-12-31 21:03
Maybe I shouldn't be suggesting this here, but can't the footstep sounds when walking into a wall issue be fixed with a simple if check for coordinates, if they don't change in a movement tick or whatever it's called, it sets silent_steps? I would test this and make a PR, but my Dream Daemon is fucking me over.

**Comment by Fox-McCloud** [comment] 2015-12-31 21:04
asteroid turfs also sound like plating.

**Comment by tigercat2000** [comment] 2015-12-31 21:08
1. asteroid turfs are probably a subtype of plating
2. this is just caused by update_icon() not clearing the footstep sounds list, when it should, there should be a `footstep_sounds = list()` right [hereish](https://github.com/ParadiseSS13/Paradise/blob/master/code/game/turfs/simulated/floor.dm#L111), and [New()](https://github.com/ParadiseSS13/Paradise/blob/master/code/game/turfs/simulated/floor.dm#L111) should have `update_icons()` added to it

**Closed** 2016-01-04 03:28 UTC
Labels: Inconsistency, Oversight
