### ISSUE TITLE
Rechargers not working after being moved.

### ISSUE THREAD

**Issue by UltraCraftGames** [ParadiseSS13/Paradise#17057] opened 2021-11-07 15:37 UTC
**Issue Description**:When i unwrench a working weapon recharger, bring it somewhere else and wrench it again it does not function, having no light and not charging what is put inside it. The area it was wrenched in is powered.

**What did you expect to happen**: For it to charge the weapon and the lights to appear.

**What happened instead**:They did not.

**Why is this bad/What are the consequences**:Prevents moving chargers.

**Steps to reproduce the problem**:Unwrench recharger, bring it somewhere else and wrench the recharger.

**When did the problem start happening**:A few weeks ago i noticed it while space exploring and today had it happen again. These are the only times ive moved a recharger.

**Extra information**:

**Comment by paulo-e** [comment] 2021-11-07 16:02
Can someone assign this to me?

**Comment by SteelSlayer** [comment] 2021-11-08 01:14
@paulo-e We don't really assign issues to people here. You can just go ahead and make a PR.

**Comment by Dovixx** [comment] 2021-11-30 13:56
I was unable to reproduce this issue when testing. I fear it might be some one off issue that happens sometimes?

**Comment by matttheficus** [comment] 2022-06-21 16:14
No Repro.

**Closed by matttheficus** 2022-06-21 16:14 UTC
Labels: Cannot Reproduce
