### ISSUE TITLE
Power cell gone on insert into APC by borg

### ISSUE THREAD

**Issue by hunakos57** [ParadiseSS13/Paradise#12871] opened 2020-01-01 08:32 UTC
**Issue Description**:

The power cells getting deleted when an engi borg tries to place it into an APC.

**What did you expect to happen**: 

The power cell end up in the APC and not in bluespace.

**What happened instead**:

The engi borg been recruited by powerfull wizards from the wizard federation and been thought how to destroy matter of a power cell by the ritual of placing it into the APC.

**Why is this bad/What are the consequences**:

Engi borgs can't finish, repair APCs

**Steps to reproduce the problem**:

Be engi borg. Open APC, take out Power cell with claw thingy, try to put it back... abraka-dabra, no more Power cell. (I tested it two different round before I started this bug report as Kyet requested.)

**When did the problem start happening**:

2020.01.01 07:22 - War round

**Extra information**:

The two places I tested it was the courtroom and Tcomms main chamber.

**Comment by SteelSlayer** [comment] 2020-01-01 08:40
Duplicate of #12627
I fix this in #12592

**Closed** 2020-04-11 05:21 UTC
