### ISSUE TITLE
Hearing binary chat as a non-synthetic

### ISSUE THREAD

**Issue by MarcellusPye** [ParadiseSS13/Paradise#8187] opened 2017-10-03 05:45 UTC
**Problem Description**:
I was able to hear binary chat as a non-synthetic without an encryption key

**What did you expect to happen**: 
Not to be able to hear binary chat

**What happened instead**:
I heard binary chat

**Why is this bad/What are the consequences:**
Muh balances

**Steps to reproduce the problem**:
I died, strange reagent was applied, I immediately died again due to prior damage, after being fixed I noticed that I was able to hear binary chat
![image](https://user-images.githubusercontent.com/29051928/31111496-ee038b36-a86a-11e7-98c6-a88941af4f93.png)

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Tractors, mid round blobs

**Comment by alexkar598** [comment] 2017-10-03 10:25
Dupe of #7121 something is wrong and weird about strange reagent

**Comment by tigercat2000** [comment] 2017-10-03 13:56
Duplicate of https://github.com/ParadiseSS13/Paradise/issues/7121

**Closed by tigercat2000** 2017-10-03 13:56 UTC
Labels: Duplicate
