### ISSUE TITLE
Nuke code doesn't always work.

### ISSUE THREAD

**Issue by tigercat2000** [ParadiseSS13/Paradise#2351] opened 2015-10-12 18:14 UTC
Not entirely sure the details of this, but it seems that the nuke code doesn't always actually work for unlocking the nuke. NanoUI issue?
http://nanotrasen.se/forum/viewtopic.php?f=12&t=6065

**Comment by TheDZD** [comment] 2015-10-12 18:35
Duplicate of #2307.

**Comment by tigercat2000** [comment] 2015-10-12 18:35
I thought I checked for those. RIP.

**Closed by TheDZD** 2015-10-12 18:35 UTC
