### ISSUE TITLE
ChemDispenser eats angry chemicals

### ISSUE THREAD

**Issue by Corona-Borealis** [ParadiseSS13/Paradise#14267] opened 2020-09-08 21:31 UTC
**Issue Description**:
If a beaker or bucket is put into a chem dispenser while on harm intent, all chemicals in the bucket vanish 5-10 seconds later. 

**What did you expect to happen**: 
Chemicals should either spill immediately or stay in bucket. 

**What happened instead**:
After a short delay where the chemicals are visible in the chem dispenser and can even react, everything in the bucket vanishes. This is reproducible. 

**Why is this bad/What are the consequences**:
Mainly, it's weird. 

**Steps to reproduce the problem**:
Be on harm intent
Have bucket with chemicals
Put bucket in chem dispenser

**When did the problem start happening**:
Still happens as of 8th of September, midnight GMT+1. 

**Extra information**:

**Comment by RedWolfie** [comment] 2020-09-09 09:31
I think this is caused by NanoUI not updating properly

**Comment by SteelSlayer** [comment] 2020-09-12 15:40
Does seem like this is nanoUI taking time to update. I couldn't get the chems to react though. For example I put chlorine and plasma in a bucket, harm clicked the dispenser, them clicked radium quickly, the other chems disappear and I was left with radium only.

**Comment by moxian** [comment] 2020-10-17 20:12
This is working as intended-ish. Or as implemented, at least.
Using beaker/bucket on harm intent splashes the contents onto.. whatever you're attacking, even if it's chem dispenser.
![dreamseeker-20201017-200047](https://user-images.githubusercontent.com/7831163/96352552-74d15b80-10b3-11eb-81ef-4d704ea3eafc.png)

The NanoUI not updating fast enough is only a display issue, and unrelated.

The overall attack logic: https://github.com/ParadiseSS13/Paradise/blob/914e1493cd3c9827644985ac8876b921ad897560/code/_onclick/item_attack.dm#L4-L6
Inserting into chem dispenser is handled in `attack_by`: https://github.com/ParadiseSS13/Paradise/blob/914e1493cd3c9827644985ac8876b921ad897560/code/modules/reagents/chemistry/machinery/chem_dispenser.dm#L249
And splashing happens later in beaker's `afterattack`: https://github.com/ParadiseSS13/Paradise/blob/914e1493cd3c9827644985ac8876b921ad897560/code/modules/reagents/reagent_containers/glass_containers.dm#L102-L106

Should be an easy first issue

**Comment by matttheficus** [comment] 2022-06-21 21:49
Unwanted due to Maint objection, closing.

**Closed by matttheficus** 2022-06-21 21:49 UTC
Labels: Cannot/Will Not Fix
