### ISSUE TITLE
New Firelocks aren't openable by AIs or Borgs.

### ISSUE THREAD

**Issue by Anoonki** [ParadiseSS13/Paradise#6615] opened 2017-02-26 11:54 UTC
**Problem Description**:
What it says on the title, or tin. AI can't open firelocks without going to the fire alarm and deactivating it.

**What did you expect to happen**: 
That the AI could interface with the firelock and open it.

**What happened instead**:
http://i.imgur.com/Tf45aS7.png
I banged on the firelock with my digital AI hands.

**Why is this bad/What are the consequences:**
AI unable to open firelocks to let crew in or out of areas with atmospheric alerts. AI generally in less control than normal

**Steps to reproduce the problem**:
Be the AI, activate a fire alarm, then try to click on a firelock.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing involving the gamemode should be effecting my ability to interact with firelocks. In the screenshot provided, I was trying to open the firelock above the engineer to get it out of the way (It wasn't especially helpful)

**Comment by Crazylemon64** [comment] 2017-02-26 12:02
@Markolie

**Comment by SamHPurp** [comment] 2017-02-26 12:06
Dupe of #6594 - although this one is worded more eloquently.

**Comment by Anoonki** [comment] 2017-02-26 12:18
My bad. 
Didn't see that other one. This can be closed.

**Comment by Markolie** [comment] 2017-02-26 13:07
Should be a super easy fix. I'm not home this week though so can't handle it.

**Comment by Crazylemon64** [comment] 2017-02-26 13:51
It's not *quite* the same bug, but they are similar, and probably linked

**Comment by Markolie** [comment] 2017-03-05 13:03
Close me!

**Closed** 2017-03-06 10:20 UTC
Labels: Bug
