### ISSUE TITLE
All popups bugged with empty screens.

### ISSUE THREAD

**Issue by Carratacus** [ParadiseSS13/Paradise#3766] opened 2016-03-05 21:46 UTC
Well, any objects that I attempt to access in game create their popups as normal. However, these popups are blank grey screens only displaying the Nanotransen logo background. When I say objects, I'm referring to PDAs, consoles, vending machines, fire alarms, the list goes on.

Unfortunately, this bug has rendered most roles either impossible or difficult to play correctly.

The only thing I can think of that may have caused this bug is a server or byond update, although I have no idea why this would be the case. It affects me from round start, to round end, no exceptions.

So far I've updated and reinstalled Byond, Java and Flashplayer, and given java and active x full permission on internet explorer.

I'll provide some images of this bizzare bug so you know what I'm talking about, any suggestions would be fantastic.

![image](https://cloud.githubusercontent.com/assets/17678919/13550708/b4046740-e31b-11e5-88cd-935f31c8716f.png)

**Comment by tigercat2000** [comment] 2016-03-05 21:57
It looks like you are running Windows XP. NanoUI uses HTML5, which earlier versions of internet explorer have iffy/no support for.

**Comment by Carratacus** [comment] 2016-03-05 22:00
I'm pretty sure I'm using Windows 7. Also, I tried updating IE, but it informed me that I have the earliest version already.

**Comment by tigercat2000** [comment] 2016-03-05 22:02
Open internet explorer, go to the gear in the top right, and find out the version from the "About Internet Explorer" version.

**Comment by Carratacus** [comment] 2016-03-05 22:05
Version 11. something

**Comment by tigercat2000** [comment] 2016-03-05 22:08
Huh. I forgot how much like XP windows 7's high constrast theme looks.

Not sure what the issue is then. If you open `C:/Users/[your_user_name]/My Documents/BYOND/cache` and open one of the `[random string of chars].htm` files (must be connected to the server) with a web browser, does it give you any errors in the console? (chrome and firefox would use f12 to see the console)

**Comment by Carratacus** [comment] 2016-03-05 22:14
Well, when opening these, I'm not getting any errors. Just some Byond stuff.

**Comment by Carratacus** [comment] 2016-03-05 22:15
Whatever's causing this issue, appears to be very well hidden.

**Comment by tigercat2000** [comment] 2016-03-05 22:16
Try turning off NanoUI's fancy mode, internet explorer may not get along with it in high contrast mode (preferences tab ingame > game preferences > fancy nanoui > off), then close and reopen the window

**Comment by Carratacus** [comment] 2016-03-05 22:17
Eh, I think it's off anyway, but I'll double check.

**Comment by Carratacus** [comment] 2016-03-05 22:19
Well, it's off, but the popups are still buggered. Also, it's prolly worth mentioning that I don't get this issue on other servers I play, like Archangel for example.

**Comment by Tastyfish** [comment] 2016-04-30 10:49
Technically duplicate of #3729

**Closed** 2016-04-30 11:07 UTC
Labels: Bug, User Interface
