### ISSUE TITLE
Additional random z levels (ie z level 9-12) block teleportation/lack flags

### ISSUE THREAD

**Issue by TDSSS** [ParadiseSS13/Paradise#11563] opened 2019-05-21 15:32 UTC
**Problem Description**:
The additional z levels created at roundstart (things like z level 12), block teleportation and lack the REACHABLE flag.
While it can be argued they should block teleportation, the reachable flag is described as:
// A level that can be navigated to through space
#define REACHABLE "Reachable"
And you can definitely reach those levels through space.

**What did you expect to happen**: 
for them to allow teleportation and be reachable.

**What happened instead**:
The level has the no teleportation flag and lacks the reachable flag

**Why is this bad/What are the consequences:**
Cult runes don't work due to the reachable flag. General teleportation doesn't work either. COnsidering those levels are basically the same as empty space levels seeded with space ruins, there's no reason they should disallow teleportation.

**Steps to reproduce the problem**:
Admin teleport or manually get to z level 12.
Scribe a teleport rune as cultist.
See:
![Capture](https://user-images.githubusercontent.com/32099540/58109540-1a964780-7bee-11e9-9b06-bd0637554e81.PNG)

**When did the problem start happening**:
No idea.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
As far as I can tell, the add_new_zlevel command just defaults to the trait BLOCK_TELEPORT, so I assume an oversight/laziness when writing the code caused this, rather than a deliberate attempt to block teleports to z12.

**Comment by AffectedArc07** [comment] 2019-05-21 15:39
Telescience also has this issue, but thats just becayse it just checks if the sector youre going to is `1, 3, 4, 5, 6, 7`

**Comment by Denthamos** [comment] 2019-05-21 18:43
Duplicate of #10282 which was opened back in 2018.

**Closed** 2019-08-12 08:42 UTC
