### ISSUE TITLE
Death Alarms and Brig cells in the AI law List.

### ISSUE THREAD

**Issue by Aurorablade** [ParadiseSS13/Paradise#4218] opened 2016-04-16 12:56 UTC
Death Alrams and Brig cells are showing up in the AI law list after they go off..and for each time they go off

**Comment by Tastyfish** [comment] 2016-04-16 20:59
Sounds like somehow radio.autosay()... is adding them to the law list? I don't even.

**Comment by Tastyfish** [comment] 2016-04-16 21:38
I'm unable to reproduce it though.

**Comment by Fox-McCloud** [comment] 2016-11-10 02:36
fixed by Crazy, at some point

**Closed** 2016-11-10 02:36 UTC
Labels: Bug
