### ISSUE TITLE
Ventcrawl pipes invisible

### ISSUE THREAD

**Issue by Threeinone** [ParadiseSS13/Paradise#9184] opened 2018-07-07 21:21 UTC
**Problem Description**:
Ventcrawling past a certain threshhold fails to show crawlable pipe

**What did you expect to happen**: 
Seeing all pipes through floors and walls, allowing for easy, intuitive crawling.

**What happened instead**:
Pipes were left unlit and un-shown through floors sparatically, sometime show a single pipe without showing how to get there.

**Why is this bad/What are the consequences:**
A lot of time wasted trying to mash your way through the vents, trying to get where your going, but going the exact opposite way because of how the pipes are laid out.

**Steps to reproduce the problem**:
The problem consistently arose every tie i crawled into a vent as anything

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: The main couple of things i was when i was crawling were a mouse, borer, diona nymph.

**Comment by taukausanake** [comment] 2018-07-08 02:03
Perhaps related to #8666?

**Comment by Threeinone** [comment] 2018-07-08 03:31
Yes, this is consistent with what happened to me. Perhaps I use the brig vents a lot, but it seemed to happen all the time, regardless of which vent or what species.

On July 7, 2018, at 10:03 PM, "Ronald T. Mullins III" <notifications@github.com> wrote:

Perhaps related to #8666?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ParadiseSS13/Paradise","title":"ParadiseSS13/Paradise","subtitle":"GitHub repository","main_image_url":"<a href="https://assets-cdn.github.com/images/email/message_cards/header.png">https://assets-cdn.github.com/images/email/message_cards/header.png</a>","avatar_image_url":"<a href="https://assets-cdn.github.com/images/email/message_cards/avatar.png">https://assets-cdn.github.com/images/email/message_cards/avatar.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/ParadiseSS13/Paradise">https://github.com/ParadiseSS13/Paradise</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@taukausanake in #9184: Perhaps related to #8666?"}],"action":{"name":"View Issue","url":"<a href="https://github.com/ParadiseSS13/Paradise/issues/9184#issuecomment-403256056">https://github.com/ParadiseSS13/Paradise/issues/9184#issuecomment-403256056</a>"}}} [ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/ParadiseSS13/Paradise/issues/9184#issuecomment-403256056">https://github.com/ParadiseSS13/Paradise/issues/9184#issuecomment-403256056</a>", "url": "<a href="https://github.com/ParadiseSS13/Paradise/issues/9184#issuecomment-403256056">https://github.com/ParadiseSS13/Paradise/issues/9184#issuecomment-403256056</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } }, { "@type": "MessageCard", "@context": "<a href="http://schema.org/extensions">http://schema.org/extensions</a>", "hideOriginalBody": "false", "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "Re: [ParadiseSS13/Paradise] Ventcrawl pipes invisible (#9184)", "sections": [ { "text": "", "activityTitle": "**Ronald T. Mullins III**", "activityImage": "<a href="https://assets-cdn.github.com/images/email/message_cards/avatar.png">https://assets-cdn.github.com/images/email/message_cards/avatar.png</a>", "activitySubtitle": "@taukausanake", "facts": [ ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "TextInput", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"ParadiseSS13/Paradise\",\n\"issueId\": 9184,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}" } ] }, { "name": "Close issue", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"ParadiseSS13/Paradise\",\n\"issueId\": 9184\n}" }, { "targets": [ { "os": "default", "uri": "<a href="https://github.com/ParadiseSS13/Paradise/issues/9184#issuecomment-403256056">https://github.com/ParadiseSS13/Paradise/issues/9184#issuecomment-403256056</a>" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 354024614\n}" } ], "themeColor": "26292E" } ]

**Comment by ppi13** [comment] 2018-07-10 05:53
The reason is that Normal pipes don't have a map, so you lose the map when entering those, and never get it back without exiting and re-entering

**Comment by Threeinone** [comment] 2018-07-12 04:32
Does this mean it is working as intended?

On July 10, 2018, at 1:53 AM, ppi13 <notifications@github.com> wrote:

The reason is that Normal pipes don't have a map, so you lose the map when entering those, and never get it back without exiting and re-entering

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ParadiseSS13/Paradise","title":"ParadiseSS13/Paradise","subtitle":"GitHub repository","main_image_url":"<a href="https://assets-cdn.github.com/images/email/message_cards/header.png">https://assets-cdn.github.com/images/email/message_cards/header.png</a>","avatar_image_url":"<a href="https://assets-cdn.github.com/images/email/message_cards/avatar.png">https://assets-cdn.github.com/images/email/message_cards/avatar.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/ParadiseSS13/Paradise">https://github.com/ParadiseSS13/Paradise</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ppi13 in #9184: The reason is that Normal pipes don't have a map, so you lose the map when entering those, and never get it back without exiting and re-entering"}],"action":{"name":"View Issue","url":"<a href="https://github.com/ParadiseSS13/Paradise/issues/9184#issuecomment-403708791">https://github.com/ParadiseSS13/Paradise/issues/9184#issuecomment-403708791</a>"}}} [ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/ParadiseSS13/Paradise/issues/9184#issuecomment-403708791">https://github.com/ParadiseSS13/Paradise/issues/9184#issuecomment-403708791</a>", "url": "<a href="https://github.com/ParadiseSS13/Paradise/issues/9184#issuecomment-403708791">https://github.com/ParadiseSS13/Paradise/issues/9184#issuecomment-403708791</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } }, { "@type": "MessageCard", "@context": "<a href="http://schema.org/extensions">http://schema.org/extensions</a>", "hideOriginalBody": "false", "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "Re: [ParadiseSS13/Paradise] Ventcrawl pipes invisible (#9184)", "sections": [ { "text": "", "activityTitle": "**ppi13**", "activityImage": "<a href="https://assets-cdn.github.com/images/email/message_cards/avatar.png">https://assets-cdn.github.com/images/email/message_cards/avatar.png</a>", "activitySubtitle": "@ppi13", "facts": [ ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "TextInput", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"ParadiseSS13/Paradise\",\n\"issueId\": 9184,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}" } ] }, { "name": "Close issue", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"ParadiseSS13/Paradise\",\n\"issueId\": 9184\n}" }, { "targets": [ { "os": "default", "uri": "<a href="https://github.com/ParadiseSS13/Paradise/issues/9184#issuecomment-403708791">https://github.com/ParadiseSS13/Paradise/issues/9184#issuecomment-403708791</a>" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 354024614\n}" } ], "themeColor": "26292E" } ]

**Comment by tigercat2000** [comment] 2018-07-13 13:47
`The reason is that Normal pipes don't have a map, so you lose the map when entering those, and never get it back without exiting and re-entering` Nope, it's a BYOND bug. Something makes the overlays fuck up. Clients should have all pipes in the pipenet added to their view.

**Comment by Threeinone** [comment] 2018-07-17 15:54
Interesting. So if it's a bug with BYOND itself, is it not fixable?

**Comment by Crazylemon64** [comment] 2018-08-28 02:46
@tigercat2000 it's not a BYOND issue, we just don't update the overlay when you switch pipenets.

**Comment by Crazylemon64** [comment] 2018-08-28 02:48
Duplicate of #7389

**Closed by Crazylemon64** 2018-08-28 02:48 UTC
Labels: Bug, Duplicate
