### ISSUE TITLE
Ambulance Trolley teleport glitch.

### ISSUE THREAD

**Issue by Birdtalon** [ParadiseSS13/Paradise#6560] opened 2017-02-21 19:10 UTC
**Problem Description**:
You can make the ambulance trolley teleport across the map from a point to where you are currently regardless of distance or walls etc.

**What did you expect to happen**: 
I'm not sure, not this.

**What happened instead**:
The ambulance trolley teleported.

**Why is this bad/What are the consequences:**
This bug could be abused as the teleport works with players buckled to the ambulance. Fairly obvious break in game mechanics.

**Steps to reproduce the problem**:
Upon discussion with an admin I am not making this information public - catch me on Discord for information.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Playing paramedic, although I doubt that makes a difference.

**Comment by taukausanake** [comment] 2017-02-21 19:53
Duplicate of #6256. I thought this looked familiar! But is it exactly the same?

**Comment by Birdtalon** [comment] 2017-02-21 19:57
I didn't see that, it seems like the issue may be in a similar vein but the way to create the glitch is different in #6256 than with mine.

**Comment by Markolie** [comment] 2017-02-22 18:48
This can only be fixed by fixing this abomination: https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/silicon/silicon.dm#L204. We really need to fix our bump code.

**Comment by Birdtalon** [comment] 2017-02-22 19:00
This isn't to do with silicons bumping at all. That's #6256

**Comment by Markolie** [comment] 2017-02-22 19:08
Yea, I have a bandaid fix. Shit's still glitchy when you pull the teleportation glitch, but you won';t actually teport anymore.

**Closed** 2017-02-24 19:57 UTC
Labels: Bug, Exploit
