### ISSUE TITLE
New Chem Dispenser UI is extremely inefficient for Laptop users

### ISSUE THREAD

**Issue by Kobic** [ParadiseSS13/Paradise#14202] opened 2020-08-31 21:07 UTC
**Issue Description**:
Making chemicals with this UI is near impossible for laptop users as our screen isn't big enough to see all the chemicals at once and scrolling looking for each chemical is EXTREMELY inefficient.

**What did you expect to happen**: 
I expected all the chemicals to be onscreen at once when using the new UI, but even with the window enlarged I can only seen Aluminum to Lithium which is a little over half the chemicals. 

**What happened instead**:
![Capture](https://user-images.githubusercontent.com/2037476/91768924-66cf8600-ebac-11ea-8165-877a462f6904.PNG)
Look at that. Do you know how annoying it is to have to scroll for each chemical? It takes 15 seconds just to make Unstable mutagen where it would take 3 before. 

**Why is this bad/What are the consequences**:
It's extremely slow to make chemicals this way and puts laptops users or ANYONE with a smaller screen at an unfair disadvantage.

**Steps to reproduce the problem**:
Make it so all chemicals appear on screen at once.

**When did the problem start happening**:
With the latest PR merge for the chem UI.

**Extra information**:
I don't care if you upgrade the UI but just make it so it doesn't put other people at a disadvantage

**Comment by dearmochi** [comment] 2020-08-31 21:10
That should happen. What is your resolution?

**Comment by moxian** [comment] 2020-10-17 19:53
The screenshot above is 1439x851
So I assume the screen is 1440x900 (note, not 1600x900).
In either case, I cannot reproduce this. Neither 1440x900 nor 1600x900 nor even 1280x720 give the unusable dispenser from the screenshot.
I'm more inclined to believe this might be an old IE issue that misinterprets TGUI/React.

**Comment by Sirryan2002** [comment] 2022-06-19 23:47
Very very likely fixed in #13738
I cannot reproduce it.

**Closed by Sirryan2002** 2022-06-19 23:47 UTC
Labels: TGUI
