### ISSUE TITLE
Phase Boots

### ISSUE THREAD

**Issue by Bormac** [ParadiseSS13/Paradise#22553] opened 2023-09-23 01:08 UTC
Found magboots on the floor, put them in my backpack, could not remove them from my backpack, noticed some very strange behavior with them while in my backpack, was advised to make an issue report

**What did you expect to happen**: 

Boots in boots out

**What happened instead**:

Boots phase through reality and are ethereal

**Why is this bad/What are the consequences**:

Being able to get things out of your bag is nice but also I dont think the way they interacted with the world is correct

**Steps to reproduce the problem**:

I could not begin to tell you how it happened but it did

**When did the problem start happening**:

Today...?

https://github.com/ParadiseSS13/Paradise/assets/25037899/9dfa7e33-df88-4b27-b2dd-b793a0047763

Edited with a different video file hope that works

**Extra information**:

**Comment by lewcc** [comment] 2023-10-03 01:51
Is it possible these somehow came out of modsuits?

**Comment by Bormac** [comment] 2023-10-06 00:55
I mean maybe, I dunno. CE and I both got abductored and he was gone when I made it back there to get my stuff. I assume they came from him in one way or antoher they are the advanced magboots after all.

**Comment by DGamerL** [comment] 2023-10-23 01:36
Closing as it is a duplicate of #22666, a TM is on the server at the moment to make sure this will not happen. Thank you for making this report!

**Closed by DGamerL** 2023-10-23 01:36 UTC
Labels: Bug, BYOND Issue, WTF
