### ISSUE TITLE
Runtime when people from before #17467 save their preferences

### ISSUE THREAD

**Issue by moxian** [ParadiseSS13/Paradise#18122] opened 2022-06-28 11:34 UTC
**Issue Description**:
In the live runtime log:
```
[2022-06-28T05:10:47] Runtime in code/modules/client/preference/preferences_mysql.dm,54: **CKEY** had a malformed role entry: 'shadowling'. Removing!
[2022-06-28T05:10:47]   src: /datum/preferences (/datum/preferences)
[2022-06-28T05:10:47]   usr: **REDACTED** (/mob/new_player)
[2022-06-28T05:10:47]   usr.loc: The plating (8,187,1) (/turf/simulated/floor/plating)
```

This happens whenever a person saves their game settings if the last time they saved settings before that was prior to #17467 being merged.

This is not a very actionable runtime though, and does not point at a code bug.
The two options to fix it that i see are:
- silence the runtime in .dm. Something like
```dm
	for(var/role in be_special)
		if(!(role in GLOB.special_roles))
			be_special -= role
			// old roles which got removed from the code, but still present in the db
			if(!(role in list("shadowling")))
				log_runtime(EXCEPTION("[C.key] had a malformed role entry: '[role]'. Removing!"), src)
```
- update the db to strip the `&shadowling=` string from `be_role` column. Something like
```sql
UPDATE player
SET be_role = REPLACE(REPLACE(be_role, 'changeling=&', ''), '&changeling=', '') ;
```

I personally prefer the latter, but the decision is really up to the host to decide

**What did you expect to happen**: 
no runtime

**What happened instead**:
runtime

**Why is this bad/What are the consequences**:
runtime log being spammed with unactionable errors hides the real issues
empty runtime log good

**When did the problem start happening**:
#17467 most likely

**Comment by Sirryan2002** [comment] 2022-06-28 13:27
Pretttty sure this is intended behavior, the log runtime was put in because it was expected that eventually, we would be removing existing options from antag preferences. TBQH, this doesn't need a PR to be fixed, it would be much simpler like you said for the host to make the decision and just run a query since it doesn't actually change the structure of the DB.

**Comment by Sirryan2002** [comment] 2022-07-19 23:40
After some discussion with the development team, this is really a non-issue. While this is technically throwing a runtime, it would be best if these were instead thrown as just a debug log (as that's what they are basically). Closing as not an issue, we appreciate the report though.

**Closed by Sirryan2002** 2022-07-19 23:40 UTC
Labels: Runtime, (99% Sure) Not A Bug
