### ISSUE TITLE
Can't repair augmented torsos

### ISSUE THREAD

**Issue by tinfoiltophat** [ParadiseSS13/Paradise#8140] opened 2017-09-25 16:06 UTC
**Problem Description**:
You cannot repair an augmented torso with welders or cable coil.

**What did you expect to happen**: 
You should be able to repair an augmented torso with welders or cable coil.

**What happened instead**:
You cannot.

**Why is this bad/What are the consequences:**
Getting damaged while your torso is augmented makes you SOL

**Steps to reproduce the problem**
1.Punch some nerd in his augmented torso
2.Feel bad and attempt repairs.
3.Cry because you've permanently injured this fellow.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Chems don't seem to work either. Also, the time I tested this I was simultaneously testing #8139 so it may only be when the full body is augmented, so this needs review on a test server.

**Comment by taukausanake** [comment] 2017-09-25 17:15
> 3.Laugh hysterically because you've turned this fellow's chest into a bowl.

Fixed

**Comment by Certhic** [comment] 2018-10-31 19:43
Your steps of reproduction seem rather vague.

Cybernetic repair surgery fixes brute damage, and it seems to work normally at the moment.

**Comment by Burzah** [comment] 2023-08-22 11:44
Tested this today to see if it was still occurring. I was not able to reproduce this bug. As this has been opened since 2017 I will be closing this issue. Thank you for making a report!

**Closed by Burzah** 2023-08-22 11:44 UTC
Labels: Bug
