### ISSUE TITLE
Invisible Item AI Hud Bugs

### ISSUE THREAD

**Issue by Banderblitz** [ParadiseSS13/Paradise#22973] opened 2023-10-20 20:59 UTC
**Issue Description**:
When someone is wearing an agent ID (possibly another agent item I am not sure what), they appear completely invisible, however you are able to see huds above the person and thus examine them, IE medical hud, security hud, etc.

**What did you expect to happen**: 
I expected not to see a floating hud wandering around and be able to examine and tell the identity of someone, and just be in utter confusion of things moving invisibly or watching security fighting nothing.

**What happened instead**:
I saw an invisible hud and was able to examine them and see who they were, everything they wore and such despite not being able to see them at all visually.

**Why is this bad/What are the consequences**:
Bugs bad, and an AI being able to see through something that's supposed to be invisible to them is counterproductive to the item/abiliti's existence

**Steps to reproduce the problem**:
1. Be AI.
2. Have someone with an agent ID standing somewhere wearing it.
3. Turn Sec/medhud on as AI.
4. Examine the hud of the invisible agent and see their description.

**When did the problem start happening**:
As of 10/20/2023 on round 37759.

**Extra information**:
Unsure if this was caused by a changeling or an agent ID or some other traitor item, however they were wearing an agent ID at the time so I assume that, and if it happens to that, it MAY also happen to invisible changelings and other things.

**Comment by Banderblitz** [comment] 2023-10-20 21:02
Apparently as I was informed not long after, it is an obfuscation suit from the traitor uplink, replace the reproduction issues from agent ID to obfuscation suit, and you should be able to see the issue.

**Comment by DGamerL** [comment] 2023-10-21 00:49
Duplicate of #21356 , closing

**Closed by DGamerL** 2023-10-21 00:49 UTC
Labels: Bug, Duplicate
