### ISSUE TITLE
Ian or Runtime stuck in the E.X.P.E.R.I.-mentor

### ISSUE THREAD

**Issue by longcyber2** [ParadiseSS13/Paradise#22409] opened 2023-09-14 20:41 UTC
**Issue Description**:

Runtime or Ian will get stuck in the E.X.P.E.R.I.-mentor when it summons them. This has happened multiple times throughout my time playing and it still hasn't been fixed yet.

**What did you expect to happen**: 

This is a issue because the CMO or the HOP will not be happy when the E.X.P.E.R.I-mentor eventually fails and draws flesh and blood from everyone around it. This will kill Runtime or Ian (or both if they are both in the same room).

**What happened instead**:

I cannot drag or throw Ian or Runtime out of the E.X.P.E.R.I-mentor. It is stuck.

**Why is this bad/What are the consequences**:

Once again, CMO or HOP will get a little upset that their favorite pet died.

**Steps to reproduce the problem**:

Use the E.X.P.E.R.I.-Mentor until it gets a runtime error or the air ian-izes. This issue may not be consistent, but its often enough that its a problem.

**When did the problem start happening**:

It has happened since I joined this server, which was a solid month or two ago. (idk I forgor)

**Extra information**:

Nothing else really needs to be said.

**Comment by 1080pCat** [comment] 2023-09-14 20:45
Same issue as [#18778](https://github.com/ParadiseSS13/Paradise/issues/18778)
Not really sure why its tagged with 'working as intended:tm:', but.

**Comment by Henri215** [comment] 2023-09-14 20:56
Like 1080pCat has said, it is a duplicate of https://github.com/ParadiseSS13/Paradise/issues/18778.
Thank you for reporting anyway.

**Closed by Henri215** 2023-09-14 20:56 UTC
Labels: Duplicate
