### ISSUE TITLE
If IPC is revived headless, still has normal vision

### ISSUE THREAD

**Issue by iantine** [ParadiseSS13/Paradise#9967] opened 2018-10-25 04:40 UTC
**Problem Description**:
As an IPC, player died and lost their head in the process. Upon being revived to living condition but with no head attached, player could see the screen as if they had a head with optics attached.

**What did you expect to happen**: 
Upon being revived to living condition as just a body with limbs, I expected to see the typical 'blind' screen.

**What happened instead**:
Immediately upon returning from the dead body view screen of being able to see everything around you just like a ghost, I returned to the view screen of being able to see your immediate surroundings with regular view, as if I had a regular head, despite having no head/optical sensors.

**Why is this bad/What are the consequences:**
An IPC should require a head/optical sensors to see.

**Steps to reproduce the problem**:
1. Die as an IPC, and lose your head in the process or after.
2. Be repaired to a living state, but do not have your head attached, or do not have optics attached to the head.
3. See through a screen that shows you a 'seeing person' screen.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Cyberiad map, traitor round. Screenshot:
![err](https://user-images.githubusercontent.com/26665535/47476441-2b572880-d86c-11e8-80f0-0be4d16c6484.png)

**Comment by lass9030** [comment] 2018-10-25 14:36
I was unable to reproduce this, although i did find a runtime #9972.
Might have something to do with it, might not.

**Comment by Shadow-Quill** [comment] 2019-08-16 21:05
@Fox-McCloud Couldn't reproduce, no runtimes.

**Comment by iantine** [comment] 2019-08-16 23:43
Haven't seen the issue happen again or had anyone else speak of the issue happen since that one time. I'm happy to have this closed.

**Comment by Shadow-Quill** [comment] 2019-08-17 01:41
@iantine You can close the issue by clicking "Close Issue" by the comment box.

**Closed** 2019-08-17 06:26 UTC
Labels: Bug
