### ISSUE TITLE
Mining Cyborg PKA only has 80% mod capacity

### ISSUE THREAD

**Issue by Zorazi-Teo-Daedalus** [ParadiseSS13/Paradise#19416] opened 2022-10-17 04:10 UTC
**Issue Description**:

The Cyborg PKA mining tool only has a base mod capacity of 80% of the normal PKA mod capacity.

**What did you expect to happen**: 

I expect to be able to put a normal amount of mods into the PKA, as opposed to having it be reduced for no reason that I can think of beyond a simple mistake.

**What happened instead**:

You just kinda can't modify the PKA as much as you should be able to, and that's dumb.

**Why is this bad/What are the consequences**:

I cannot think of a possible reason to kneecap the function of the Cyborg PKA that isn't entirely arbitrary. If the concern is making it so that the Cyborg isn't as powerful a miner as carbonmob miners, they're already worse off by not having access to plasma cutters or the ability to utilize lavaland loot, mining points, or even creature parts from Goliaths for example.

**Steps to reproduce the problem**:

Become mining cyborg. Examine PKA. Be annoyed.

**When did the problem start happening**:

I haven't played much mining cyborg so I don't know if this is only a recent issue but I figured I needed to make the issue all the same.

**Extra information**:

See attached image below.
![Bugged PKA](https://user-images.githubusercontent.com/71111573/196087591-a02fe4ec-db3a-4fe3-b277-e65ac93a15d5.png)

**Comment by GDNgit** [comment] 2022-10-17 12:02
/obj/item/gun/energy/kinetic_accelerator/cyborg
	holds_charge = TRUE
	unique_frequency = TRUE
	max_mod_capacity = 80

Not a bug

**Comment by matttheficus** [comment] 2022-10-17 12:10
as GDN said, it appears to not be a bug, but odd wording of the Mod Capacity. As such, closing.

**Closed by matttheficus** 2022-10-17 12:10 UTC
