### ISSUE TITLE
Removing the trunk beneath a disposals chute means you can no longer deconstruct the chute.

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#6673] opened 2017-03-04 01:33 UTC
Problem Description:
Removing the pipe trunk beneath a disposals chute that is set up causes the chute to exist in a stuck state and cannot be removed.

What did you expect to happen:
You should be able to remove a chute regardless if a trunk is under it.

What happened instead:
It complains that there is no trunk underneath, despite the fact you're trying to DECONSTRUCT it.

Why is this bad/What are the consequences:
It becomes an impassible obstacle.

Steps to reproduce the problem:
Install a disposals trunk pipe.
Install chute on top of it.
Remove trunk.

Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?): Anything else you can tell us.

It's annoying... :-/. I believe the checks around here are what need to be adjusted: https://github.com/ParadiseSS13/Paradise/blob/18f4aa18b98fcf8503f7173d3e294d581aa2acff/code/modules/recycling/disposal-construction.dm#L179

Simply stopping someone from removing the trunk won't be enough... if somehow the trunk is destroyed by a bomb but the tile or chute survives, you will end up with the same problem.

**Comment by Crazylemon64** [comment] 2017-03-04 02:21
Duplicate of #6671

**Closed by Crazylemon64** 2017-03-04 02:21 UTC
Labels: Duplicate

**Comment by Anticept** [comment] 2017-03-04 04:09
I... what? I must be tired as hell or something. I swear that didn't mention anything about trying to remove it, just nullspacing.
