### ISSUE TITLE
Alternate Job Titles prevents you from accessing departmental accounts

### ISSUE THREAD

**Issue by Contrabang** [ParadiseSS13/Paradise#20033] opened 2022-12-28 22:53 UTC
**Issue Description**:

Having a job title (e.g. "Maintenance Technician" instead of "Station Engineer") prevents you from seeing your departmental account at cargo

**What did you expect to happen**: 

to see personal account, departumental account, supply account

**What happened instead**:

sees personal account and supply account

**Why is this bad/What are the consequences**:

Certain people cant order stuff

**Steps to reproduce the problem**:

Have a special title roundstart (e.g. "Maintenance Technician" instead of "Station Engineer"

**When did the problem start happening**:

Economy refactor

**Extra information**:

I made a snowman today :)

**Comment by warriorstar-orion** [comment] 2022-12-28 22:57
I believe this is a duplicate of #19901.

**Closed** 2022-12-29 05:02 UTC
Labels: Duplicate
