### ISSUE TITLE
Organs & Freezers

### ISSUE THREAD

**Issue by Deanthelis** [ParadiseSS13/Paradise#2854] opened 2015-12-15 23:51 UTC
Limbs, hearts, eyeballs, and other organs left out in the open decay normally; that is, after a short period of time, Examining them will indicate they have decayed.

Organs left in a Freezer, like the ones in Surgery, give the appearance of working; if the organs are kept inside, Examining them never changes. They appear to be unrotten. However, when transplanted into a patient, they are full of infections; the organ rots anyway, despite not appearing to be decayed.

I do not know whether organs are intended to stop decaying in a freezer or not, but either way this should probably be fixed.

**Comment by Crazylemon64** [comment] 2015-12-16 00:32
Oh, I don't think the bacteria increasing code for when an organ is outside of a person accounts for the organ being in a freezer. Should be an easy enough fix

**Comment by Crazylemon64** [comment] 2015-12-16 00:45
Which organs are exhibiting the weird behavior? Limbs, or internal ones? The logic for the two differs, and the external limbs have additional processing that might mess up the freezer handling.

**Comment by Ar3nn** [comment] 2015-12-16 08:39
I'd look at the OP

"Limbs, hearts, eyeballs, etc"

**Comment by Crazylemon64** [comment] 2015-12-16 08:46
I suspect this may be from an isolated incident, and that they may have only done this with one type or the other. Knowing which will really help with finding where things went wrong.

**Comment by Crazylemon64** [comment] 2015-12-17 05:18
I can confirm that the freezer works for internal organs - thus, unable to replicate. You ARE administering antibiotics with the new organs, right?

**Comment by Crazylemon64** [comment] 2015-12-17 11:13
OH: Is the problem that if, for example, you chop off someone's head and put it in the freezer, that the organs inside the head (brain, eyes) don't get preserved? I think with an in_contents_of check or something this could be fixed, if this is what you are referring to. Your description of the problem is rather vague, @Deanthelis

**Comment by Crazylemon64** [comment] 2015-12-17 11:16
I think this would also cause, for example, a foot attached to a leg to rot while in a freezer. Is this the issue?

**Comment by Deanthelis** [comment] 2015-12-17 23:11
Oh, snap. I didn't expect such an immediate response. I'll fully explain what it is I did.

At the beginning of a round, I obtained a humanized monkey and disassembled it. Surgically, I removed the hands, arms, legs, feet, lower body, head, brain, eyes, heart, lungs, liver, kidneys, and appendix, and after each removal, I placed the organ into a freezer and closed the freezer. The organs were not exposed to normal air, so to speak, for more than a few seconds apiece.

An individual later required new eyeballs and a new heart. This was one hour or so into the shift, and the freezer had not been opened. When transplanting the new organs, I Examined them, and the did not say 'Decay has set in.' Yet the eyeballs had an Acute++ Infection and the Heart had an Acute+ Infection, in spite of at maximum 20 seconds of exposure to the air.

I did not discover any issues with organs contained by other organs (Feet on legs, brains in heads, etc) rotting while in the freezer because I did not happen to experience that; however, I did test both internal organs and limbs.

This issue of organs rotting anyway while in a freezer (After a half hour or more spent inside) has been a recurring one, to the point where players who are far more experienced with Medical and the new organ system in general refuse to freezer organs at all, instead opting to store a humanized monkey somewhere to gut it when needed.

It's not a massive problem, but it'd be nice to be able to have a stockpile of organs if need be, or rescue organs from uncloneable corpses.

This is tangentially related and outside the scope of this issue, but some method of disinfecting organs would be rather helpful; a machine that takes time to disinfect, with a longer amount of time dependent upon infection severity, or a reagent that, when injected into an organ, fixes an amount of infection per unit administered. A possibly simpler approach could also be allowing scalpel+cautery to disinfect organs that aren't already thoroughly rotten.

**Comment by Crazylemon64** [comment] 2015-12-17 23:31
Well... as it stands, you CAN disinfect organs, hilariously enough, by washing them in a sink, but that's probably very very silly... Perhaps, the organs can check if they are on the same tile as an open freezer, so the short stints where the freezer is open while you add new organs don't imperil everything else inside. I'll write a fix for that, and once that's merged, you can tell me if that did the trick.

**Comment by Deanthelis** [comment] 2015-12-18 05:30
Sounds good.

**Comment by Crazylemon64** [comment] 2015-12-18 11:38
@Deanthelis Are your hands clean (gloves ideally) when chopping off extra limbs? If they aren't, they'll grab the 110 or so points of infection you have on unwashed hands right as you chop them off, making them infected when you try to do a straight graft with them

**Comment by Crazylemon64** [comment] 2015-12-21 05:37
Alright, now that my PR's been merged, let me know if this addressed your concerns properly.

**Comment by Crazylemon64** [comment] 2015-12-21 05:37
Alright, now that my PR's been merged, let me know if this addressed your concerns properly @Deanthelis

**Comment by Crazylemon64** [comment] 2015-12-23 06:37
@Deanthelis I believe this PR's been merged for a while now, are things working better?

**Comment by Deanthelis** [comment] 2015-12-23 11:16
Can't say, happened (mostly by chance) not to toy with it in favor of playing with other stuff.

I'll test it tomor- oh,it's today already. Today.

**Comment by Fox-McCloud** [comment] 2015-12-28 04:34
@Deanthelis 

Tested this? Anyone else?

**Comment by Crazylemon64** [comment] 2015-12-28 07:46
I mean mechanically it works, but as whether it makes organ transplants viable, design-wise... Might just hop on the server tomorrow and see if I can't get it working myself.

**Closed** 2016-01-29 07:36 UTC
Labels: Inconsistency
