### ISSUE TITLE
Walls, tables, and many other things were undeconstructable for a shift.

### ISSUE THREAD

**Issue by Dashsora** [ParadiseSS13/Paradise#13168] opened 2020-03-22 03:00 UTC
**Issue Description**:
Welding walls, and wrenching or screwdriving tables and computers would pop their processing bar for half a second, then it'd go away and never complete. 

**What did you expect to happen**: 
Things to be deconstructed.

**What happened instead**:
Nothing happened instead.

**Why is this bad/What are the consequences**:
It makes it impossible to remove these structures without destroying them.

**Steps to reproduce the problem**:
Try using a wrench or a screwdriver on a table or table frame, or a welder on either a wall or a reinforced wall. Witnessed multiple people try and fail.

**When did the problem start happening**:
Working the very previous shift, this only has ever happened to me on the shift going on at the time this was  posted.

**Extra information**:
List of known things affected : deconstructing tables, walls and computers, moving vending machines, disassembling operating tables and anything disposals related.
Atmospherics pipes were okay.

Was told to ping @Citinited about this.

**Comment by Mitchs98** [comment] 2020-03-22 03:10
`[2020-03-21T22:08:31] Runtime in tool_behaviour.dm,60: undefined proc or verb /list/Invoke(). 
   proc name: tool check callback (/obj/item/proc/tool_check_callback)
   usr: Randy Ali (mitchs98) (/mob/living/carbon/human)
   usr.loc: The floor (121,83,1) (/turf/simulated/floor/plasteel)
   src: the hand drill (/obj/item/screwdriver/power)
   src.loc: Randy Ali (/mob/living/carbon/human)
   call stack:
   the hand drill (/obj/item/screwdriver/power): tool check callback(Randy Ali (/mob/living/carbon/human), the reinforced window (/obj/structure/window/reinforced), 0, /list (/list))
   /datum/callback (/datum/callback): Invoke()
   check for true callbacks(/list (/list))
   do after(Randy Ali (/mob/living/carbon/human), 0.25, 1, the reinforced window (/obj/structure/window/reinforced), 1, /list (/list), 1)
   the hand drill (/obj/item/screwdriver/power): use tool(the reinforced window (/obj/structure/window/reinforced), Randy Ali (/mob/living/carbon/human), 0.25, 0, 50, /list (/list))
   the reinforced window (/obj/structure/window/reinforced): screwdriver act(Randy Ali (/mob/living/carbon/human), the hand drill (/obj/item/screwdriver/power))
   the reinforced window (/obj/structure/window/reinforced): tool act(Randy Ali (/mob/living/carbon/human), the hand drill (/obj/item/screwdriver/power), "screwdriver")
   the hand drill (/obj/item/screwdriver/power): tool attack chain(Randy Ali (/mob/living/carbon/human), the reinforced window (/obj/structure/window/reinforced))
   the hand drill (/obj/item/screwdriver/power): melee attack chain(Randy Ali (/mob/living/carbon/human), the reinforced window (/obj/structure/window/reinforced), "icon-x=15;icon-y=6;left=1;scre...")
   Randy Ali (/mob/living/carbon/human): ClickOn(the reinforced window (/obj/structure/window/reinforced), "icon-x=15;icon-y=6;left=1;scre...")
   the reinforced window (/obj/structure/window/reinforced): Click(the plating (121,84,1) (/turf/simulated/floor/plating), "mapwindow.map", "icon-x=15;icon-y=6;left=1;scre...")`

Possible associated runtime. Doesn't occur when trying to decon a table or wall, oddly enough, this occurred when deconstructing a window. Deconstructing the window worked fine, yet still runtimed.

**Comment by shawnhind** [comment] 2020-03-22 03:20
Duplicate of https://github.com/ParadiseSS13/Paradise/issues/13167 ;)

**Comment by SteelSlayer** [comment] 2020-03-22 04:50
Thanks to Mitch's runtime post, I'm pretty sure I know whats causing this, will fix soon.

**Closed** 2020-03-23 00:34 UTC
