### ISSUE TITLE
Signs can be duplicated

### ISSUE THREAD

**Issue by DenialDuckOfService** [ParadiseSS13/Paradise#8144] opened 2017-09-26 16:21 UTC
**Problem Description**: You can duplicate a sign, From 1 sign to 2 to 3 to 4 and so on.
What is the problem?

**What did you expect to happen**: Nothing, I found it accidentally.
Why do you think this is a bug?
I don't think making an infinite amount of signs using one sign is very..logical?
**What happened instead**: It duplicated.
How is what happened different from what you expected?
Ones a nothing and ones something.
**Why is this bad/What are the consequences:**
Making infinite signs out of one breaks all logic and everyones MURSHUNS.
Why do you think this is an important issue?
I don't think it's THAT important but hey.
**Steps to reproduce the problem**: Step 1. Get a screwdriver. Step 2. Find a sign. Step 3. Click the sign twice. Step 4. Press south then north, or whatever direction you want. step 5. You have just duplicated one sign into two! Now have fun.
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Secret, I was walking around the hallways, No.

**Comment by FalseIncarnate** [comment] 2017-09-26 18:14
Can you be a bit more clear on the reproduction steps?

Are you clicking the sign twice to remove it from the wall and it generates two separate signs?

**Comment by scrubmcnoob** [comment] 2017-09-30 19:06
You're going need to explain the steps better. Can't reproduce.

**Comment by Citinited** [comment] 2018-10-08 21:02
@Crazylemon64 Bookkeeping - this is fixed by #9167 I believe

**Closed** 2018-10-14 11:09 UTC
Labels: Bug, Need Verification
