### ISSUE TITLE
DeltaStation issues megathread

### ISSUE THREAD

**Issue by AffectedArc07** [ParadiseSS13/Paradise#16071] opened 2021-05-24 19:04 UTC
Post here anything regarding delta not being right, and we can work on it.

**Comment by SabreML** [comment] 2021-05-24 19:05
![image](https://user-images.githubusercontent.com/57483089/119395397-58da0c00-bccb-11eb-9220-70c0efb4858d.png)

**Comment by Boidca** [comment] 2021-05-24 19:05
Hello, The Spacepod fabricator unloads the stuff onto the table below it:

![image](https://user-images.githubusercontent.com/71344502/119395427-65f6fb00-bccb-11eb-9a54-88e02f664e96.png)

**Comment by S34NW** [comment] 2021-05-24 19:06
![image](https://user-images.githubusercontent.com/12197162/119395526-8b840480-bccb-11eb-9755-57c8fe387bb5.png)
this is the entire capacity of the brig

**Comment by S34NW** [comment] 2021-05-24 19:08
![image](https://user-images.githubusercontent.com/12197162/119395711-d4d45400-bccb-11eb-8696-36b0ca3098a8.png)
old style windows, rad collectors too far away to generate power proerly

**Comment by CarlLomax** [comment] 2021-05-24 19:10
No psych office

**Comment by Qwertytoforty** [comment] 2021-05-24 19:10
![image](https://user-images.githubusercontent.com/52090703/119395893-22d46200-bca2-11eb-9c51-36e4cca83436.png)
mining shuttle does this skrek when on station

**Comment by Boidca** [comment] 2021-05-24 19:10
Sec pod bay is open by default, the mechanic can break in easily and steal all the stuff in the sec pod bay by exiting pod inside the podlock:

![image](https://user-images.githubusercontent.com/71344502/119395829-f9c8c700-bccb-11eb-81d8-44fd7ade0466.png)

**Comment by S34NW** [comment] 2021-05-24 19:14
![image](https://user-images.githubusercontent.com/12197162/119396288-94c1a100-bccc-11eb-949c-f2e5efb29ada.png)
no stamp or fax machine for captain

**Comment by S34NW** [comment] 2021-05-24 19:15
![image](https://user-images.githubusercontent.com/12197162/119396425-bae74100-bccc-11eb-9a00-a587359f7bd5.png)

no ticket machine for hop line

**Comment by SabreML** [comment] 2021-05-24 19:16
Tesla engine eats the containment wires
![image](https://user-images.githubusercontent.com/57483089/119396519-d8b4a600-bccc-11eb-9f3d-fa05a2e48ebc.png)

**Comment by S34NW** [comment] 2021-05-24 19:18
![image](https://user-images.githubusercontent.com/12197162/119396720-25987c80-bccd-11eb-8779-902c838a581c.png)
tcomms room is not connected to the grid

**Comment by LightFire53** [comment] 2021-05-24 19:20
> ![image](https://user-images.githubusercontent.com/12197162/119396288-94c1a100-bccc-11eb-949c-f2e5efb29ada.png)
> no stamp or fax machine for captain

No chain of command either.

**Comment by SabreML** [comment] 2021-05-24 19:20
There's sec checkpoints in each department. Not nessecarily an *issue*, but it's an inconsistency.

**Comment by LightFire53** [comment] 2021-05-24 19:21
The psychiatrist doesn't have a room anymore in medical, however one of the patient rooms could be converted to create one.

**Comment by S34NW** [comment] 2021-05-24 19:22
![image](https://user-images.githubusercontent.com/12197162/119397269-ca1abe80-bccd-11eb-9138-2dee5907b8c0.png)

supermatter APC is unconnected

**Comment by E-MonaRhg** [comment] 2021-05-24 19:23
> There's sec checkpoints in each department. Not nessecarily an issue, but it's an inconsistency.

>this is the entire capacity of the brig

Checkpoints have their own cells
Science:
![image](https://user-images.githubusercontent.com/71735193/119397117-fdf9e200-bcd5-11eb-84f2-853e5d086ef4.png)

Medbay: 
![image](https://user-images.githubusercontent.com/71735193/119397307-3bf70600-bcd6-11eb-9049-059f16459d50.png)

**Comment by S34NW** [comment] 2021-05-24 19:23
Those seem less like cells and more like mini-processing areas

**Comment by E-MonaRhg** [comment] 2021-05-24 19:24
> Those seem less like cells and more like mini-processing areas

They seem fully functional
![image](https://user-images.githubusercontent.com/71735193/119397463-6ea0fe80-bcd6-11eb-8016-37a894be5562.png)

**Comment by S34NW** [comment] 2021-05-24 19:26
![image](https://user-images.githubusercontent.com/12197162/119397595-457c7000-bcce-11eb-9410-34bd161a0278.png)
disposals to recycler is the wrong chute and throws trash all over the room

**Comment by S34NW** [comment] 2021-05-24 19:29
![image](https://user-images.githubusercontent.com/12197162/119397945-c3d91200-bcce-11eb-899a-5c767db84630.png)
server room vents are both blowing, so it doesn't get cooled

**Comment by E-MonaRhg** [comment] 2021-05-24 19:30
Cargo also has a cell 
![image](https://user-images.githubusercontent.com/71735193/119397979-32ba6900-bcd7-11eb-999f-6884fa0d05b4.png)

**Comment by S34NW** [comment] 2021-05-24 19:30
![image](https://user-images.githubusercontent.com/12197162/119398008-da7f6900-bcce-11eb-9108-ac0c346cc470.png)
there is no area air computer to control the large scrubbers

**Comment by LightFire53** [comment] 2021-05-24 19:30
Magistrate does not have an office location per se. The courtroom is labelled as the magistrate's office, and it doesn't have a fax machine, stamp, or fancy pen.

**Comment by E-MonaRhg** [comment] 2021-05-24 19:31
Cargo shuttle looks like this
![image](https://user-images.githubusercontent.com/71735193/119398120-64cbcb00-bcd7-11eb-8079-cfc8484daa0b.png)

**Comment by S34NW** [comment] 2021-05-24 19:32
> 
> > Those seem less like cells and more like mini-processing areas
> 
> They seem fully functional
> ![image](https://user-images.githubusercontent.com/71735193/119397463-6ea0fe80-bcd6-11eb-8016-37a894be5562.png)

Those cell timers are only accessible from outside the security area, an oversight no doubt

**Comment by LightFire53** [comment] 2021-05-24 19:33
Medbay has a total of 2 NanoMed+, one in medical supplies room and one in a hallway.

**Comment by S34NW** [comment] 2021-05-24 19:33
![image](https://user-images.githubusercontent.com/12197162/119398318-4f52a300-bccf-11eb-870f-994adc01fd82.png)
toxins doppler array is pointing the wrong way

**Comment by S34NW** [comment] 2021-05-24 19:34
![image](https://user-images.githubusercontent.com/12197162/119398427-6f826200-bccf-11eb-8521-e20fa913bcdb.png)
experimentor needs rfloors

**Comment by S34NW** [comment] 2021-05-24 19:35
![image](https://user-images.githubusercontent.com/12197162/119398457-7c06ba80-bccf-11eb-9b48-52bdb938273b.png)
xenobio kill room also needs a siphon vent, not two blow vents

**Comment by LightFire53** [comment] 2021-05-24 19:35
NT Rep gets a Central Command stamp, not the NT Rep stamp.

**Comment by E-MonaRhg** [comment] 2021-05-24 19:35
This might be because I'm used to box/Cyberiad but this cloning room seems to lack a cryo cell and the space is generally not really well used
![image](https://user-images.githubusercontent.com/71735193/119398411-cbe97f80-bcd7-11eb-9873-64675872ac06.png)

**Comment by S34NW** [comment] 2021-05-24 19:41
![image](https://user-images.githubusercontent.com/12197162/119399072-57f7a900-bcd0-11eb-9d34-0be56196dd28.png)
both chem fridges are public with no ID lock or windoor

**Comment by S34NW** [comment] 2021-05-24 19:42
There is only one spare science clothing locker, and none at all for robotics

**Comment by LightFire53** [comment] 2021-05-24 19:44
SM engine in atmospherics does not have a monitoring computer.

**Comment by Deelite34** [comment] 2021-05-24 19:46
![image](https://user-images.githubusercontent.com/35972878/119399493-423ab180-bcd9-11eb-93df-b8842fe7c5fd.png)
^north side and no button(ignore lack of airlock, was done by crew)

![image](https://user-images.githubusercontent.com/35972878/119399301-043d8d80-bcd9-11eb-86f2-99b2affa22c5.png)
^ south side and no button
Tesla/SM area, south side airlock from engine side. There's no button either here, or from north side, but it might be related to tesla destroying not only wires, but buttons too, still worth ensuring buttons are actually there

If buttons are there at starting point, then #16073 should fix this.

**Comment by S34NW** [comment] 2021-05-24 19:46
![image](https://user-images.githubusercontent.com/12197162/119399655-0d2a6100-bcd1-11eb-8e69-14ce9f1c79ad.png)
the status display in the northern most escape pod doesn't work

**Comment by michaelyesok** [comment] 2021-05-24 19:48
hmmm yes two brig bays.
![image](https://user-images.githubusercontent.com/84622738/119399891-becd9000-bcd9-11eb-905f-97b22870cf4b.png)

**Comment by S34NW** [comment] 2021-05-24 19:49
![image](https://user-images.githubusercontent.com/12197162/119400018-80cc6e00-bcd1-11eb-8259-969f3baacb32.png)

the vault starts with a stethoscope

**Comment by S34NW** [comment] 2021-05-24 19:51
![image](https://user-images.githubusercontent.com/12197162/119400191-b6715700-bcd1-11eb-8b80-b2384e809c34.png)
abandoned robotics lab is called "medical research" and doesn't start wired to the grid (last bit might be intentional)

**Comment by E-MonaRhg** [comment] 2021-05-24 19:51
Cant find/there is no spot for the gamma armory to dock at

**Comment by S34NW** [comment] 2021-05-24 19:53
This maint room is confusing

![image](https://user-images.githubusercontent.com/12197162/119400405-0bad6880-bcd2-11eb-9dbe-d5e25518dc63.png)

**Comment by dearmochi** [comment] 2021-05-24 19:53
Contractor extraction zones are not defined for Delta. In fact the system should be refactored to support map rotation

**Comment by michaelyesok** [comment] 2021-05-24 19:54
Coroner seems to have no locker.
![image](https://user-images.githubusercontent.com/84622738/119400461-824e6400-bcda-11eb-8bf3-bf079b3c0187.png)

**Comment by S34NW** [comment] 2021-05-24 19:54
> 
> 
> Cant find/there is no spot for the gamma armory to dock at

There is currently a PR up to fix the brig, if accepted #15405

**Comment by E-MonaRhg** [comment] 2021-05-24 19:54
There is no stick to place a target on in the firing range

![image](https://user-images.githubusercontent.com/71735193/119400539-a0b45f80-bcda-11eb-8c1a-faa9da2f6d5f.png)

**Comment by LightFire53** [comment] 2021-05-24 19:57
Security Camera Consoles don't work.
![image](https://user-images.githubusercontent.com/16112919/119400846-915bf480-bc8f-11eb-8481-754e1d17d22e.png)

**Comment by S34NW** [comment] 2021-05-24 19:58
While not an issue per se, these floors need to be not like this:

![image](https://user-images.githubusercontent.com/12197162/119400738-81b1cf80-bcd2-11eb-9cc6-cf1b2bbaf51c.png)

**Comment by S34NW** [comment] 2021-05-24 19:59
![image](https://user-images.githubusercontent.com/12197162/119401003-cfc6d300-bcd2-11eb-9610-731c9d11d9e1.png)
Departure maint is labelled "Arrivals north" due to map areas being box-centric and not cardinal based

**Comment by LightFire53** [comment] 2021-05-24 19:59
![image](https://user-images.githubusercontent.com/16112919/119401093-e3047f00-bc8f-11eb-94a2-ed41fa37ba7a.png)
Science floors are receiving multiple complaints regarding colouring/pattern.

**Comment by E-MonaRhg** [comment] 2021-05-24 20:00
There are no anti-hobo blast doors on the bridge 
![image](https://user-images.githubusercontent.com/71735193/119401149-67c8ba80-bcdb-11eb-81f8-38cc401e8de4.png)

**Comment by S34NW** [comment] 2021-05-24 20:00
![image](https://user-images.githubusercontent.com/12197162/119401185-0f8dba80-bcd3-11eb-9179-6f215dad2509.png)

These doors in arrivals aren't bolted, alowing anyone to space themselves

**Comment by SabreML** [comment] 2021-05-24 20:01
> While not an issue per se, these floors need to be not like this:
> 
> ![image](https://user-images.githubusercontent.com/12197162/119400738-81b1cf80-bcd2-11eb-9cc6-cf1b2bbaf51c.png)

They're not by default, someone painted them.

**Comment by S34NW** [comment] 2021-05-24 20:01
> 
> 
> > While not an issue per se, these floors need to be not like this:
> 
> They're not by default, someone painted them.

Pff, good catch, deleted

**Comment by SabreML** [comment] 2021-05-24 20:03
IAA office only has space for one agent
![e](https://user-images.githubusercontent.com/57483089/119401459-6c897080-bcd3-11eb-90cb-bd71b2316776.png)
Also has an 'Unknown Requests Console'.
![image](https://user-images.githubusercontent.com/57483089/119401499-7b702300-bcd3-11eb-80eb-145341fc509f.png)

And the paper bin is a regular one, not a fancy one like on box.

**Comment by michaelyesok** [comment] 2021-05-24 20:05
There are two customs offices.
One in arrivals and one in departures even though the role is long removed from paracode.
![image](https://user-images.githubusercontent.com/84622738/119401660-10771a00-bcdc-11eb-86d8-d681171419ab.png)
![image](https://user-images.githubusercontent.com/84622738/119401679-1a991880-bcdc-11eb-9cd4-93449009adde.png)

**Comment by michaelyesok** [comment] 2021-05-24 20:08
No ticket machine at the HoP's office
![image](https://user-images.githubusercontent.com/84622738/119401981-8bd8cb80-bcdc-11eb-80e6-eeab87a3e46f.png)

**Comment by LightFire53** [comment] 2021-05-24 20:08
There are no mime/clown EVA suits in EVA.

**Comment by LightFire53** [comment] 2021-05-24 20:15
Chef's kitchen also doesn't have a grill.

**Comment by michaelyesok** [comment] 2021-05-24 20:15
Atmos only gets two atmos hardsuits instead of four
![image](https://user-images.githubusercontent.com/84622738/119402667-8c259680-bcdd-11eb-98d1-8180b1a025f9.png)

**Comment by S34NW** [comment] 2021-05-24 20:16
![image](https://user-images.githubusercontent.com/12197162/119402739-44027600-bcd5-11eb-9fba-b17e1c07fa53.png)
Clown/mime combined office lacks either of their lockers or starting stuff

**Comment by S34NW** [comment] 2021-05-24 20:19
might be intended, but arrivals shuttle is made of both titanium and plastitanium, something usually reserved for syndies

![image](https://user-images.githubusercontent.com/12197162/119403050-b1160b80-bcd5-11eb-8cbf-7496c872cfce.png)

**Comment by S34NW** [comment] 2021-05-24 20:25
disposals is broken and routes items to CE office 

![image](https://user-images.githubusercontent.com/12197162/119403627-8d06fa00-bcd6-11eb-8884-7abeb55bdd33.png)

**Comment by michaelyesok** [comment] 2021-05-24 20:32
The magi has no office, Also courtroom airlocks are named Magistrate's Office..

**Comment by QuacksQ** [comment] 2021-05-24 20:48
Atmos doors also have engi acsess on them (SM ones included) This can cause numerous issues Like an inexperienced engineer causing a delamination.  Or seriously messing with the stations atmospherics.

Atmos SM also lacks Rad suits.

**Comment by AffectedArc07** [comment] 2021-05-24 21:15
![image](https://user-images.githubusercontent.com/25063394/119408419-9182e100-bcdd-11eb-90b5-f7d9b5298652.png)

**Comment by michaelyesok** [comment] 2021-05-24 21:42
uhh i dont think this is supposed to be here.
![image](https://user-images.githubusercontent.com/84622738/119410780-a5344480-bce9-11eb-8998-1690976f0c85.png)

**Comment by LightFire53** [comment] 2021-05-24 21:51
> uhh i dont think this is supposed to be here.
> ![image](https://user-images.githubusercontent.com/84622738/119410780-a5344480-bce9-11eb-8998-1690976f0c85.png)

Oh, that was me trying to get some buckshot for security since they were lamenting not having it. Unintentionally spawned the internal ones, and since they were invisible thought no one would see them

**Comment by Machofish** [comment] 2021-05-24 21:56
As above, it seems that lethal buckshot is plainly not available in the security armory. That was an extremely nasty surprise to discover, I would like that to change, please.

**Comment by S34NW** [comment] 2021-05-25 08:40
toxins mixing only has a filter, not a gas combiner as is needed

![image](https://user-images.githubusercontent.com/12197162/119467197-3385e600-bd3d-11eb-862e-bf5121a7d1d7.png)

**Comment by ZanderDoggo** [comment] 2021-05-30 01:41
This has probably been said 1000 times, but medchem needs reinforced walls

**Comment by Adrer** [comment] 2021-07-15 19:31
Top medical chemistry station does not have a fuel tank.
![image](https://user-images.githubusercontent.com/19361017/125846651-a93a484e-25b2-4596-8c50-d974a4cb9e7c.png)

**Comment by terectec** [comment] 2021-07-15 19:33
![chrome_gcKj7KLFJB](https://user-images.githubusercontent.com/53158786/125846790-6b74b400-43c2-4e7b-8800-4c18c82b2640.png)
Treatment area at medbay has no defibrillator mounts and no lights, making it very dark

**Comment by hal9000PR** [comment] 2021-07-15 19:37
![image](https://user-images.githubusercontent.com/69320440/125847198-96aac0a9-7c7f-4878-b908-71c417ef849e.png)
you cannot teleport to this teleporter directly. the beacon that is in the picture is in an area called "hallway"

**Comment by Adrer** [comment] 2021-07-15 19:37
Dorm rooms have airlocks with windows, so people can watch you sleep

![image](https://user-images.githubusercontent.com/19361017/125847211-01ab1615-17c4-40f6-98f7-7c507b903a00.png)

**Comment by hal9000PR** [comment] 2021-07-15 19:38
also I am getting a lot more lag on delta. could be because of the amount of decals

**Comment by Adrer** [comment] 2021-07-15 19:39
Virology atmos network has some above tile piping.

![image](https://user-images.githubusercontent.com/19361017/125847450-ab00d3e2-1c54-4b23-a191-57ae60704c67.png)

**Comment by hal9000PR** [comment] 2021-07-15 19:40
the safe codes in the captains office doesn't have the codes for the vault

**Comment by smokincheez** [comment] 2021-07-15 19:45
![lathe](https://user-images.githubusercontent.com/58581128/125848187-460bd9e2-c379-42d1-bbf8-92d1147412e2.JPG)
Lathe in front of science is not in range of any APC's, so it doesn't work.

**Comment by Wojz** [comment] 2021-07-15 19:46
![dreamseeker_19IjwAHpGW](https://user-images.githubusercontent.com/76156288/125848229-2083a50d-27cc-46cb-abfb-06965ec01405.png)

Oh my LORD why is this in the armory.

**Comment by AllStickyGithub** [comment] 2021-07-15 19:52
![image](https://user-images.githubusercontent.com/62549552/125848856-e4f1c062-e5dd-434f-8474-1169a7fee706.png)
I have no clue what access requirements these little cells have but the one in medical cannot be closed with normal security or CMO access.

**Comment by Wojz** [comment] 2021-07-15 20:02
![dreamseeker_Hs7sqxv1CN](https://user-images.githubusercontent.com/76156288/125850175-66933204-2419-45dc-9dfc-72309d502f6f.png)
The AI sat blast doors are called Bridge blast doors.

**Comment by Wojz** [comment] 2021-07-15 20:03
![dreamseeker_ADdNESmS5t](https://user-images.githubusercontent.com/76156288/125850262-a4eedb95-cab1-4a9a-abbd-7884c6b868c9.png)
AI sat blast doors are bridge blast doors apparently.

**Comment by Adrer** [comment] 2021-07-15 20:10
> ![lathe](https://user-images.githubusercontent.com/58581128/125848187-460bd9e2-c379-42d1-bbf8-92d1147412e2.JPG)
> Lathe in front of science is not in range of any APC's, so it doesn't work.

Pretty sure it is mapped within a station area, so might've just been your UI not working

**Comment by S34NW** [comment] 2021-07-15 20:33
![image](https://user-images.githubusercontent.com/12197162/125853685-71e0c508-0ea6-4bc9-90f4-8ff2d6463bd7.png)
this area of the permabrig has no lights at roundstart

**Comment by S34NW** [comment] 2021-07-15 20:33
there is a redundant flasher button here at roundstart
![image](https://user-images.githubusercontent.com/12197162/125853759-02279ee0-8608-43f4-9e2c-96b1201bb462.png)

**Comment by S34NW** [comment] 2021-07-15 20:35
there is no key to the secway at roundstart.

armoury does not start with any lethal ammunition.

**Comment by S34NW** [comment] 2021-07-15 20:37
![image](https://user-images.githubusercontent.com/12197162/125854227-704a7c6e-fc45-46cf-95b7-fbbdab813d38.png)
this central window has two glass on top of each other

**Comment by S34NW** [comment] 2021-07-15 20:39
If you'll pardon the mess caused by a drake invasion, the gulag and mining shuttles kiss

![image](https://user-images.githubusercontent.com/12197162/125854423-1bbae342-750e-4522-9bca-4317b48022a2.png)

**Comment by PeppermintEclipse** [comment] 2021-07-15 22:56
Going to bet this is working as intended, but I noticed during the Delta round earlier that the ghost spawn for observing players seems to be the hallway above bridge instead of a seat in the arrivals shuttle. Figured I'd mention it just because it's different from Box (though honestly, I think ghosts spawning at the center of the station instead of the edge is an improvement).

**Comment by Mitchs98** [comment] 2021-08-06 21:41
![dreamseeker_q4YGI3eZ7o](https://user-images.githubusercontent.com/12178527/128573784-1b823220-c0f1-49c0-b3ba-80802868c22a.png)
![dreamseeker_GOs23NWT8F](https://user-images.githubusercontent.com/12178527/128573797-281062df-2245-4d34-ae1c-d3b38642665a.png)
![dreamseeker_w7TiXNR1E3](https://user-images.githubusercontent.com/12178527/128573802-b97ba8d9-8856-4981-a0ce-60827ce12bc2.png)

First two buttons and the top right button don't actually open medbays doors. The first is at the front desk, the second above the doors themselves. The one that DOES actually open medbay front doors is the one on the wall across the security checkpoint below the top right button that doesn't work.

Unsure if this was fixed in Seans latest batch of fixes or not.

**Comment by tsp01** [comment] 2021-08-06 23:41
I don't have a screenshot but there didn't appear to be a control panel for the AI sat foyer turrets(the room just below the AI core).

**Comment by hal9000PR** [comment] 2021-08-10 19:30
![image](https://user-images.githubusercontent.com/69320440/128923163-d7e67d5e-4d8c-42db-83ee-3c1bf0b413db.png)
you cannot reach this keycard swiper without standing on the table

**Comment by Herder05** [comment] 2021-08-10 19:31
Medbay doesnt have any radiation suits so genetics has to go bother engineering for a rad suit or if med is dealing with a severe case of rads (engine going boom) they are also screwed

**Comment by RadiantFlash7** [comment] 2021-08-10 21:19
Not a bug, But Medbay is severely lacking in disposals bins in the normal areas.

**Closed** 2021-08-10 22:42 UTC
Labels: DeltaStation
