### ISSUE TITLE
Opening a morgue tray with the gravity generator off sends the tray across the room

### ISSUE THREAD

**Issue by ProcessedSpecimen** [ParadiseSS13/Paradise#7548] opened 2017-06-13 23:02 UTC
**Problem Description**:
When you open a morgue tray with the gravity generator off the tray flys across the room, seems strange as the tray should be attatched. When the container is clicked again the tray teleports back inside.
![ss13](https://user-images.githubusercontent.com/6432309/27108372-ba8faaa6-5094-11e7-8281-315c3c09df63.png)

**Comment by taukausanake** [comment] 2017-06-13 23:08
Duplicate of #2540 and #7129. It's Working As Intended™

**Closed** 2017-06-13 23:16 UTC
