### ISSUE TITLE
Tarot cards disappear once placed into pocket from backpack

### ISSUE THREAD

**Issue by Jackal-boop** [ParadiseSS13/Paradise#17401] opened 2022-02-14 12:50 UTC
**Problem Description**:
Clicking and dragging a deck of tarot cards from the backpack into your pockets seemingly deletes them. After ahelping after thjd occured,the admin said they could still see the cards on my person,but only I couldn't

**What did you expect to happen**: 
The expected behavior of dragging from the backpack to the pocket is for the item to be transfered to the pocket slot 

**What happened instead**:
The item seemingly dissapared

**Why is this bad/What are the consequences:**
Losing a item you were going to use

**Steps to reproduce the problem**:
Start round with a deck of tarot cards, then click and  drag them from the backpack to your pocket

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.:
It was secret with a vamp antagonist if I recall correctly

**Comment by MarcellusPye** [comment] 2022-02-15 01:18
Duplicate of #12774 and #12193.

I'll try and work on this.

**Comment by matttheficus** [comment] 2022-06-21 15:53
Duplicate.

**Closed by matttheficus** 2022-06-21 15:53 UTC
Labels: Bug, Duplicate
