### ISSUE TITLE
Captain's Office Maint isn't Shielded from Radiation Storms

### ISSUE THREAD

**Issue by DaveKorhal** [ParadiseSS13/Paradise#13097] opened 2020-03-09 20:47 UTC
**Issue Description**:

The small maintenance tunnel by the Captain's office isn't shielded from radiation storms.

**What did you expect to happen**: 

It would be shielded from radiation storms.

**What happened instead**:

It wasn't shielded and the Captain got irradiated.

**Why is this bad/What are the consequences**:

The warning explicitly says to take shelter in the Maintenance tunnels, yet the Captain's Maint tunnel isn't safe for some reason. It's confusing and once the Captain realizes his mistake, it's hard to run to an actually shielded area.

**Steps to reproduce the problem**:

1. Radiation storm event.
2. Take cover in Captain's Office Maintenance.

**When did the problem start happening**:

**Extra information**:

**Comment by datlo** [comment] 2020-03-09 20:52
duplicate of https://github.com/ParadiseSS13/Paradise/issues/10309 that has been fixed in https://github.com/ParadiseSS13/Paradise/pull/10323
This is working as intended

**Comment by Citinited** [comment] 2020-03-09 23:26
Yeah, it's not a maintenance corridor at all

**Comment by AffectedArc07** [comment] 2020-10-18 09:07
Not an issue

**Closed by AffectedArc07** 2020-10-18 09:07 UTC
