### ISSUE TITLE
Xenobiology Camera Bug

### ISSUE THREAD

**Issue by remiliaxflandre** [ParadiseSS13/Paradise#8395] opened 2017-11-25 10:19 UTC
**Problem Description**:
Cameras in xenobiology can see into the secret rooms on the left, when you hear footsteps through the walls, using the console you can put the cursor over a wall, and see on both sides of it including the left side with empty rooms. I hear someone walking or welding the walls down, i know i can go look at it. This shouldn't be possible.

https://prnt.sc/hezyqb

**What did you expect to happen**: 
Cameras aren't on that side, should only be able to see inside xenobio

**What happened instead**:
You can see on the other side of the wall using the console's camera

**Why is this bad/What are the consequences:**
Unfair advantage, I can see people breaking into these rooms for computers/ID's every game.

**Steps to reproduce the problem**:
Generally speaking its always possible, just hold left while inside a slime pen and you'll enter the wall, on that wall you can see both sides of the pen, including the rooms on the left. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing out of the ordinary, can do it every game.

**Comment by taukausanake** [comment] 2017-11-25 21:42
I thought that was fixed with the revert revert PR. Guess it was missed

**Comment by tigercat2000** [comment] 2017-11-26 23:43
These are locked to the xenobio area, I'm guessing that the problem here is that the walls are coated in xenobio instead of maint, letting the camera traverse onto them.

**Comment by Fox-McCloud** [comment] 2017-11-27 01:20
Yeah, this isn't an issue; this is due to how areas work--the standard is that walls are part of the room's area instead of maint's area.

This is here to stay.

**Closed by Fox-McCloud** 2017-11-27 01:20 UTC

**Comment by taukausanake** [comment] 2017-11-27 03:03
You mean it's Working as Intended and Won't Fix because of it. It's still kind of an issue, you shouldn't have visibility into those rooms. Is there a big reason why the walls have to be XenoBio area?
