### ISSUE TITLE
Throwing weapons broken

### ISSUE THREAD

**Issue by dexofan23** [ParadiseSS13/Paradise#7761] opened 2017-07-12 03:43 UTC
**Problem Description**:
Throwing weapons broken (rockets, pie launcher)

**What did you expect to happen**: 
The rocket must fly away

**What happened instead**:
The rocket appears below me and I can pick it up, but I can not throw it

**Why is this bad/What are the consequences:**
Because it broke mech rocket launchers

**Steps to reproduce the problem**:
Try use mech rocket launchers or hand rocket launcher

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Nothing

**Comment by Fox-McCloud** [comment] 2017-07-12 03:44
Terrible Issue name.

Please try to name something more accurately in the future so you don't convince everyone that the throwing of all objects is "broken".

**Comment by tigercat2000** [comment] 2017-07-12 03:45
Duplicate of #7575

**Closed by tigercat2000** 2017-07-12 03:45 UTC
