### ISSUE TITLE
Death nettles not working as intended

### ISSUE THREAD

**Issue by Matt1311** [ParadiseSS13/Paradise#12562] opened 2019-10-11 22:48 UTC
**Issue Description**:
Death Nettles arent getting harvested with their chems in them they are just empty

**What did you expect to happen**: 
I expected them to have chems inside of them

**What happened instead**:
They had no chems upon harvest

**Why is this bad/What are the consequences**:
You cant make death nettles that inject poisons

**Steps to reproduce the problem**:
grow a death nettle and scan it with the plant analyzer to see that it has no chems

**When did the problem start happening**:
I noticed it today no idea how long it has been like this

**Comment by DGamerL** [comment] 2023-11-09 12:16
Duplicate of #18751

**Closed by DGamerL** 2023-11-09 12:16 UTC
Labels: Inconsistency
