### ISSUE TITLE
Having an abductor organ removed does not remove the objective

### ISSUE THREAD

**Issue by KittyNoodle** [ParadiseSS13/Paradise#18572] opened 2022-07-26 05:08 UTC
**Issue Description**:

**What did you expect to happen**: 

The objective and antag status being removed

**What happened instead**:

You remain an antag

**Why is this bad/What are the consequences**:

Having to deal with someone with the objective: 
You must escape the station! Get the shuttle called!
or
Steal all organs.
Is probably supposed to be stopped by removing the organs

**Steps to reproduce the problem**:

Do the regular abduction things to a person(give the organ, put them in the chamber in the upper left corner on the ship) remove the organ.
Observe lack of antag status removal

**When did the problem start happening**:

Probably when abductors were first introduced

**Extra information**:

**Comment by Sirryan2002** [comment] 2022-07-26 05:10
I'm not sure if this is working as intended or is an actual bug, needs to be verified by designers

**Comment by FloFluoro** [comment] 2022-07-26 07:30
I can't find anything in Abductor code (`abduction.dm`, `gland.dm`, `abductee_objectives.dm`) indicating that abductee objectives are intended to be removed once the implanted organ is removed, which leads me to believe the objectives were meant to be permanent.

The automated message for Abductors winning their gamemode reads as follows:
`Large amount of abnormal thought patterns detected. All crew are recalled for mandatory evaluation and reconditioning.`

I'm pretty sure that the bizarre abductee objectives and implication of mental abnormality are meant to play on the sci-fi trope of alien abductees being returned to earth with brain damage and/or paranoia that makes them look insane. From an IC perspective, there are plenty of reasons why removing an organ embedded in someone's chest wouldn't fix whatever Abductors might've done to their brain.

From an OOC perspective, I'd rather we not go down a path that encourages security to preemptively bring abductees to medbay for "de-antagification".

**Comment by Inadvizable** [comment] 2022-07-26 18:29
One of the messages, I believe, is "Your mind snaps!" Someone would have to verify this but I'm pretty sure I'm right. 

Probably not caused by the organ. Rather the testing procedure.

**Comment by GDNgit** [comment] 2022-07-27 04:07
> One of the messages, I believe, is "Your mind snaps!" Someone would have to verify this but I'm pretty sure I'm right.
> 
> Probably not caused by the organ. Rather the testing procedure.

This is used for the abductors beam in message (aka after being experimented on usin the machine). 

Codewise there's 0 indication this is the case, and this is more of a feature request if anything

**Comment by Sirryan2002** [comment] 2022-07-27 04:23
Confirmed by the Author of the PR which ported abductor to Paradise that this is 100% intended behavior. Closing as not a bug/issue

**Closed by Sirryan2002** 2022-07-27 04:23 UTC
Labels: Need Verification
