### ISSUE TITLE
Slimes vaporized by single pipe tile area in space when ventcrawling.

### ISSUE THREAD

**Issue by ATP-Engineer** [ParadiseSS13/Paradise#20589] opened 2023-03-07 22:49 UTC
**Issue Description**:

Farragus ventcrawling bug. (Atmos related?)
Total slime death when trying to traverse the vent pipe located on this tile my ghost is visible on near engineering.
Pictures related.
![image](https://user-images.githubusercontent.com/120416457/223571512-3eb5df03-14e7-4413-989a-6cca0f373147.png)
![image](https://user-images.githubusercontent.com/120416457/223571532-47a2d849-89d6-4851-ae8f-a0bab9dc352d.png)

**What did you expect to happen**: 

Uncontested movement even through space pipe systems, as is possible with all other ventcrawling mobs and vent areas, seeing as the pipe is ordinary, and even the other sections in space don't cause this.

**What happened instead**:

Frozen in place after landing on that tiles pipe, slowly dying, splitting into multiple slimes because I was evolved, and then dying.

**Why is this bad/What are the consequences**:

Any sentient xenobio slimes, or anomaly-created slimes can have their game cut short in an instant by this unknown force or oversight in map design.

**Steps to reproduce the problem**:

Spawn as a xenobio or anomaly slime, evolve, ventcrawl at kitchen, traverse to space pipe through maintenance east of kitchen by going north of botany maintenance, go through the space pipe until you hit that tile, and die a unreasonable, and hard to explain slow death while unable to do anything.

**When did the problem start happening**:

Happened once when I was a sentient event slime, was just traversing pipes, assumed it was just atmos nuking vents or something with that specific area, but then it happened a second time when an anomaly went nuclear and I won the slime roll.

**Extra information**:

Besides what already is mentioned, you are frozen apon hitting the tile, and slowly die by what can be assumed is pressure/atmos stuck on that one tile. It is not apparent what force causes this.

**Comment by Contrabang** [comment] 2023-03-08 00:50
![image](https://user-images.githubusercontent.com/91113370/223590374-b0a3d87e-5f79-49c3-8c6e-13e88075ce3c.png)
Reproduced with any pipes going through space, it just randomly stops you. I'm guessing this is a whole "slimes cold and they die thing". Although, the temperature probably shouldn't be transferred through the pipe

**Comment by Komrad822** [comment] 2023-03-08 20:25
Can you go to those pipe sections with an analyzer and see what it says about the gas in those sections? In now way should the outside be influencing those specific pipes as stated earlier.

**Comment by Contrabang** [comment] 2023-03-09 18:48
> Can you go to those pipe sections with an analyzer and see what it says about the gas in those sections? In now way should the outside be influencing those specific pipes as stated earlier.

From what I can tell, the gas inside the pipes is not being affected. The problem is that the slime is getting its environment tempereature from the gas thats outside in space

**Comment by Pennwick** [comment] 2023-03-12 16:13
This feels like its still a bug, just not whats being reported. The actual issue is that some mobs seem to survive or die based on the atmos of the tile they're occupying instead of the pipe they're in if ventcrawling.

**Comment by Contrabang** [comment] 2023-03-12 18:27
> This feels like its still a bug, just not whats being reported. The actual issue is that some mobs seem to survive or die based on the atmos of the tile they're occupying instead of the pipe they're in if ventcrawling.

Yeah, I agree with this, this is the most likely cause of it

**Closed** 2023-03-24 20:42 UTC
Labels: Bug
