### ISSUE TITLE
Changeling hivemind is left in the body if the changling brain is removed

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#16216] opened 2021-06-19 22:15 UTC
**Issue Description**:

Changeling hivemind is left in the body if the changeling brain is removed

**What did you expect to happen**: 

For the langage to be tied to the mind / brain, and move with it

**What happened instead**:

If the brain of a changeling is removed, and another persons brain is put in the body, that person can hear and speak on the changeling hivemind

**Why is this bad/What are the consequences**:

Hivemind is supposed to be cling only, crew being able to listen into it is not good.

**Steps to reproduce the problem**:

Debrain a changling after killing them
Insert brain of someone else.
Revive body.
Listen to the song of my people.

**Comment by matttheficus** [comment] 2022-06-21 18:19
Duplicate of #15430

**Closed** 2022-06-21 18:19 UTC
Labels: Duplicate
