### ISSUE TITLE
Attacking people with a welder does no damage

### ISSUE THREAD

**Issue by mrturkeytoe** [ParadiseSS13/Paradise#5491] opened 2016-08-18 21:32 UTC
**Problem Description**:
What is the problem?
Attacking people with a activated welding tool appears to at times do no damage.
**What did you expect to happen**: 
Why do you think this is a bug?
The welder has done burn damage in the past and is, you know, hot.
**What happened instead**:
How is what happened different from what you expected?
The person took no damage but consumed welding fuel as they were harmlessly whapped with a flaming, hot, welder.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
If someone is getting toolboxed and tries to fight back with a welder they could be screwed.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
I am not sure what causes it but I think it might be the industrial welding too only.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by IcyV** [comment] 2016-08-18 22:28
When off it does 3 brute, when on it does 15 burn. I just tested it a bunch and it seems to be doing the proper damage just fine. I'm not able to reproduce this at all. Tried it with both the normal and industrial welder. Any other factors that come to mind?

**Comment by mrturkeytoe** [comment] 2016-08-20 17:34
I saw it happen one round where a borg was trying to attack someone using a industrial welder and it didn't do any damage and one round I had a industrial welder and tried to hit someone with it while it was on and it did no damage.

**Comment by Davdichan** [comment] 2016-08-20 20:19
@mrturkeytoe  Was by chance your intent on help (green), as this would have beyond believe you're attempting to repair a robotic limb.

Also did you see what the chat log said while attempting to attack them?

**Comment by Fox-McCloud** [comment] 2016-09-11 21:44
Not been able to reproduce this. Closing.

**Closed by Fox-McCloud** 2016-09-11 21:44 UTC
Labels: Cannot Reproduce
