### ISSUE TITLE
Large grenade disappears in backpack

### ISSUE THREAD

**Issue by florkeger** [ParadiseSS13/Paradise#11877] opened 2019-07-17 19:34 UTC
**Problem Description**:
When you put a large grenade (after you screwdriver it close) into your satchel/backpack, it disappears completely alongside its contents.

**What did you expect to happen**: 
The item to not disappear, obviously.

**What happened instead**:
It just vanishes out of existance.

**Why is this bad/What are the consequences:**
Because it destroys your efforts entirely.

**Steps to reproduce the problem**:

1. Take a lage grenade casing from the Protolathe.
2. Build the grenade with two large beakers.
3. Put it into your backpack.
4. Get frustrated.

**When did the problem start happening**:
No idea.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Nothing really. I just noticed it happening twice when I built large grenades as a Chemist.

**Comment by SteelSlayer** [comment] 2019-07-20 01:25
I'm not able to reproduce this. Any other info you can give us, like the specific backpack you were using?

**Comment by Kyep** [comment] 2020-09-27 04:46
@AffectedArc07 Tested this on live, cannot reproduce, suggest closing.

**Closed** 2020-09-27 07:40 UTC
