### ISSUE TITLE
Crates are broken

### ISSUE THREAD

**Issue by Denthamos** [ParadiseSS13/Paradise#7981] opened 2017-08-14 00:24 UTC
**Problem Description**:
Any crate in the game right now is broken.  You cannot put any items inside crates by clicking the item on them, nor can you use cargo RCS to teleport crates

**What did you expect to happen**: 
For crates to work like lockers in terms or putting items in them and using the RCS on them.

**What happened instead**:
You cannot interact an RCS with crates or put items in them

**Why is this bad/What are the consequences:**
It makes cargo REALLY annoying to do when you are stamping manifests to send them back and loading stuff into crates, or teleporting crates from maint to cargo.

This also nerfs traitor cargo techs/qm as they cannot easily RCS the crates to a hidden cargo telepad.

**Steps to reproduce the problem**:
Try putting an item in a crate by using it on the crate or using an RCS on a closed crate.

**Comment by SirBloodBuske** [comment] 2017-08-14 01:33
duplicated, been this way a few days. annouyinggggg

**Comment by tigercat2000** [comment] 2017-08-14 02:57
Duplicate of #7960

**Closed by tigercat2000** 2017-08-14 02:57 UTC
