### ISSUE TITLE
Performing Organic Head Replacement Surgery on IPCs stops any head replacement on them in future.

### ISSUE THREAD

**Issue by Taaketa** [ParadiseSS13/Paradise#5499] opened 2016-08-19 14:46 UTC
**Problem Description**:
What is the problem?

Performing organic head replacement surgery on an IPC stops IPCs from getting their head replaced at all, even through regular surgery.

**What did you expect to happen**: 
Why do you think this is a bug?

Organic surgery shouldn't work at all.

**What happened instead**:
How is what happened different from what you expected?

Someone trying organic surgery on an IPC shouldn't even be able to get started.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

Probably not really. Considering the endless list of things that IPCs end up having broke.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Perform organic head replacement using regular surgical tools. Stop procedure and try to do with mechanical tools.

**Comment by Crazylemon64** [comment] 2016-08-19 19:12
HOW?
https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/surgery/limb_reattach.dm#L35-L37

**Comment by Crazylemon64** [comment] 2016-08-19 19:18
Did you start a synthetic limb re-attachment, then try to put an organic limb in its place? You can stop the surgery just by clicking it with a screwdriver, like any other.

**Comment by Crazylemon64** [comment] 2016-08-19 19:21
Well, one way or the other, I'm not able to reproduce this. Could you please give details on how exactly you started this surgery?

**Comment by Crazylemon64** [comment] 2016-08-19 19:22
And right now, IPC head replacement is broken - the patch has been merged, but the server's not been updated yet.

**Comment by Taaketa** [comment] 2016-08-20 01:26
Not sure. I was the subject getting the head re-attachment. The guy kept insisting that he was doing it right. Then I asked him via LOOC was he using a screw driver. Which he said he wasn't. So I assume he was using surgical tools. I could not see.

Anyway, point is, after he tried to put the head back on, no one else could.

**Comment by Crazylemon64** [comment] 2016-08-20 04:22
Head replacement is broken right now but it's patched just wait a little and it'll work then

**Closed** 2016-08-20 04:51 UTC
Labels: Cannot Reproduce
