### ISSUE TITLE
Viral Injector Bugged

### ISSUE THREAD

**Issue by UltraCraftGames** [ParadiseSS13/Paradise#16638] opened 2021-09-05 17:08 UTC
**Issue Description**:When i used the viral injector it said it stealthily injects the person however no fluid is drained from it and it just attempts to drip into their eyes like a normal pipette.

**What did you expect to happen**: For it to inject the fluid into the person without them knowing when i use it on them.

**What happened instead**:It just said a message saying it stealthily injected something without actually injecting anything and attempting to drip in their eyes.

**Why is this bad/What are the consequences**:It makes the item lose its main purpose.

**Steps to reproduce the problem**:I had bought the virus injector from the uplink then filled the pipette with a virus culture of brainrot (though other cultures did the same) and when i tried to inject someone with it (i was targeting the chest and it does the same thing on any intent) the bug occured

**When did the problem start happening**:Today though i have not used it before.

**Extra information**:I only tried virus culture bottles on it.

**Comment by Exavere** [comment] 2021-09-22 00:54
I've tried re-create this issue and it seems to work just fine, the pipette stealth stabs the targets as intended with no eye dripping attempted.  May of been fixed by another PR but for now it seems to work just fine.

**Comment by Sirryan2002** [comment] 2022-07-13 17:05
cannot reproduce this issue

**Closed by Sirryan2002** 2022-07-13 17:05 UTC
Labels: Bug, Cannot Reproduce
