### ISSUE TITLE
Maint Drone Table Generation

### ISSUE THREAD

**Issue by NTSAM** [ParadiseSS13/Paradise#2547] opened 2015-11-15 01:51 UTC
As a maintenance drone, it's possible to generate tables out of nowhere.

How to reproduce:
Pick up a table part set with your gripper.
Place table by using the gripper.
Keep using the gripper, you'll generate tables out of nowhere.

**Comment by Spacemanspark** [comment] 2015-11-15 02:26
I swear this was already reported.

**Comment by Crazylemon64** [comment] 2015-11-15 03:04
*ping*
#2368

**Comment by TheDZD** [comment] 2015-11-15 03:15
As @Crazylemon64 pointed out, duplicate of #2368.

**Closed by TheDZD** 2015-11-15 03:15 UTC
Labels: Bug, Duplicate

**Comment by NTSAM** [comment] 2015-11-15 06:12
oh
