### ISSUE TITLE
Steal Objective Bug

### ISSUE THREAD

**Issue by TheDZD** [ParadiseSS13/Paradise#2150] opened 2015-09-23 20:09 UTC
For some reason, traitors often get the base datum/objective/steal objective, instead of one of its subtypes, resulting in them getting an objective that just says "Steal ."

**Comment by Markolie** [comment] 2015-09-24 02:36
Duplicate of https://github.com/ParadiseSS13/Paradise/issues/1815.

**Closed by Markolie** 2015-09-24 02:36 UTC
Labels: Bug
