### ISSUE TITLE
Detective revolver barrel reinforcing won't happen anymore

### ISSUE THREAD

**Issue by xXx-RegularJoe-xXx** [ParadiseSS13/Paradise#13010] opened 2020-02-20 22:16 UTC
**Issue description**
You can't reinforce the detective gun's barrel anymore to take the .357 ammo, or vice versa.

**What did you expect to happen**: 
Lethal .357 noir action after applying screwdiver to the gun. 

**What happened instead**:
Only screwdiver action sound played, nothing else happened - no matter what was the gun's state.

**Why is this bad/What are the consequences**:
Nukies and other lethal threats to the detective got to taste gummi bullets until it's fixed.

**Steps to reproduce the problem**:
Be detective, take the gun, use the screwdiver on it. No danger of blowing it your face either. 

**When did the problem start happening**:
Became aware via a mhelp 21.2.20. Tested locally after the round in question to confirm it. I guess it is due the tool refactor #11700.

**Extra information**:
Looked to the code at revolver.dm, these might be the lines failing:
```
/obj/item/gun/projectile/revolver/detective/attackby(obj/item/A, mob/user, params)
	if(istype(A, /obj/item/screwdriver))
```

**Comment by FlattestGuitar** [comment] 2020-02-20 22:48
This is intended behavior. 

The rubber bullets are total bullshit overpowered and only a fool would hinder themselves by using .357 

pew, crack and whack

**Comment by xXx-RegularJoe-xXx** [comment] 2020-02-20 23:56
Not that I don't agree, honk

**Comment by Citinited** [comment] 2020-02-21 23:48
I'm working on a fix for this.

Offending behaviour was that the `obj/item/gun` has a `screwdriver_act()`, but the detective revolver doesn't (it's done in the attackby, which is bypassed)

**Closed** 2020-02-25 00:45 UTC
