### ISSUE TITLE
Grill not cooking recipes involving metal rods correctly

### ISSUE THREAD

**Issue by gbadillo** [ParadiseSS13/Paradise#14693] opened 2020-10-22 03:53 UTC
**Issue Description**: To keep it brief many of the food recipes involving metal rods were not working properly on the grill. It seems as if the grill is accidentally duplicating metal rods as ingredients or not properly removing them during the cooking process. 

**What did you expect to happen**: I expected that when I attempted to cook a kabob recipe (IE: 2 meats and 1 rod or 2 tofu and 1 rod) to be able to cook kabobs.

**What happened instead**: In an infrequent basis the grill would either burn the food, duplicate the metal rods while attempting to cook, or work accurately. The issue didn't seem consistent in behavior as there were times when I could cook the kabobs and times when I couldn't. The main evidence of this mistake was that after cooking a successful kabob I would see 1-2 metal rods still be on the grill. There were even times where after a failed kabob attempt that broke the grill after I repaired it again I would see 1-2 metal rods left over.

**Why is this bad/What are the consequences**: Main consequences are that recipes involving metal rods will not work correctly and thus limit food options.

**Steps to reproduce the problem**: 
1. Place 2 meats/2 tofu and 1 metal rod into grill
2. Cook the ingredients
3. See what of 3 potential options happen
    option a: The recipe works (though occasionally has leftover rod ingredients on the grill)
    option b: The recipe fails and breaks the oven creating a burned mess (at this point repair the grill and notice there are still leftover rods in a 1-2 quantity)

**When did the problem start happening**: Noticed it occurring on Oct. 21 around the 8 pm Central Time shift (not sure what time zone for person reading this)

**Extra information**: I advise testing it yourself to see in action.

**Comment by Burzah** [comment] 2023-08-21 02:03
Tested this today, could not reproduce. The only way I could see something happening like this now, is if attempting to make kabobs with meat that was not from a recipe. This would include using any meat besides human, synth, monkey, or even tofu. Using any other than those listed on the wiki will not produce a kabob. Even when testing with different types of usable and non-usable meat I was not able to duplicate any metal rods.

**Comment by Henri215** [comment] 2023-08-21 13:04
I failed to replicate this issue in the past too.

**Comment by DGamerL** [comment] 2023-11-09 10:26
Three people couldn't replicate this, closing.
If it happens again somehow, feel free to open a new report!

**Closed by DGamerL** 2023-11-09 10:26 UTC
Labels: Bug, Cannot Reproduce
