### ISSUE TITLE
UI not showing on interactable Objects like PDA, Vending Machines and other stuff.

### ISSUE THREAD

**Issue by Maceeee** [ParadiseSS13/Paradise#2381] opened 2015-10-17 21:28 UTC
PDA, Consoles, Vending Machines and lots of different stuff dont show an UI for me when I open them.  It only happens on Paradise Station.
Upload is a screenshot showing the opened PDA. It looks the same on the other usable stuff. Only the window size differs.
![ss 2015-10-17 at 11 23 33](https://cloud.githubusercontent.com/assets/13185611/10561380/860b0fc8-7526-11e5-8286-a4edebb6a3e8.png)

**Comment by Markolie** [comment] 2015-10-17 21:52
Check if you have JavaScript enabled in Internet Explorer/Edge, and consider re-installing it. Sort of a duplicate of https://github.com/ParadiseSS13/Paradise/issues/1623.

**Closed by Markolie** 2015-10-17 21:52 UTC
Labels: Duplicate
