### ISSUE TITLE
Pipette not transferring 1u

### ISSUE THREAD

**Issue by AirwaveRaptor** [ParadiseSS13/Paradise#12753] opened 2019-11-26 07:15 UTC
**Issue Description**:
The pipette occasionally inputs 1u of a reagent/virus culture and outputs slightly less, such as 0.97846...u,

**What did you expect to happen**: 
I expected it to input and output 1u

**What happened instead**:
The pipette transferred 0.9-u

**Why is this bad/What are the consequences**:
It leads to waste and frustration regarding limited resources in virology.

**Steps to reproduce the problem**:
1. Use the pipette, transfer 1u of a virus from a culture bottle to a beaker.
2. Transfer in 1u of a reagent. Occasionally, it doesn't react. Add in a 2nd unit of each, and it will likely react twice.
or
1. Use the pipette, transfer 1u of unstable mutagen from the given mutagen bottle to a beaker. 
2. Then load the pipette with virus food and transfer it to the new beaker. This should immediately create mutagenic agar, but occasionally it won't react. If you load another 1u of mutagen and virus food, it'll react twice instantly.

**When did the problem start happening**:
11/25/19 is when I first noticed it. Today's the first day I've played in a while, but it worked perfectly a few months ago.

**Extra information**:
My ping at the time was 46ms. Also, it looks like you smack the wall with the pipette when you load virus food into it from the dispensary.

**Comment by farie82** [comment] 2019-11-26 08:19
I found this as well and only when using virus food. I think this is due to byond using floats for all numbers. Floats being numbers with decimals. But floats are also imprecise due to how they work. Prob cant fix this

**Comment by Contrabang** [comment] 2023-03-22 06:51
Duplicate of #18036. Despite this one being older, the newer one has more better information, so this one is getting closed.

**Closed by Contrabang** 2023-03-22 06:51 UTC
Labels: BYOND Issue
