### ISSUE TITLE
Buttons Missing from Top of Screen

### ISSUE THREAD

**Issue by Kaomiyo** [ParadiseSS13/Paradise#22932] opened 2023-10-17 06:40 UTC
**Issue Description**:
Buttons missing from top of screen as a pulse demon makes it a little difficult to play as.

**What did you expect to happen**: 
Buttons to be there and clickable so I don't need to click on pulse demon tab to then access my abilities and upgrades.

**What happened instead**:
Buttons were missing, and as I unlocked powers (cable hop, malfunctioning, etc) they disappeared from the top of screen.
![image](https://github.com/ParadiseSS13/Paradise/assets/142894314/ef881af1-21ff-4028-9228-ffd4b2c5f2a6)

**Why is this bad/What are the consequences**:
Not being able to use abilities without going through verbs is a little unwieldly.

**Steps to reproduce the problem**:
Spawn in as pulse demon, have no usable buttons, uplock cable hop, lose ability to click on cable hop button.

**When did the problem start happening**:
Genuinely no idea.

**Extra information**:
I could still alt + click the buttons of locked abilities to unlock them, in which case they would disappear.
Using Reload Graphics and Reload UI Resources fixed nothing
Completely restarting the client fixed nothing.

**Comment by Adrer** [comment] 2023-10-20 10:35
Bug was caused by testmerge removing several icons. Should be fixed now.

**Comment by DGamerL** [comment] 2023-10-20 10:43
As Chap said, it was indeed the result of a TM, which has luckily been identified and fixed. Thanks for making this issue report!

**Closed by DGamerL** 2023-10-20 10:43 UTC
Labels: Bug
