### ISSUE TITLE
Laptop Vendor - Redundant PIN Pop-Up

### ISSUE THREAD

**Issue by Plotron** [ParadiseSS13/Paradise#1199] opened 2015-05-28 12:56 UTC
The laptop vendor asks you to a) pick your components, b) press the 'vend' button, c) swipe your ID to confirm and d) enter your PIN.

The issue is that d) is redundant, considering that it doesn't actually check your PIN for validity - you can put in any random combination of numbers and it will still dispense the laptop. I use this thing to make the purchasing process faster, as simply putting in "1" gets rid of the pop-up - I don't have to check my IG notes for my actual PIN.

Either remove this pop-up or fix it so it WILL check whether the PIN you gave it is correct.

**Comment by Krausus** [comment] 2015-05-30 08:01
> it doesn't actually check your PIN for validity

The accounts system actually *does* check your PIN for validity, but only if you've manually increased your account's security level; if you haven't, the PIN is ignored. The problem is, the laptop vendor asks for a PIN even if your account doesn't require one - this will be fixed.

**Closed** 2015-05-30 11:00 UTC
Labels: bug
