### ISSUE TITLE
Borked pop ups

### ISSUE THREAD

**Issue by Belario** [ParadiseSS13/Paradise#2070] opened 2015-09-16 13:23 UTC
Anything with this type of pop up shows up as blank, started a few months ago, happens on every server that's not Goon but I figured this'd be the place to ask.

![untitled](https://cloud.githubusercontent.com/assets/14313169/9905692/5a2ba932-5c7e-11e5-893b-b20e7fd71ecd.png)

Affected things include PDAs, all consoles, APCs, air alarms, and all vending machines, but not autolathes for some reason.
I spoke to a mentor in game and was told it was something to do with Byond not downloading its cache properly, and that others suffered from this as well.

Anything that can be done? I've reinstalled Byond several times to no avail.

**Comment by tigercat2000** [comment] 2015-09-16 13:29
It's NanoUI, and it can bug out randomly.

**Comment by PsiOmegaDelta** [comment] 2015-09-16 13:30
The JavaScript detection in NanoUI seems a bit iffy, thus one thing you can do is manually double-check that JavaScript is enabled in **Internet Explorer** (even if you are normally using any other browser). 

Hopefully this guide will be of some help: http://www.enable-javascript.com/#ie
http://www.enable-javascript.com/#ie

**Comment by Belario** [comment] 2015-09-16 13:38
@tigercat2000 Happened occasionally since I started playing, but this last half year? every single time.

@PsiOmegaDelta I've reinstalled everything and will try that out, thanks.

**Comment by PsiOmegaDelta** [comment] 2015-09-16 13:58
You can disable Flash in IE separately without touching JavaScript (you can leave Flash in any other browsers you're using), which is what BYOND uses to run its ads.

**Comment by Markolie** [comment] 2015-09-16 16:29
Probably worth investigating to see if it it's possible to improve the error handling when JavaScript is disabled.

**Comment by Alex6511** [comment] 2015-09-16 16:30
Holy shit you found the cause. Sorry I couldn't be more help everytime you've ahelped this but I simply ran out of ideas.

**Comment by Tastyfish** [comment] 2016-04-22 00:14
Is this still a thing at all?

**Comment by TullyBurnalot** [comment] 2016-07-29 07:51
@TheDZD Most likely not relevant, could warrant a closing.

**Closed** 2016-07-30 01:12 UTC
Labels: Not a Bug
