### ISSUE TITLE
Chat sprite replaced by gibberish

### ISSUE THREAD

**Issue by lalchimi** [ParadiseSS13/Paradise#12956] opened 2020-02-04 19:14 UTC
**Issue Description**: 
    Everytime where a sprite should appear on chat, it is replaced by gibberish text.
[ > Example when examining a floor ](https://cdn.discordapp.com/attachments/488785918665424897/674330081036075029/unknown.png)

**What did you expect to happen**: 
    Having a sprite instead of gibberish text

**What happened instead**:
   Gibberish text

**Why is this bad/What are the consequences**:
   Flood chat box

**Steps to reproduce the problem**:
   Examining any object or doing anything that show a sprite on chat box

**When did the problem start happening**:
    Since 4th february

**Extra information**:
   I don't seem to be the only one to have this glitch.

**Comment by FlattestGuitar** [comment] 2020-02-04 19:27
Nice. Did you guys ever merge those replacement regexes for chat? Are you using anything like this in goonchat?

**Comment by iantine** [comment] 2020-02-04 19:52
https://puu.sh/EWiyp/cbd01aea4a.gif Here's another example, 5th January 2020. Shift clicked to examine blood on the ground, and the game lagged out due to the mass of gibberish, resulting in me examining two or three times, which produced this.

**Comment by lalchimi** [comment] 2020-02-04 19:55
in other news. Thanks to Dovixx. Disabling regex fixed the issues.

**Comment by farie82** [comment] 2020-02-07 14:40
Fixed in #12690 or #12691

**Comment by craftxbox** [comment] 2020-02-11 02:21
this is 'technically' working as intended but is fixed in #12690

**Comment by AffectedArc07** [comment] 2020-10-18 09:04
Fixed

**Closed by AffectedArc07** 2020-10-18 09:04 UTC
