### ISSUE TITLE
Cannot double click a word in chat to select it.

### ISSUE THREAD

**Issue by FlattestGuitar** [ParadiseSS13/Paradise#5094] opened 2016-07-18 17:58 UTC
This is literally how it works in every other text viewer and editor on the surface of Earth. Fix pls.

@tigercat2000 
:hocho: :gun: :bomb:

**Comment by tigercat2000** [comment] 2016-07-18 18:08
how the fuck do you think this can be anything i can control

**Comment by FlattestGuitar** [comment] 2016-07-18 18:12
[#4744](ttps://github.com/ParadiseSS13/Paradise/pull/4744)

**Comment by TheDZD** [comment] 2016-07-20 00:59
This is something that occurs on Goon as well, likely won't be fixed.

**Closed by TheDZD** 2016-07-20 00:59 UTC
Labels: Cannot/Will Not Fix

**Comment by PJB3005** [comment] 2016-07-23 22:17
Hard to fix but not impossible.

The issue is that to prevent you getting focus on your chat (and thus potentially making hotkeys less responsive), clicks instantly refocus you on the map window (the main game window).

**Comment by FlattestGuitar** [comment] 2016-07-23 22:18
One could perhaps add a 100ms cooldown on that to enable the double click...

**Comment by PJB3005** [comment] 2016-07-24 09:01
Yeah same thing I was thinking.
