### ISSUE TITLE
Chem Dispenser 5000 rounding error when emptying dispenser

### ISSUE THREAD

**Issue by Christer2222** [ParadiseSS13/Paradise#18662] opened 2022-07-31 20:30 UTC
**Issue Description**:
The energy stored in the Chem Dispenser is slightly less than the reported energy. When 20 or more energy is stored it is reported as a whole number, but is in fact 0.00...1 units less. This is more visible when 20 units is lowered to "10", as it will write the whole number (9.99...9). 

**What did you expect to happen**: 

To have the energy be a multiple of 10, or have the energy gradually increase so decimal numbers make sense.

**What happened instead**:

I got an error in chat when I tried to spend the last charge in the Chem Dispenser, despite the UI showing it would be possible.

**Why is this bad/What are the consequences**:

Its confusing to not be able to fill a beaker with the reported value.

**Steps to reproduce the problem**:

1. Put a beaker in the Chem Dispenser 5000
2. Repeatedly fill the beaker and empty it out to drain the Chem Dispenser of power.
3. At some point you should be able to empty out the last charge from the dispenser, but cant.

**When did the problem start happening**:

I encountered this first today 31.07.2022.

**Extra information**:

I am guessing the charge will be carried over when you make a machine with batteries that has partial power; if that is the case, the Chem Dispenser 5000 acts as a recharger for those batteries, and they should reach a charge of (true) 100% when the dispenser reports it being full.

![image](https://user-images.githubusercontent.com/25958019/182048091-b1033eea-5cba-41ac-aecd-903d4b6f45d7.png)

**Comment by Sirryan2002** [comment] 2022-08-01 04:25
duplicate of #18036 this is technically a different part of the UI being bitchy but it's almost exactly the same cause/issue.

**Closed by Sirryan2002** 2022-08-01 04:25 UTC
