### ISSUE TITLE
Vox *flap and *aflap don't use the proper pronoun.

### ISSUE THREAD

**Issue by fludd12** [ParadiseSS13/Paradise#3083] opened 2016-01-02 03:14 UTC
It's always 'his,' no matter if you're female or your gender is obscured by a mask or such.

**Comment by tigercat2000** [comment] 2016-01-02 03:22
not a bug and not specific to vox, it just uses 'his'

**Comment by Fox-McCloud** [comment] 2016-01-02 04:39
old emote is oldddddddddddd

**Comment by Spacemanspark** [comment] 2016-01-02 04:59
Wouldn't this be easily fixed with a \his thing?

**Comment by tigercat2000** [comment] 2016-01-02 05:01
yes, incredibly easy
but why would we fix a great mistake from nearly 3 years ago
stop trying to make me replace [my ship](https://en.wikipedia.org/wiki/Ship_of_Theseus) damnit

**Closed** 2016-01-08 20:06 UTC
Labels: Grammar and Formatting
