### ISSUE TITLE
Emotes still trigger after death

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#4827] opened 2016-06-29 22:49 UTC
certain emotes still trigger after death, don't know if this is because of the new emote system

How2reproduce:

Have a mechanical heart
Get EMP'd my singularity
Die from heart attack
Continue to clutch your chest every time you get EMP'd
Continue to stare blankly into the singularity even when you're dead

**Comment by TheDZD** [comment] 2016-06-29 23:29
Duplicate of #4821

**Closed by TheDZD** 2016-06-29 23:29 UTC
