### ISSUE TITLE
Can not write to bundle if paper was renamed

### ISSUE THREAD

**Issue by WhiteHusky** [ParadiseSS13/Paradise#5351] opened 2016-08-07 05:20 UTC
**Problem Description**:
If you write to a bundle of papers, you can write to the document if you clicked on it with a pen. However, if the paper in the bundle was renamed before being attached to the bundle, it doesn't allow you to directly write, regardless if it is in your hand or on a table.

**What did you expect to happen**: 
Window of the bundle appearing along with an additional window of the current paper with writing allowed.

**What happened instead**:
It brought up a window of the bundle but no additional window for the current paper to write to.

**Why is this bad/What are the consequences:**
Inconvenient to write to a bundle.

**Steps to reproduce the problem**:
Create a new paper, name it, copy it as many times as you like, make it into a bundle, and attempt to write to it directly.

**Comment by Ty-Omaha** [comment] 2016-08-07 09:47
Dont look at that PR :( but all cringing aside, I **was** able to reproduce this at and now I am unable to again.

**Comment by Ty-Omaha** [comment] 2016-08-07 09:58
Don't look at that PR or I will cry, but all cringing aside; during some more testing I noticed if there is at least 1 renamed paper INFRONT of the renamed paper you are trying to edit, it works.

**Comment by moxian** [comment] 2019-10-31 07:09
I could not reproduce the bug.
Took a paper out of a paper bin, renamed it, made 3 copies, combined them into a paper bundle, used pen on the bundle, got presented with write dialog, successfully committed text to paper.
Tried varying the process (adding text before the copies, combining with unnamed papers, writing not on the first page), to no avail - everything just works...

**Closed** 2020-03-07 23:50 UTC
Labels: Bug
