### ISSUE TITLE
After being handed the carded AI it didnt count as a steal the AI objective

### ISSUE THREAD

**Issue by Alantodne** [ParadiseSS13/Paradise#14179] opened 2020-08-29 04:25 UTC
**Issue Description**:
I had the AI in my bluespace belt, however it didnt count it for the objective

**What did you expect to happen**: 
Me to pass the objective with a greentext

**What happened instead**:
Redtexted with a intelicard containing the AI in my bluespace bag.

**Why is this bad/What are the consequences**:
I didnt greentext

**Steps to reproduce the problem**:
Not sure, happened at the end of the round that started at 9:48PM EDT 2/28/2020.
I had 2 intelicards. one with the AI one with no AI in it. both were in my bluespace belt, and didnt greentext at round end. I was handed the AI rather than carding it myself.

**When did the problem start happening**:
I noticed it the moment it happened.

**Extra information**:
Image of the redtext with card in belt. 
![Redtext](https://user-images.githubusercontent.com/44008012/91628483-22ff3580-e98e-11ea-89c1-364e5072c680.PNG)

**Comment by SteelSlayer** [comment] 2020-08-29 05:01
I have to ask the obvious: was the AI still alive?

**Comment by Spacemanspark** [comment] 2020-08-29 06:46
That was my question too lmao

**Comment by SteelSlayer** [comment] 2020-08-29 14:35
Yeah true. I think the issue is that the objective looks for the first intellicard in your inventory and calls the check completion proc on it. And because the first one in your bag is empty, it returns false.

**Comment by Oyu-De** [comment] 2020-08-31 06:49
> I have to ask the obvious: was the AI still alive?

I was the AI that round (JL204) and I was, indeed alive and still active in the round when it ended.

**Comment by matttheficus** [comment] 2022-06-21 21:51
Have successfully done so in the past, unsure of what this issue was then. Closing due to stale, then.

**Comment by matttheficus** [comment] 2022-06-21 22:02
Reopening after discord discussion, edgecase not tested.

https://discord.com/channels/145533722026967040/145700319819464704/988926391351377982

**Comment by Oyu07** [comment] 2024-01-24 03:40
Message from the future

Realised this is still open, anyone know if the bug still occurs?

**Comment by chuga-git** [comment] 2024-06-20 08:39
Closing as this objective no longer exists

**Closed by chuga-git** 2024-06-20 08:39 UTC
Labels: Bug
