### ISSUE TITLE
Mimes can howl

### ISSUE THREAD

**Issue by Little-119** [ParadiseSS13/Paradise#7899] opened 2017-07-28 18:54 UTC
**Problem Description**:
Mimes can howl

**What did you expect to happen**: 
Mimes not being able to howl

**What happened instead**:
Mimes can howl

**Why is this bad/What are the consequences:**
Mimes are supposed to be silent

**Steps to reproduce the problem**:
Be Vulp mime. Howl.

**Possibly related stuff**: Nothing

**Comment by FlattestGuitar** [comment] 2017-07-28 18:58
I think the issue is that howling is a thing in the first place.

🐺 ⛔️

**Comment by SabreML** [comment] 2020-08-13 16:43
Fixed by #13353.

**Closed** 2021-04-19 13:50 UTC
Labels: Bug
