### ISSUE TITLE
Wrapping paper is invisible.

### ISSUE THREAD

**Issue by Spacemanspark** [ParadiseSS13/Paradise#2558] opened 2015-11-15 18:07 UTC
Wrapping paper seems to turn invisible upon use. Package wrapping still works just fine.

**Comment by Robertha89** [comment] 2015-11-15 18:52
You are using it wrong, first package wrap the item, then use wrapping paper to change the type of paper.. its silly, but hey, that is how it is. Altought they still turn invisible

**Comment by Spacemanspark** [comment] 2015-11-15 18:54
Er, ya, meant that they turn invisible. Updating to reflect that.

**Comment by Robertha89** [comment] 2015-11-15 19:06
duplicate of #1385 gonna make a fix for this and #2390 using this to remember.

**Closed** 2015-11-16 00:46 UTC
Labels: Duplicate, Sprites
