### ISSUE TITLE
Advanced cam bug

### ISSUE THREAD

**Issue by realtaac** [ParadiseSS13/Paradise#16502] opened 2021-08-08 04:07 UTC
**Issue Description**:

on an advanced cam console you can see areas with no cam

**What did you expect to happen**: 

static in maints

**What happened instead**:

I could see everything

**Why is this bad/What are the consequences**:

someone could use info they see via this bug

**Steps to reproduce the problem**:

open the advanced cam console, like on the syndicate base for example, go to a place with no cam and you see static, leave the console, re-enter, an area around where you left the console on is now visible even though it should be static

**When did the problem start happening**:

**Extra information**:

**Comment by Henri215** [comment] 2023-05-28 12:24
Duplicate of https://github.com/ParadiseSS13/Paradise/issues/13948, thank you for filling this issue.

**Closed by Henri215** 2023-05-28 12:24 UTC
Labels: Bug, Duplicate
