### ISSUE TITLE
It is possible to attempt dethralling surgery with a seclight

### ISSUE THREAD

**Issue by theColdflame** [ParadiseSS13/Paradise#4286] opened 2016-04-25 07:34 UTC
**Problem Description**:
It is possible to attempt dethralling surgery using a seclight, however the seclight is unable to complete the surgery step

**What did you expect to happen**: 
I expected the seclight to either proceed the surgery or not allow me to attempt the step 

**What happened instead**:
I was able to attempt to complete the surgery step with the seclight, but the surgery did not proceed

**Why is this bad/What are the consequences:**
It leads players to believe they should be able to complete the surgery step with a seclight, when only a flashlight or penlight is capable of doing so

**Steps to reproduce the problem**:
Attempt to complete the 'cleanse contamination' step of dethrall surgery with a seclight

**Comment by TheDZD** [comment] 2016-04-25 20:36
Somewhat related to #4278, although given that not being a bug, it probably shouldn't be able to start the surgery at all.

**Comment by DesolateG** [comment] 2018-09-23 21:52
Not a bug.

**Comment by Shadow-Quill** [comment] 2019-08-16 21:33
@Fox-McCloud Either no longer a bug, or it was fixed in the past.

**Closed** 2020-03-17 19:21 UTC
Labels: Bug
