### ISSUE TITLE
Weird Hair Gradient Picture

### ISSUE THREAD

**Issue by Christasmurf** [ParadiseSS13/Paradise#17199] opened 2021-12-09 13:57 UTC
**Issue Description**:
When taking a picture, the hair gradient takes up a lot of the image
![image](https://user-images.githubusercontent.com/25437893/145409388-c9852055-8f38-44e5-aac2-84755f17a337.png)

**What did you expect to happen**: 
To look normal

**What happened instead**:
Big orange box of gradient 

**Why is this bad/What are the consequences**:
How am I meant to put pictures of myself on the newscaster to show everyone how pretty I am

**Steps to reproduce the problem**:
Take picture of self with hair gradient active

**When did the problem start happening**:
When hair gradients got added I guess?

**Extra information**:
I was putting the camera down on the table when it took the picture, not sure if that's related to the bug

**Comment by hal9000PR** [comment] 2021-12-09 14:35
Duplicate of #17116

**Closed** 2022-06-24 14:32 UTC
Labels: Duplicate
