### ISSUE TITLE
UI Menus break every so often

### ISSUE THREAD

**Issue by Quantum-M** [ParadiseSS13/Paradise#13409] opened 2020-05-10 09:43 UTC
**Issue Description**:

The UI menus when opened do not load up.

**What did you expect to happen**: 

Doesn't allow you to look at/use potentially important things (e.g. pda, uplinks, ID computer, Communications console).

**What happened instead**:

The window just had a white background where the item's UI elements were supposed to be in.

**Why is this bad/What are the consequences**:

Makes it much difficult to play the game when you have to handle certain menus but can't interact with them or see their contents (e.g. uplinks).

**Steps to reproduce the problem**:

Open a UI menu every so often, wait to see if each time it opens it breaks, if it breaks, it shows a white background.

**When did the problem start happening**:

About two weeks, having seen the issue in at least three different rounds, along with some people mentioning that they had the same issue.

**Extra information**:

It seems it gets "fixed" if you exit and log back in, but there's a chance that it breaks again later on.

**Comment by AffectedArc07** [comment] 2020-05-10 09:44
Caused from asset corruption, not something we can fix from within the code.

**Comment by farie82** [comment] 2020-05-21 17:47
Dupe of #10378

**Comment by AffectedArc07** [comment] 2021-03-04 16:02
Fixed with addition of `Reload UI Resources`

**Closed by AffectedArc07** 2021-03-04 16:02 UTC
