### ISSUE TITLE
Vampiric vision does nothing

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#3524] opened 2016-02-06 14:33 UTC
When vampires reach 100 blood they are supposed to get vampiric vision (Thermal vision) and shapeshifting.

While it does change your sight var to 32, which should be (by tigers calculation) everything except SEE_SELF or something, don't quote me on that, it was a long time ago.
Maybe @tigercat2000 remembers better.

**Comment by TheDZD** [comment] 2016-02-06 14:59
Duplicate of #2812

**Closed by TheDZD** 2016-02-06 14:59 UTC
Labels: Duplicate
