### ISSUE TITLE
Faling to spawn as a changling in a changling traitor round.

### ISSUE THREAD

**Issue by Qwertytoforty** [ParadiseSS13/Paradise#11739] opened 2019-06-22 03:04 UTC
**Problem Description**:
What is the problem?
I got the changeling message, sound and objectives, but did not spawn in

**What did you expect to happen**: 
Why do you think this is an issue?
I expected when rolling changeling on a traitor changeling round to spawn.

**What happened instead**:
How is what happened different from what you expected?
Not spawning and staying in lobby.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
People don't get the role in a normal method, causing an admin to have get involved.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
1. Have a single highly wanted job set to high.
2. Play in a traitor changeling round.
3. See if this happens

**When did the problem start happening**:
8:20PM EST 21/06/19
Saw a round with traitors and changelings earlier in the day.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Traitor changeling game mode, at the time I only had one job on to high and it was miner, with return to lobby if job not met, which probably caused the issue in the first place, As similar to issue   #11527 

Image of notification and getting objective:
https://pasteboard.co/IkvZhYc.png

**Comment by craftxbox** [comment] 2019-10-27 19:56
as #12643 is a dupe of this ill post the comment i posted there here too:
```
I have never been able to intentionally reproduce this, but have accidentally, and i theorize this is a mixture of antags rolling before roles, return to lobby when prefs unavailable and roles happening to all be unavailable.
If you choose a role that can't be that antag, you'll have the flags still but be de-antagged (ie ai, sec, Capt) however if you choose an antag capable role, then you will get antag and it will work normally, but you'll have been able to pick your job based on your objectives. Highly RNG based issue.```

**Closed** 2020-03-14 19:41 UTC
