### ISSUE TITLE
Revenant able to interact with new UI.

### ISSUE THREAD

**Issue by KozackWolf** [ParadiseSS13/Paradise#14593] opened 2020-10-12 07:45 UTC
**Issue Description**:

Revenant can interact with the new UI without manifesting

**What did you expect to happen**: 

That a revenant can't interact with machines or anything.

**What happened instead**:

I was able to open canisters, interact with exosuit fabricators and auto-lathes. (Ammendment) Also able to interact with cryotubes)

**Why is this bad/What are the consequences**:

Easily able to flood research with N2O and plasma. making for easy victims and cause WAY MORE destruction than they should be able to. (Ammendment) Cryotubes interaction makes it easy to eject and drain a victim. I was able to forcefully eject someone.

**Steps to reproduce the problem**:

Be a revenant, go to something using the new UI. try and interact with it as you normally would. Tested so far, Canisters, exosuit fabricator, and auto-lathe

**When did the problem start happening**:

I'm assuming since the new UI was implemented. (Ammendment) However this just happened when I was a revenant and thought "Can I interact with this?"

**Extra information**:

Kyet told me to github this. Since revs aren't major events, it could be bad to have them able to tamper with machines. However, I can see it as an interesting power to "haunt" them... though without costing resources, it's overpowered
(ammendment) oddly enough, the door UI opens, but you can't do anything, as it's synthetic access only.

**Comment by SteelSlayer** [comment] 2020-10-12 17:07
Duplicate of #13328. Looks like this was an issue with revenants before TGUI even. Something will have to be done about them. Probably should blanket prevent all simple animals from interacting with UIs

**Closed** 2020-10-21 20:52 UTC
