### ISSUE TITLE
T-ray Scanner allows you to buckle people onto piping through floor tiles.

### ISSUE THREAD

**Issue by BakKeener** [ParadiseSS13/Paradise#13863] opened 2020-07-17 12:45 UTC
**Issue Description**:

As stated in the title.

**What did you expect to happen**: 

I didn't expect this to occur at all.

**What happened instead**:

The T-ray Scanner brings the piping into view and existence instead of just view. This gives me a small gap to actually buckle them through the floor effectively super gluing someone to it.

**Why is this bad/What are the consequences**:

It's a easy and cheap way to buckle someone almost anywhere with the only way to remove them is having a T-ray scanner to see the piping or to crowbar it.

**Steps to reproduce the problem**:

Step 1. Turn on T-ray Scanner
Step 2. Cuff your victim
Step 3. ~~Glue~~ Buckle your victim to the piping that is now in view.
Step 4. Laugh at how you ~~glued~~ buckled them to the floor.

**When did the problem start happening**:

I found this out on 7/17/2020 around 5 AM PST, I am unsure as to when or what caused this to allow me to do this.

**Extra information**:

I don't know if you can do it without alt-clicking since I think the flooring is the most important overlay I believe?

**Comment by SabreML** [comment] 2021-08-11 15:28
Unable to reproduce, so presumably this was fixed by #15331.

**Comment by Sirryan2002** [comment] 2022-06-19 23:55
Cannot reproduce either, appears to no longer be an issue

**Closed by Sirryan2002** 2022-06-19 23:55 UTC
Labels: Bug
