### ISSUE TITLE
Windows don't seem to be airtight anymore

### ISSUE THREAD

**Issue by Sollessa** [ParadiseSS13/Paradise#9094] opened 2018-06-05 04:22 UTC
**Problem Description**:
Windows don't appear to be airtight anymore unless it's the full window setup.  I tried to setup the old school killbox in xenobiology at the window but air was leaking out and the window got busted and I got sucked out.

**Steps to reproduce the problem**:
Try the killbox in xenobiology I guess.

**Comment by Citinited** [comment] 2018-06-05 11:29
Post is very vague. Did you ensure the window was properly screwed in? Did you test other windows to see if it was just a one-off thing? Has anyone else noticed this happen before? Was anything else weird happening? etc.

**Comment by taukausanake** [comment] 2018-06-05 16:46
RIP killboxes

**Comment by ID404-NotFound** [comment] 2018-06-16 00:11
I was building a couple 1x3 grille+reinforced in space to make a new room, filled with air, and then all the air drained from the windows. Building the exact with RCD does /not/ leak

**Comment by Calecute** [comment] 2018-09-03 16:39
Could not reproduce. Deconstructed xeno windows except for the two that seal the room. Turned off air alarm so it would not interfere. Waited some time. No drop in pressure measured by air alarm, no drop in pressure measured by pda, no space wind, no air leaking sound. Pretty sure the windows are airtight.


![image](https://user-images.githubusercontent.com/34964590/44996438-587b0f00-af7e-11e8-986f-54a1641b3baf.png)

**Comment by ID404-NotFound** [comment] 2018-09-03 17:57
It's been months, air transfer between tiles might be fixed now, but I'll test when I'm able. Major test is putting up a holobarrier, opening a hole to space on other side of holobarrier, then removing holobarrier. If vacuum doesn't succ, still broke, if it do, then no problem

**Comment by Henri215** [comment] 2023-05-04 00:10
Tested and couldnt replicate, looks to be not an issue anymore?

**Comment by Sollessa** [comment] 2023-05-04 00:38
I imagine so?  It's been almost 5 years so I imagine its been fixed by now

**Closed as not planned** 2023-05-30 13:28 UTC
Labels: Need Verification
