### ISSUE TITLE
Opening the chess game and moving away doesn't allow you to close it

### ISSUE THREAD

**Issue by Christer2222** [ParadiseSS13/Paradise#15697] opened 2021-03-10 17:13 UTC
**Issue Description**:

Opening the chess game in the bar and moving away doesn't allow you to close it, even if you press the close button. It eventually closes, but it doesn't seem to be because of distance.

**What did you expect to happen**: 

To be able to "x out" the window, or at the very least press the close button.

**What happened instead**:

The window stayed open, even after pressing the "close" button.

**Why is this bad/What are the consequences**:

The window stayed open and blocked the screen. I resorted to resizing the window to the minimum size possible (something akin to a 1x5px window). However this will most likely mess up future windows, or at the very least future windows in the same game.

**Steps to reproduce the problem**:

I accidentally opened the chess board in the bar, and instead of opening it I continued into the medbay. The window stayed open until I was into the operation room. I tried multiple times to close it, but to no avail.

**When did the problem start happening**:

Bug found 10.03.2021

**Extra information**:

**Comment by matttheficus** [comment] 2022-06-21 20:54
Duplicate of #16628

**Closed by matttheficus** 2022-06-21 20:54 UTC
Labels: Duplicate
