### ISSUE TITLE
Full vision while asleep/KO

### ISSUE THREAD

**Issue by farie82** [ParadiseSS13/Paradise#8757] opened 2018-03-13 15:02 UTC
**Problem Description**:
I can see everything while being asleep or knocked out. 

**What did you expect to happen**: 
A black screen with only yourself on it

**What happened instead**:
I saw everything in my field box.

**Why is this bad/What are the consequences:**
It's not to bad of an issue since you can't do anything about it and you can RP that you didn't see it. But it can be abused

**Steps to reproduce the problem**:
I died while losing my head, then I saw everything while you were supposed to only see blackness. When I got cloned I still had the bug, I saw everything when I was being cryo tubed and when I was in surgery.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
I think it is because my head got chopped off, from there it became weird.

**Comment by farie82** [comment] 2018-03-13 15:04
![image](https://user-images.githubusercontent.com/15887760/37350070-2a95476a-26d8-11e8-8a16-39b3d9740ac4.png)
A image of the bug

**Comment by Citinited** [comment] 2018-03-14 22:12
Duplicate of #8653

**Closed** 2018-08-28 02:37 UTC
Labels: Duplicate
