### ISSUE TITLE
Broken Medibot Feature

### ISSUE THREAD

**Issue by vgauntlet** [ParadiseSS13/Paradise#7918] opened 2017-08-01 20:21 UTC
**Problem Description**:
Medibots are not injecting what is inserted via beaker - using the beaker as reagent source. It draws out a syringe - but never injects the chemicals.

**What did you expect to happen**: 
I expected the Medibots to actually inject chemicals from the beaker.

**What happened instead**:
The Medibot only drew a syringe out - never injecting the chemicals inserted into the medibot.

**Why is this bad/What are the consequences:**
The Medibot is unable to inject chemicals from a loaded beaker - stopping use of the feature.

**Steps to reproduce the problem**:
- Unlock a Medibot.
- Insert your chemicals of choice.
- Set the Reagent source to Beaker.
- Injure yourself for the medibot to try and inject you.
- Medibot will draw syringe but does not inject.

**Comment by SamHPurp** [comment] 2017-08-01 20:44
Potentially related to #7037

**Comment by pinatacolada** [comment] 2017-08-02 14:28
sounds like a duplicate of #7037 to me

**Comment by vgauntlet** [comment] 2017-08-04 06:35
Sounds about right.

**Closed** 2017-08-15 03:02 UTC
