### ISSUE TITLE
HTML formatting Bug

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#7174] opened 2017-04-25 00:39 UTC
**Problem Description**:
What is the problem?
unexpected characters
**What did you expect to happen**: 
Why do you think this is a bug?
cause it should show up normally
**What happened instead**:
How is what happened different from what you expected?
showed html/i_dont_know_what   codes
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
its not
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
name a slime nasiaf'fuiafbuis
hover over it

![capture](https://cloud.githubusercontent.com/assets/25136265/25364124/fe572662-292d-11e7-9639-d37b3a814799.PNG)

i wont be in contact with tech for 4 days so i wont be able to change title just yet

and its a PAI type slime( personnel automatic ian)

**Comment by KasparoVy** [comment] 2017-04-25 00:46
Come on man, try to make a title when you write the bug

What window is this?

**Comment by alexkar598** [comment] 2017-04-25 00:47
Lower left corner

**Comment by alexkar598** [comment] 2017-04-25 00:49
When examining or interacting it shows correctly in char

**Comment by alexkar598** [comment] 2017-04-25 00:50
Chat* and I hate mobile

**Comment by SamHPurp** [comment] 2017-04-25 00:54
HTML character encoding symbols such as apostrophes. I'm on my phone but I think this is likely a dupe issue.

**Comment by Fox-McCloud** [comment] 2017-04-25 01:02
It's not that hard to think up a title; don't be lazy about it, please.

**Comment by Will-Bohlen** [comment] 2022-04-04 23:35
Just tested this, and it looks like the issue is no longer present- likely fixed by #11515, I'd guess. 

![image](https://user-images.githubusercontent.com/15622691/161649253-5d294cdd-07b7-4a00-80c7-522e5f5f83d7.png)

**Comment by alexkar598** [comment] 2022-04-05 00:36
its been 5 years

**Comment by alexkar598** [comment] 2022-04-05 00:36
I don't even remember making this issue

**Comment by Sirryan2002** [comment] 2022-06-23 03:53
likely fixed by now, poor issue documentation

**Closed by Sirryan2002** 2022-06-23 03:53 UTC
Labels: Bug
