### ISSUE TITLE
Dark Space

### ISSUE THREAD

**Issue by FireFlashie** [ParadiseSS13/Paradise#1379] opened 2015-06-24 10:19 UTC
![image](https://cloud.githubusercontent.com/assets/10612280/8327767/a88d1072-1a73-11e5-9d45-0b802f202fd8.png)

**Comment by FalseIncarnate** [comment] 2015-06-24 10:23
Should be fixed by #1365

Server simply isn't patched yet to my knowledge.

**Comment by FireFlashie** [comment] 2015-06-24 10:42
This is latest Paradise code.

**Comment by TheDZD** [comment] 2015-06-24 21:40
@PJB3005

**Comment by Fox-McCloud** [comment] 2015-06-24 22:10
![bright](http://i72.photobucket.com/albums/i169/Fox_P_McCloud/brigt_zpsrijf4tsy.png)

I'm unable to reproduce this.

**Comment by Spacemanspark** [comment] 2015-06-24 22:40
Glance at the live server.
Also, it does look like it's the same deal on your end, look to the left.

**Comment by Fox-McCloud** [comment] 2015-06-24 22:48
I'm guessing this is a server configuration issue revolving around starlight and not necessarily a coding issue--PJB will have to look into it further.

Also, that's occurring because SS13 was designed for 15x15 and we have 17x17 so...yeah.

**Comment by PJB3005** [comment] 2015-06-25 13:01
Alright i'll see what's causing this

**Closed** 2015-06-25 22:11 UTC
Labels: Bug
