### ISSUE TITLE
Resin Grows UNDER Tiles

### ISSUE THREAD

**Issue by matttheficus** [ParadiseSS13/Paradise#20760] opened 2023-03-31 07:44 UTC
**Issue Description**:

Resin grows under tiles, making it so they cant be easily removed.

**What did you expect to happen**: 

Resin should grow on TOP of the tiles.

**What happened instead**:

It was under it.

**Why is this bad/What are the consequences**:

This is not intended.

**Steps to reproduce the problem**:

1. Place resin node.
2. Watch resin grow under tiles.

**When did the problem start happening**:

Probably with all the layering issues we've had recently.

**Comment by Contrabang** [comment] 2023-03-31 12:07
Likely caused by #20503
Possibly fixed by #20725

**Comment by unknownuser782** [comment] 2023-03-31 15:32
#20725 already has the fix for this, as it was pointed out to me on discord earlier.

**Closed** 2023-04-08 06:14 UTC
Labels: Bug
