### ISSUE TITLE
receiving deachat information from the holoparasite and robot chats while alive?

### ISSUE THREAD

**Issue by MasterrExploder** [ParadiseSS13/Paradise#7422] opened 2017-05-29 19:09 UTC
**Problem Description**:
Players able to receive communication from the Robot channel and Holoparasite channel

**Why is this bad/What are the consequences:**
It's probably a bad idea for a secuirty officer to have the ablility to receive prompts from the guardian channels...

**Steps to reproduce the problem**:
I was mauled and killed by a Goliath given sentience by a Miner, and afterwords i ghosted from my corpse, and reentered maybe twice? i was revived by SR, and for some reason i could see the communication
 
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
It was a good ol' traitor round
![bug](https://cloud.githubusercontent.com/assets/29048237/26559913/422f0e8a-4478-11e7-9388-53c35217ab6e.PNG)
![bug2](https://cloud.githubusercontent.com/assets/29048237/26559912/422a1858-4478-11e7-9677-b16f3c510418.PNG)

Pictures showing the issue

**Comment by FlattestGuitar** [comment] 2017-05-29 19:15
I've had this happen to me once and received a couple of reports from people about it, but I've never been able to reproduce it myself.

As far as I remember, every single one of these came from being revived with SR.

**Comment by MasterrExploder** [comment] 2017-05-29 19:41
i left my body by moving out of it, rather than using the ghost verb, if that helps

**Comment by alexkar598** [comment] 2017-05-29 22:51
maybe related to #7121 ?

**Comment by MasterrExploder** [comment] 2017-05-30 03:49
i read that issue as well, and yes, it's exactly the same. If there were drones talking i bet i could hear them too

**Comment by tigercat2000** [comment] 2017-06-16 12:20
Going to consider this a duplicate of #7121 as they are more than likely the same issue.

**Closed by tigercat2000** 2017-06-16 12:20 UTC
Labels: Bug, Cannot Reproduce, Duplicate
