### ISSUE TITLE
Ranged Guardian do not have any rate of fire limiter

### ISSUE THREAD

**Issue by Anasari** [ParadiseSS13/Paradise#6537] opened 2017-02-20 13:08 UTC
**Problem Description**:
Ranged Guardian do not have any rate of fire limiter, leading to obscenely high fire rate, attack log spam and instant crit in one second.

**What did you expect to happen**: 
Ranged guardian's ranged ability to have reasonable cooldown

**What happened instead**:
It shoots faster than a Roblox kid on a shitty shooter with two autohotkey autoclicker

**Why is this bad/What are the consequences:**
Ranged guardians tear apart everything.

**Steps to reproduce the problem**:
Be ranged parasite. CLICK.

**Comment by Kyep** [comment] 2017-02-20 13:38
Verified. Tested it in admin test area - ranged guardian can fire a constant stream of crystal bullets.

**Comment by SamHPurp** [comment] 2017-02-20 13:53
Saw it in the live environment, absolutely wrecking people.

**Comment by taukausanake** [comment] 2017-02-21 05:40
This is also a duplicate of #2729 I thinks. Wow, and so old too

**Closed** 2017-02-21 20:48 UTC
