### ISSUE TITLE
Wooden furniture (bamboo) gives metal when decon'd instead of wood

### ISSUE THREAD

**Issue by Niteark** [ParadiseSS13/Paradise#18115] opened 2022-06-27 19:21 UTC
You can use wood planks to build bamboo stools or benches, but when wrenched return metal sheets.

**What did you expect to happen**: 
Should get wood planks back

**What happened instead**:
Alchemy or something

**Why is this bad/What are the consequences**:
Muh immersion and logic, its weird turning wood into metal with a common wrench.

**Steps to reproduce the problem**:
Acquire wood, build bamboo, wrench bamboo.

**When did the problem start happening**:
Noticed today

**Extra information**:

**Comment by hal9000PR** [comment] 2022-06-27 19:23
duplicate of #18105

**Closed by hal9000PR** 2022-06-27 19:23 UTC
Labels: Duplicate
