### ISSUE TITLE
Autocloners break plasmaman revival

### ISSUE THREAD

**Issue by Shadeykins** [ParadiseSS13/Paradise#8136] opened 2017-09-25 06:50 UTC
**Problem Description**:
The Autocloner breaks plasmamen from being revived. This is because the cloner no longer forces the ghost into a cloning body, which means an autocloner will immediately scan an eligible body while they're cloning. (IE: A valid body is put in, it immediately clones, then it immediately rescans).

This results in a situation wherein the plasmaman will be thrown into their dead corpse (which is defibbable), before being ripped back out of it into the second dead body. The end result is confused medical personnel, an SSD body, and a real body.

While it is still possible to revive the second body, you essentially have what was a perfectly valid but now SSD body that a ghost can't get back into (because they were forced into the second, dead body while their primary, earlier body was being revived).

**What did you expect to happen**: 
For Plasmamen not to be forcibly thrown into another body while they're being defibbed.

**What happened instead**:
See above.

**Why is this bad/What are the consequences:**
Plasmamen are paradoxically harder to clone with an autocloner due to zombie plasmamen.

**Steps to reproduce the problem**:
1) Have an autocloner.
2) Scan a dead, valid plasmaman.
3) Watch the plasmaman clone.
4) Follow the revival procedure for plasmamen when the rejected clone shoots out.
5) Behold your new zombie plasmaman, as the ghost is flung into the new dead body spit out by the autocloner.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Changeling. Watching cloning as a ghost. No.

**Comment by Contrabang** [comment] 2023-03-23 04:04
Duplicate of #13587, the other one has better information and is more generalized than autocloners + plasmamen

**Closed by Contrabang** 2023-03-23 04:04 UTC
Labels: Bug
