### ISSUE TITLE
TGUI - DNA Modifier Access Console "From Disk" Bug

### ISSUE THREAD

**Issue by Boidca** [ParadiseSS13/Paradise#14314] opened 2020-09-15 17:51 UTC
**Issue Description**: 
![image](https://user-images.githubusercontent.com/71344502/93245674-89a09380-f783-11ea-83b3-efd4470e420b.png)

**What did you expect to happen**: To upload the data from the disk when I click the From Data button

**What happened instead**: Absolutely nothing happened when I clicked the "From Disk" button

**Why is this bad/What are the consequences**: It means I cannot copy DNA data from one machine to the other via a disk

**Steps to reproduce the problem**: Load up a body into the dna scanner, download the contents onto a disk, go to the other console and try to fill a new buffer "From Disk"

**When did the problem start happening**: When trying the new testmerge in the round i'm playing.

**Comment by dearmochi** [comment] 2020-09-15 18:39
I'm unable to reproduce this issue locally. Did you try re-opening the window after pressing From Disk?

**Comment by Boidca** [comment] 2020-09-15 20:41
A number of times, yeah. Swapped console and everything. Might've been an issue on my end?

**Comment by dearmochi** [comment] 2020-09-16 09:58
Could be... I'll have to try on the live server.

**Comment by dearmochi** [comment] 2020-09-17 22:11
Can't reproduce after a couple rounds as Geneticist on the live server. Does the issue persist for you? It could've been a one-off.

**Comment by Sirryan2002** [comment] 2022-07-11 14:38
cannot reproduce this either, closing

**Closed by Sirryan2002** 2022-07-11 14:38 UTC
Labels: TGUI
