### ISSUE TITLE
Crafting A Chainsaw Doesn't Give You The "Wielded" Item

### ISSUE THREAD

**Issue by Leanfrog** [ParadiseSS13/Paradise#14480] opened 2020-09-28 18:50 UTC
**Issue Description**:
You can craft a chainsaw and use it with one hand when you normally have to use both hands to hold it opening up shenanigans with shields and other items

**What did you expect to happen**: 
To be given the wielded "item" in my off-hand preventing me from holding another item

**What happened instead**:
I was able to use a second item alongside the chainsaw

**Why is this bad/What are the consequences**:
Chainsaws are a rather powerful weapon, part of their balance is the fact that they must be wielded to be used, this bug though allows the user to carry a second item or weapon in their off hand allowing for some silly combos

**Steps to reproduce the problem**:
1. Craft Chainsaw
2. See that only one hand is filled by the chainsaw
3. Take any item and use it at the same time as the chainsaw

**When did the problem start happening**:
Probably ever since you could craft a chainsaw

**Extra information**:

**Comment by VEN0M5** [comment] 2020-11-16 04:40
Duplicate of #12551

**Closed** 2020-11-26 09:45 UTC
