### ISSUE TITLE
PKA Upgrade Duplication

### ISSUE THREAD

**Issue by Banderblitz** [ParadiseSS13/Paradise#22116] opened 2023-08-25 21:31 UTC
**Issue Description**: 
Duplicating the effect of a PKA upgrade with a single upgrade.

**What did you expect to happen**: 
I expected to buy one PKA upgrade, and get one effect added to my gun.

**What happened instead**:
I was able to buy a single upgrade, and apply it twice to the same gun.

**Why is this bad/What are the consequences**:
Getting the effects of two upgrades for the price of one is just an abuse, it however has very little consequences in the scheme of things, as it is a PKA.

**Steps to reproduce the problem**:
1. Obtain a PKA (proto-kinetic accelerator, the mining gun).
2. Get an upgrade that is small enough to be applied to a gun twice.
3. Place PKA in hand.
4. Click the PKA onto the upgrade as fast as possible.
5. Your gun now has two upgrades of the same kind for the price of one.

**When did the problem start happening**:
As of 8/25/2023, it has likely been in existence as long as PKAs have existed.

**Comment by Contrabang** [comment] 2023-08-25 21:34
Did the upgrade come from RND or the vendor?

**Comment by Banderblitz** [comment] 2023-08-25 21:37
It came from the vendor, however I believe you can do it with any if you just click fast enough.

**Comment by Adrer** [comment] 2023-09-01 14:15
Unable to reproduce using an autoclicker.

**Comment by silverplatedelta** [comment] 2024-11-28 05:17
As Chap was unable to reproduce, this likely occurred due to server latency. Closing as not planned.

**Closed by silverplatedelta** 2024-11-28 05:17 UTC
Labels: Bug, Exploit
