### ISSUE TITLE
Fore Port Solar Array APC

### ISSUE THREAD

**Issue by Jovaniph** [ParadiseSS13/Paradise#12185] opened 2019-09-02 15:51 UTC
**Issue Description**:
The Fore Port Solar Array is not connected to the Area and will not take External Power. It stays stuck at 90% on the monitor computer and directly.

This issue really is a map oversight. The Area is not fully enclosed so therefore, the Area is basically broken. (See image below)

![image](https://user-images.githubusercontent.com/11299017/64125089-ca935900-cd76-11e9-8416-4dfd3edd03e9.png)

This is how is should be:
![image](https://user-images.githubusercontent.com/11299017/64125232-5311f980-cd77-11e9-99d3-1a19999ca0d9.png)

Even after removing the APC from the wall. You cannot put it back on the wall. We tried using the blueprint to make it work, but it doesn't work either.

**What did you expect to happen**: 
The APC to work

**What happened instead**:
APC no work

**Why is this bad/What are the consequences**:
SMES doesn't distribute power to the station. So therefore only 3/4 of the Solar Arrays throughout the station are running at any given time. The only solution would be to directly power the solar to the main line.

**Steps to reproduce the problem**:
N/A This is a mapping problem.

**When did the problem start happening**:
I don't know. Recent Map merges in that area?

**Extra information**:
I have video clips, if you need additional proof.

**Comment by AffectedArc07** [comment] 2019-09-02 15:54
I dont think this is the problem. You can have un-enclosed areas in the map itself, the APC just binds to that area. You can even have 2 instances of the same area and have it share power (Look at wildwest APC distribution)

![image](https://user-images.githubusercontent.com/25063394/64125532-2f17dd80-cda2-11e9-8151-a0bee49c1288.png)

The `X` signifies the actual tile the APC is on (They are placed on the floor then pixel shifted)

**Comment by Jovaniph** [comment] 2019-09-02 15:56
I placed a wall in the middle of the room and try to set an APC on that.. it still wouldn't work.

**Comment by Shadow-Quill** [comment] 2019-09-02 16:14
Duplicate of #11752

**Comment by FreeStylaLT** [comment] 2019-09-02 18:18
oh no! What sort of sick, careless mind mapped this mistake in?! 💢 :angry:

**Closed** 2019-09-02 21:25 UTC
