### ISSUE TITLE
Cryogenic Oversight Console repeated listing

### ISSUE THREAD

**Issue by Lazyman310** [ParadiseSS13/Paradise#21109] opened 2023-05-17 01:45 UTC
**Problem Description**:
What is the problem?
The cryogenic oversight console listed a shaft miner hundreds of times, making looking at the list of cryo'd crew impossible.

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
A few days ago at least

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.
Round ID 35749, was looking to see which shaft miners cryo'd and which needed recovered

**Comment by Sirryan2002** [comment] 2023-05-17 01:49
do you have any more details about this bug, we're aware it exists but have been unable to reproduce it on a local server.

**Comment by Lazyman310** [comment] 2023-05-17 01:54
Sadly I do not, apologies. I kept scrolling and scrolling, and the name continued repeating

**Comment by Contrabang** [comment] 2023-06-15 21:29
A newer issue with a picture has been created and more information, closing this

**Closed by Contrabang** 2023-06-15 21:29 UTC
Labels: Bug, TGUI
