### ISSUE TITLE
paper and bundles weird

### ISSUE THREAD

**Issue by sirjatu** [ParadiseSS13/Paradise#22995] opened 2023-10-22 11:40 UTC
**Issue Description**:
stacking paper into a bundle and then burning the said bundle with a welder burn the papers in it, but leaves you with a bundle of paper which description states it still has X number of paper in it, but you cannot interact with it other than pick it up

**What did you expect to happen**: 
paper to get stuck in a limbo

**What happened instead**:
paper was stuck in a limbolike state within a bundle that serves no purpose

**Why is this bad/What are the consequences**:
bugs bad

**Steps to reproduce the problem**:
take lots of paper, stack all paper in a bundle, apply welder, ash is made, bundle remains

**When did the problem start happening**:
noticed when making ash in science today

**Comment by DGamerL** [comment] 2023-10-22 21:27
This is a duplicate of #16218 , closing. Thank you for making the report, luckily a PR was open to fix it already! If you have any other issues, feel free to open a new issue report!

**Closed by DGamerL** 2023-10-22 21:27 UTC
Labels: Bug
