### ISSUE TITLE
Cross-species transformation with UIs is faulty

### ISSUE THREAD

**Issue by ModDownloading** [ParadiseSS13/Paradise#6471] opened 2017-02-16 14:10 UTC
**Problem Description**:
Injecting yourself with the UI of someone who is a different race than you changes your name and some physical features but not your actual race.

**What did you expect to happen**: 
If you inject yourself with the UI of someone who is a different race than you, you should turn into that person in appearance, race and name.

**What happened instead**:
Injecting yourself with the UI of someone who is a different race than you changes your visible name and some physical features, but not your race and occasionally not your skin/scale color.

**Why is this bad/What are the consequences:**
UI injecting should provide a complete change, not just a partial one.

**Steps to reproduce the problem**:
Get someone of another race into the genetics scanner, put their UI/UE into a DNA injector, then inject yourself.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I found this issue on my private testing server. Injecting yourself with the UI of someone that is the same race as you has no issues, you turn completely into them. Also, the polymorph mutation has similar issues to the UI injecting because all that ability does is copy someone else's UI over your own.

**Comment by Crazylemon64** [comment] 2017-02-16 14:30
Don't quote me on this, but I'm pretty sure this is to keep karma-locked species/similar inaccessible to non-members of that species.

**Comment by ModDownloading** [comment] 2017-02-16 15:24
If that is true, how about making it so that you can only transform using UIs into species you have unlocked/everyone can get?

**Comment by DesolateG** [comment] 2017-02-16 15:35
Working as intended.

**Comment by ktoma36** [comment] 2017-02-16 16:05
I have had this happen as a changling slime. I had transformed into a tagaran in my process to collect dna and tried to transform to my old form. What ended up happening was I became a tagaran with all the tags of my slime person and the translucent brightly colored skin. Thankfully no one acted on my strange appearance but at a gameplay standpoint this would be a dead giveaway to anyone low enough to use meta information ingame.

**Comment by uraniummeltdown** [comment] 2017-02-16 17:56
are you sure ktoma? as a changeling Vox I can transform from Vox to human to Vox just fine (although when going human->vox you have to transform twice as the hair doesn't load properly first time)

**Comment by ktoma36** [comment] 2017-02-16 18:00
Yeah, when I examined myself it still said I was a tagaran, plus I started to suffocate in a vacuum.

**Comment by MischievousGremlin** [comment] 2017-02-17 02:54
So wait... An entire branch of strategies and gameplay is locked out because of "muh karma" but why? I understand locking the species out pre round, but stopping people from becoming them in the round is just bizzare... Being able to turn myself into the person i just killed if i broke my way into the genetics lab would be awesome! I could even see a vox injecting their victims with a vox UI as a way of murder because they wouldn't have their voxygens, so if this is working as intended then it really needs to be looked at.

**Comment by Rumiluntti** [comment] 2017-02-18 18:12
This is how it has always been

**Comment by Fox-McCloud** [comment] 2017-02-19 16:48
Yeah, going to close this; unless genetics itself is refactored to handle this.

**Closed by Fox-McCloud** 2017-02-19 16:48 UTC
Labels: Inconsistency, Not a Bug
