### ISSUE TITLE
AI Examine Issue

### ISSUE THREAD

**Issue by granodd** [ParadiseSS13/Paradise#7296] opened 2017-05-13 06:44 UTC
**Problem Description**:
The AI cannot examine people unless they have a mask on.

**What did you expect to happen**: 
I expected to be able to examine people without masks on.

**What happened instead**:
It flat out does not let you examine anyone not wearing a mask as the AI. Makes it very difficult for setting security records and arrests.

**Why is this bad/What are the consequences:**
You should be able to examine people regardless of whether or not they're wearing a mask.

**Steps to reproduce the problem**:
Attempt to examine any crew not wearing masks with the current version of the client.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Pretty sure this has to do with the previous issues of not being able to examine people without masks.

**Comment by SamHPurp** [comment] 2017-05-13 09:01
@Aurorablade & @FlattestGuitar

**Comment by Anoonki** [comment] 2017-05-13 09:05
I'm gonna go out on a limb and say this is the same issue as #7292

**Comment by granodd** [comment] 2017-05-13 09:26
I could have sworn there was a PR that was merged rather recently that fixes this though. At least, for non-AI. I might be mistaken though.

**Comment by FlattestGuitar** [comment] 2017-05-13 10:43
I can't reproduce this. The live server works just fine now.

My bet would be the commit got pushed live way later than it was merged here and I didn't make a changelong, which confused people.

**Comment by FalseIncarnate** [comment] 2017-05-13 18:37
Server updates between rounds. Issues are closed when the PR is merged, not patched. Therefore, if a PR gets merged mid-round, the server won't patch until the next round, but the issues will be closed, leading to people mistakenly believing the issue is still valid and sometimes re-reporting it because they don't wait until a new round to re-confirm.

**Comment by SamHPurp** [comment] 2017-05-13 18:40
@FalseIncarnate there was 8 hours between issue report and the merge, which is why a few of us assumed it was still current.

**Closed** 2017-05-13 19:32 UTC
