### ISSUE TITLE
Character Selection UI won't load whatsoever.

### ISSUE THREAD

**Issue by grestin** [ParadiseSS13/Paradise#16527] opened 2021-08-11 23:33 UTC
**Issue Description**:
Whenever I join the character selection UI won't show up.

**What did you expect to happen**: 
This one is obvious.

**What happened instead**:
Whenever I join the character selection UI won't show up.

**Why is this bad/What are the consequences**:
Can't play the game.

**Steps to reproduce the problem**:
Join.

**When did the problem start happening**:
Yesturday.

**Extra information**:
I've tried every possible fix, and I say again, every possible fix, so this is most certainly a serverside issue. Furthermore, it works when I log in on a different account only my primary account is unable to load the UI.

**Comment by SabreML** [comment] 2021-08-12 01:32
Assuming that 'Czardoc' is your ckey, this seems to be related to #16449. Either caused by it, or only discovered because of it.
```
[2021-08-11T23:25:59] Runtime in 20-load_characters.dm,84: list index out of bounds
[2021-08-11T23:25:59]   proc name: process result (/datum/client_login_processor/load_characters/process_result)
[2021-08-11T23:25:59]   src: /datum/client_login_processor/... (/datum/client_login_processor/load_characters)
[2021-08-11T23:25:59]   call stack:
[2021-08-11T23:25:59]   /datum/client_login_processor/... (/datum/client_login_processor/load_characters): process result(/datum/db_query (/datum/db_query), Czardoc (/client))
[2021-08-11T23:25:59]   Czardoc (/client): New(null)

[2021-08-11T23:25:59] Runtime in new_player.dm,45: Cannot read null.real_name
[2021-08-11T23:25:59]   proc name: new player panel proc (/mob/new_player/proc/new_player_panel_proc)
[2021-08-11T23:25:59]   usr: Czardoc (czardoc) (/mob/new_player)
[2021-08-11T23:25:59]   usr.loc: The plating (8,174,1) (/turf/simulated/floor/plating)
[2021-08-11T23:25:59]   src: Czardoc (/mob/new_player)
[2021-08-11T23:25:59]   src.loc: the plating (8,174,1) (/turf/simulated/floor/plating)
[2021-08-11T23:25:59]   call stack:
[2021-08-11T23:25:59]   Czardoc (/mob/new_player): new player panel proc()
[2021-08-11T23:25:59]   Czardoc (/mob/new_player): new player panel()
[2021-08-11T23:25:59]   Czardoc (/mob/new_player): Login()
[2021-08-11T23:25:59]   Czardoc (/client): New(null)
```
[20-load_characters.dm](https://github.com/ParadiseSS13/Paradise/blob/8ee04f3b400105f9dedaad057ae638f0df15d592/code/modules/client/login_processing/20-load_characters.dm) line 84 is this:
https://github.com/ParadiseSS13/Paradise/blob/8ee04f3b400105f9dedaad057ae638f0df15d592/code/modules/client/login_processing/20-load_characters.dm#L84
Which is referring to the 53rd item from `Q`, the `slot` column of the `characters` table in the database.
https://github.com/ParadiseSS13/Paradise/blob/8ee04f3b400105f9dedaad057ae638f0df15d592/code/modules/client/login_processing/20-load_characters.dm#L6-L62
<hr>

I'm not sure what caused the issue yet, but it should be fixed pretty quickly so I wouldn't worry too much about it.

**Comment by grestin** [comment] 2021-08-13 11:17
Cool thanks

**Comment by grestin** [comment] 2021-08-13 11:19
Cool thanks

**Comment by AffectedArc07** [comment] 2021-08-13 11:21
What is your ckey, and can you ping me on discord so I can deal with this?

**Comment by grestin** [comment] 2021-08-18 03:18
> What is your ckey, and can you ping me on discord so I can deal with this?

My ckey is czardoc I cannot join the discord because im banned idk why

**Closed** 2022-06-21 16:58 UTC
