### ISSUE TITLE
Cutted leg bug ( texture agin )

### ISSUE THREAD

**Issue by iwanesko** [ParadiseSS13/Paradise#7997] opened 2017-08-22 14:32 UTC
**Problem Description**:
I cut 2 legs ( self ), and I loose 2 legs and foot ( foot displays on me, but a don; have him

 **What did you expect to happen**: 
Foot lie around and displays on me =/

**What happened instead**:
Foot displays on me, but I do not what display him

**Why is this bad/What are the consequences:**
Medical mistake

**Steps to reproduce the problem**:
Cut legs and spin around ( vulpkanin )

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

![3](https://user-images.githubusercontent.com/29836662/29570710-6e083d0a-8781-11e7-99fc-c74c8553f0cb.png)

**Comment by taukausanake** [comment] 2017-08-22 15:28
Yeah, duplicate of #7596

**Comment by iwanesko** [comment] 2017-08-22 20:27
I donn wear socks

**Comment by Sirryan2002** [comment] 2022-07-06 03:50
duplicate issue

**Closed by Sirryan2002** 2022-07-06 03:50 UTC
Labels: Sprites
