### ISSUE TITLE
Durathread jumpsuits cannot be dyed via washing machine and crayons without textures breaking

### ISSUE THREAD

**Issue by evilmattyg** [ParadiseSS13/Paradise#21132] opened 2023-05-20 03:48 UTC
**Issue Description**:
When dying a durathread jumpsuit through the washing machine and inserting a crayon, the durathread jumpsuit does not change colour, and instead has texture issues and gets renamed to (what crayon it was dyed with) jumpsuit.

**What did you expect to happen**: 
When dying a durathread jumpsuit through the washing machine and a crayon, I expected the durathread jumpsuit to be a durathread jumpsuit, but in a different colour.

**What happened instead**:
When taken out of the washing machine, the durathread jumpsuit was renamed to black jumpsuit, and gained a placeholder(?) honk texture. When worn, it also has another placeholder texture.

**Why is this bad/What are the consequences**:
I believe this is important to fix, as style should be compatible with protection, and there is no reason to not allow durathread jumpsuits to be dyed colours, like every other jumpsuit.

**Steps to reproduce the problem**:
1. Insert a crayon colour of choice into washing machine.
2. Insert a durathread jumpsuit into the washing machine.
3. Turn on said washing machine.
4. Take out durathread jumpsuit to see a placeholder texture.

**Extra information**:]
Tested on an older codebase (1 year>), but may still be obscure enough to be unfixed.

**Comment by Henri215** [comment] 2023-05-20 12:04
Closing this issue since its a duplicate of https://github.com/ParadiseSS13/Paradise/issues/20411. Thank you for filling this one.

**Closed by Henri215** 2023-05-20 12:04 UTC
Labels: Sprites, Duplicate
