### ISSUE TITLE
Abductor console malfunction.

### ISSUE THREAD

**Issue by KingPhilipIII** [ParadiseSS13/Paradise#5227] opened 2016-07-28 12:49 UTC
**Problem Description**:
I was playing as a scientist and for most of the run, the console worked as intended, retrieving and sending down what I marked or what was on telepad. Some time through however, the abductor console's retrieve function ceased to work while we were abducting members of security. Despite my agent's best attempts to survive(In which he incapacitated the entirety of security.) without being able to grab him he died. 

**What did you expect to happen**: 
Contrary to the name, it did not retrieve. I expected my agent to get zapped up when he was about to get lynched.

**What happened instead**:
It simply ceased to function. Despite going down and marking a differant target and attempting to retrieve him, it still did not work, or when I remarked my agent.

**Why is this bad/What are the consequences:**
It's completely game breaking for the Abductor antagonist, since without retrieval they cannot abduct people or safely recover their agents.

**Steps to reproduce the problem**:
The only thing I think might have caused this bug was I dropped my agent, flew off screen and then tried to retrieve him. When I went back apparently it was not retrieving despite having him marked. Otherwise I have no idea what caused it.

**Possibly related stuff: Well. We were admin spawned abductors. Thats just about the only thing I can think of.

**Comment by KingPhilipIII** [comment] 2016-07-28 12:50
New to this. Gimme a sec.

**Comment by TheDZD** [comment] 2016-07-28 13:25
@Fox-McCloud

**Comment by Fox-McCloud** [comment] 2016-07-28 14:58
>**Possibly related stuff: Well. We were admin spawned abductors. Thats just about the only thing I can think of. 

Define admin spawned? Did they set your species, spawn the event (with the "do you want to be considered for abductor?") or something else?

**Comment by KingPhilipIII** [comment] 2016-07-28 16:15
Spawned the event. It was too earlier for an abductor RNG.

**Comment by KingPhilipIII** [comment] 2016-07-28 16:16
Wow. Early. What is wrong with my grammar.

**Comment by AndriiYukhymchak** [comment] 2016-09-24 10:56
we were also adminspawned...

**Comment by Contrabang** [comment] 2023-03-23 03:37
Not able to reproduce and after 6 years, it is likely fixed

**Comment by Burzah** [comment] 2023-08-15 18:26
Tested for this today. I was not able to reproduce this bug. As pointed out above, it was most likely fixed at some point over the 6 year period. Closing this issue as of now. Thank you for making a report.

**Closed by Burzah** 2023-08-15 18:26 UTC
Labels: Bug, Cannot Reproduce
