### ISSUE TITLE
Mechs do not take damage from projectiles 

### ISSUE THREAD

**Issue by SmokingKilz** [ParadiseSS13/Paradise#5790] opened 2016-10-17 22:16 UTC
**Problem Description**:
What is the problem?
Mechs do not take damage from projectiles.
**What did you expect to happen**: 
Why do you think this is a bug?
Mech's getting hit by projectiles should be taking damage.
**What happened instead**:
How is what happened different from what you expected?
Mech's do not seem take damage, when shot at by projectiles, this is also a non-consistent bug, every now and then a projectile will damage a mech, but majority of the shots do not.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It eliminates the ability to take down mechs with projectiles weapons apart from the Ion Carbine, forcing a melee confrontation with a big military grade mech. 
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
I've asked Elysian_Prince to test out if I was correct, he used a mauler on a dark gygax that was on the admin station, and they did take damage from each others projectiles. I thought I was possibly wrong, however one of the rounds end round grief happened, I found myself in a gygax, and tried fighting the other two mechs, neither of us could damage each other with the ballistics of the mechs, so we started going for melee. Then, since the end round was delayed, I spaced myself and managed to find the Syndicate asteroid with the turrets. I stood in front of the turrets so long that they fired at least close to a hundred rounds into the mech, and only a single bullet did damage. I asked Tully to try it out for himself later on, he confirmed that when he tried to put a full mag of a captains laser into a ripley it did no damage. So my theory is, that possibly mechs that were brought in AFTER round start are the only ones immune to projectiles?

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us. 
As stated above. #

**Comment by Taaketa** [comment] 2016-10-18 00:10
Fixed in #5763

**Comment by Plotron** [comment] 2016-10-18 00:52
Also a duplicate of #5761.

**Comment by SmokingKilz** [comment] 2016-10-18 01:12
Guess if it's already been posted this can be closed.

**Comment by Taaketa** [comment] 2016-10-18 01:21
You can do that at the bottom of the comment box.

**Closed** 2016-10-18 02:07 UTC
