### ISSUE TITLE
Monkey cubes does not properly qdel on being watered

### ISSUE THREAD

**Issue by Robertha89** [ParadiseSS13/Paradise#2248] opened 2015-09-30 15:55 UTC
![image](https://cloud.githubusercontent.com/assets/7663878/10198467/6dbbe0f6-679c-11e5-8877-796efac9f159.png)
You still hold an invisible cube in your hand

**Comment by Markolie** [comment] 2015-09-30 16:51
Duplicate of https://github.com/ParadiseSS13/Paradise/issues/1566.

**Closed** 2015-09-30 16:51 UTC
Labels: Duplicate
