### ISSUE TITLE
Schrödinger's HardHat - IPC teleporting

### ISSUE THREAD

**Issue by hunakos57** [ParadiseSS13/Paradise#13103] opened 2020-03-11 05:27 UTC
**Issue Description**:

It is not really a problem just an abusable bug. Any IPC can teleport to any cyborg rechargers by doing a little setup. It works over every Z levels. The teleport happens when somebody uses the eject on the cyborg recharger that been set up with this bug.

**What did you expect to happen**: 

Found it by accident was not expecting anything.

**What happened instead**:

HardHat Magic, that what happened. The IPC moved to the same tile where the cyborg recharger is, the cyborg recharger showed that somebody was inside but the IPC was not.

**Why is this bad/What are the consequences**:

You can teleport from anywhere to set locations and you can't even tell if somebody teleported since it looks like they just move out of the recharger.

**Steps to reproduce the problem**:

Be an IPC. Stand next to a cyborg recharger that is EMPTY. Grab intent -> grab somebody. (monkey, other player), Move to the tile where the cyborg recharger is. Done.

**When did the problem start happening**:

This bug might as be as ancient as the game is also I named it Schrödinger's HardHat. :P

**Extra information**:

Sorry for not being serious with this issue report. I just already miss my HardHat magic. :( (side note, I never abused it or used it aside showing to a random vox who was needed for the first test so I could confirm the bug existence, Torque - Cazdon(admin), Reagan, Frost, and Slade - Dumbdumn5 admin)

**Comment by Citinited** [comment] 2020-03-11 18:50
Duplicate of #13102 😛

**Comment by hunakos57** [comment] 2020-03-11 18:58
*snip-snip... he was faster by seven minutes, should have showed him after I reported the bug... the betrayal.     /s

**Comment by hunakos57** [comment] 2020-03-11 18:58
> Duplicate of #13102 😛

*snip-snip... he was faster by seven minutes, should have showed him after I reported the bug... the betrayal. /s

**Comment by matttheficus** [comment] 2022-06-22 14:05
Duplicate of #13233

**Closed by matttheficus** 2022-06-22 14:05 UTC
Labels: Duplicate
