### ISSUE TITLE
Becoming colorblind then removing it turns view white

### ISSUE THREAD

**Issue by Sylvaratayn** [ParadiseSS13/Paradise#9919] opened 2018-10-20 22:29 UTC
**Problem Description**:
Being turned colorblind by a Geneticist changes your vision just fine, but being reversed back seems to apply both screen effects simultaneously, turning your screen a blinding white.

**What did you expect to happen**: 
Should remove the colorblind effect and restore vision to normal.

**What happened instead**:
Both effects were instead applied over top of each other.

**Why is this bad/What are the consequences:**
Minor issue, can be fixed with a reconnect, but should still be tracked.

**Steps to reproduce the problem**:
Apply colorblind effect to individual, remove colorblind effect.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing important.

**Comment by SamHPurp** [comment] 2018-10-20 22:35
This is fixed in the next BYOND release

**Comment by tigercat2000** [comment] 2018-10-20 23:11
Duplicate of #9868

**Closed by tigercat2000** 2018-10-20 23:11 UTC

**Comment by KasparoVy** [comment] 2018-10-21 00:06
byond y u break my colourblind
