### ISSUE TITLE
Problem with Progression to Command Roles

### ISSUE THREAD

**Issue by MustacheMan45** [ParadiseSS13/Paradise#15624] opened 2021-02-27 07:23 UTC
**So, I've played as an IAA on Paradise Station for a while now, and it seems like no matter how long I play as an IA or how long I learn more and more about the game, command roles still won't unlock for me. I've checked my occupation preferences multiple times after two-hour-long rounds, and it's always the same. **"19h until unlocking"** Or something like that.**:

** I don't think it's a display problem, as even when I click on the message, it still doesn't put a role to low, medium, or high. I'm not exactly sure what's causing the problem, as I'm not a coder. I believe it might have something to do with the code responsible for role progression, but I'm not sure. I don't play many of the other departments like medical, science, or cargo. I'm usually a security, or IAA when the round starts. If not I'm a civilian. I'm not sure if HoS is the job I need to play for 20h to unlock command roles, but I saw IAA in the Command roles, and IA isn't a department head, so I've played as an IAA for a while now. I progressed one hour, so it's now 19h instead of 20, but I know this isn't from me playing as an HoS, as I've never been that job.**: 

**I expected I would play as an IAA for 20h, learn SSOP, CSOP, LSOP, Space Law, others and more. But it wasn't the case.**:

**I think this is important as I cannot play as command roles, ever. This means that, if it ever comes to me to be an Acting Command Figure, I will fail to perform. I'm not sure if this is just a problem with me, or if it's a problem for other players.**:

**Before I found this problem, I decided to give IAA a shot during one round a few months ago. I played as an IAA that round, read space law and SSOP for most of the round, and then the round finished. The menu showed I had progressed one hour through the process of unlocking command roles. After that, I kept playing as an IAA for a few more rounds, studying Space Law, SSOP, and LSOP for most of them. But, it didn't progress at all.**:

**Well, it's been a few months since I encountered the problem now, so some, or all of my information could be correct or incorrect. The last time I progressed any time through the process to unlock command roles, was a few months ago, as I mentioned earlier. I just played one round as an IAA, about an hour or so long, and when it ended, I progressed an hour.**:

**There's not much else to note, other than this could be a problem with IAA somehow not being recognized as a Command role, in which the game might not think I'm playing a command role. Either this, or I really do have to be an HoS to progress. I'm going to try playing as an HoS one round, and if I progress any more, I'll let the readers of this post know.**:

**Comment by farie82** [comment] 2021-02-27 07:45
Internal Affairs Agents are considered support positions in the code. `support_positions`. You will only get "experience" towards command roles by playing command roles. Any head role will do:
```
	"Captain",
	"Head of Personnel",
	"Head of Security",
	"Chief Engineer",
	"Research Director",
	"Chief Medical Officer",
	"Nanotrasen Representative"
```
Issue can be closed as it's not a bug but a feature request

**Comment by AffectedArc07** [comment] 2021-02-27 07:55
IAA isn't command, you'll need to play one of the others as farie mentioned.

**Closed** 2021-02-27 07:55 UTC
Labels: Not A Bug
