### ISSUE TITLE
The Rod of Asclepius  Duplicating of when you try to cut of a arm

### ISSUE THREAD

**Issue by rapaskoti** [ParadiseSS13/Paradise#12670] opened 2019-10-30 12:09 UTC
**Issue Description**: When you cut of the arm holding the Rod it will firstly get you a copy of the arm and then it will start to spawn a bunch asclepius Rods

**What did you expect to happen**: I just expected the arm to fall off and the rod with it

**What happened instead**:look in the description above

**Why is this bad/What are the consequences**:It duplicates a item over and over and could cause problems for the server and for that matter its duplicating a item that there is only supposed to be one of

**Steps to reproduce the problem**:Amputate the arm holind the Rod of Asclepius  

**When did the problem start happening**:My guess is that it has ben a issue since it got added 

**Extra information**: just a picture of what happens 
![image](https://user-images.githubusercontent.com/44611123/67857214-d739f080-fb1e-11e9-8d46-50d2702c78af.png)

_it keeps going for a while_

**Comment by Citinited** [comment] 2019-10-30 12:10
Dupe of #12631

**Comment by rapaskoti** [comment] 2019-10-30 12:17
well i will just go ahead and close this as another one was made before this

**Closed** 2019-10-30 12:17 UTC

**Comment by Citinited** [comment] 2019-10-30 12:38
Cheers!
