### ISSUE TITLE
Invisible leg

### ISSUE THREAD

**Issue by iwanesko** [ParadiseSS13/Paradise#7998] opened 2017-08-22 14:46 UTC
**Problem Description**:
Cutted leg invisible
**What did you expect to happen**: 
Invisible leg

**What happened instead**:
Leg stay invisible

**Why is this bad/What are the consequences:**
Invisible leg =/

**Steps to reproduce the problem**:
Cut the leg and turn it top
 ( If right leg - turn right. If Left leg - turn left )

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

![1](https://user-images.githubusercontent.com/29836662/29571402-4a2e2078-8783-11e7-8373-c2dee98870e4.png)

**Comment by taukausanake** [comment] 2017-08-22 15:27
Duplicate of #7596?

**Comment by iwanesko** [comment] 2017-08-22 20:24
No, i cut only one leg. I havr 1 leg, layer bag.

**Comment by iwanesko** [comment] 2017-08-23 16:02
I don't think

**Comment by Twinmold93** [comment] 2017-08-23 22:20
Oversight, but also would require every species to have overlaid legs, which is a lot of work.

**Comment by Sirryan2002** [comment] 2022-07-06 03:50
duplicate issue

**Closed by Sirryan2002** 2022-07-06 03:50 UTC
Labels: Sprites, Code Limitation
