### ISSUE TITLE
Cyborgs can not intract with small animals such as mice

### ISSUE THREAD

**Issue by ASmolKitten** [ParadiseSS13/Paradise#19835] opened 2022-12-04 03:05 UTC
**Issue Description**:
While using the "Hugging Module" as borg you can pick up mice but cant drop them or put them back down.

**What did you expect to happen**: 

This may have happened due to borgs having no internal storage and the hugging mod acting like a normal open hand action. I tried to pet the mouse but he was just teleported inside of me.

**What happened instead**:

Usually this would just hold the mouse but it was just eaten by the game.

**Why is this bad/What are the consequences**:

Its not super important but Cyborgs handing out pet mice as emotional support would be great. 

**Steps to reproduce the problem**:

This was done with Tom in the vault with me. Started round as medical borg. Went to the vault after a while to drop off money because the AI said to and tried to pet Tom with the Hugging Module. 

**When did the problem start happening**:

This happened today and this report is being written during the round that it happened.

**Extra information**:

Round ID: 33729
M.O,O,N

**Comment by GDNgit** [comment] 2022-12-04 04:03
duplicate of #18895

**Comment by ASmolKitten** [comment] 2022-12-04 10:57
Easy. Ill close this then! thanks GDN

**Closed** 2022-12-04 10:57 UTC
