### ISSUE TITLE
Meat hook deals insane amount of damage

### ISSUE THREAD

**Issue by littleherse** [ParadiseSS13/Paradise#12930] opened 2020-01-28 11:31 UTC
**Issue Description**:
The meathook seems to deal damage multiple times at once when a blobbernaut is hit by a meathook, one shotting it. Apparently this happens when the meathook is used point blank.

**What did you expect to happen**: 
The meathook to hit once.

**What happened instead**:
It hit multiple times and instantly killed a blobbernaut, dealing crazy damage. 
![image](https://user-images.githubusercontent.com/60387791/73259705-9fe3ea00-41c8-11ea-8ae9-fb59dc6eaedc.png)

**Why is this bad/What are the consequences**:
The meathook becomes the best weapon to use against blobbernauts, being an instant kill. Also may not be intended behavior for the hook.

**Steps to reproduce the problem**:
Use meathook on blobbernaut (Point blank?)

**When did the problem start happening**:
2020-01-28 is when I first saw it

**Extra information**:
It can be used to one shot blobbernauts, but it may also be usable on any mob to deal tons of damage.

**Comment by Spacemanspark** [comment] 2020-01-28 11:33
FRESH MEAT

**Comment by farie82** [comment] 2020-01-28 17:35
Could not repro it locally both using pointblank and normal shots at blobbernauts.
Did the projectile per chance get reflected by a reflector blob?

**Comment by Pckables** [comment] 2020-01-29 07:58
I've actually seen this happen against a sentient xenobio spider that a miner was using meathooks on.
It did happen when the spider was near or already on the same tile as the miner. It might be an issue of a mob being on the same tile as the destination but in the middle of moving away when the meathook lands.

**Comment by farie82** [comment] 2020-01-30 21:21
@Kyep is it possible to get the runtimes from that day?

**Comment by Kyep** [comment] 2020-01-30 22:08
@farie82 I searched the runtime logs for the last 3 days for "magic/hook" and blobbernauts. I found nothing (except runtimes caused by blobbernauts attacking grilles).

**Comment by farie82** [comment] 2020-01-30 22:31
> @farie82 I searched the runtime logs for the last 3 days for "magic/hook" and blobbernauts. I found nothing (except runtimes caused by blobbernauts attacking grilles).

Thanks. Was worth a shot...

**Comment by littleherse** [comment] 2020-02-01 10:07
I'd ask whoever played Jim Moore that shift. He seemed to know how to pull it off

**Comment by SomeSortaSquid** [comment] 2020-03-01 20:30
Probably related: Some time ago, I have killed myself by throwing a meathook at my guardian. It was either point-blank or two tiles away, I don't quite remember. Damage has thrown me instantly into crit, so it had to be massive.
On Lavaland, it works as intended, causing relatively minor damage to fauna and dragging it on top of you.

Possibly affects all non-Lavaland simple mobs or all player-controlled simple mobs,

**Comment by farie82** [comment] 2020-07-03 20:30
Should be fixed in #13637

**Closed** 2020-07-03 20:31 UTC
