### ISSUE TITLE
Slime console allows you to see through walls

### ISSUE THREAD

**Issue by Christer2222** [ParadiseSS13/Paradise#18732] opened 2022-08-07 01:31 UTC
**Issue Description**:

The consoles in xenobiology allows you to look at the walls, and to see what is on the other side.

**What did you expect to happen**: 

To not be able to put the cursor on walls/have vision to other rooms blocked off.

**What happened instead**:

Being able to see through walls.

**Why is this bad/What are the consequences**:

Spying on other rooms is probably not intended for these machines.

**Steps to reproduce the problem**:

1. Use a slime console in xenobiology.
2. Put the cursor on a wall that has another room next to it.

**When did the problem start happening**:

Its been around forever, but it is much more noticeable with the new map rework.

**Extra information**:

![image](https://user-images.githubusercontent.com/25958019/183271042-3bcb8e3f-d28a-451f-b8ad-d18c61c47a5d.png)

**Comment by Henri215** [comment] 2023-05-06 12:08
Is this still an issue? And in which stations it happens?

**Comment by Christer2222** [comment] 2023-05-09 18:25
I don't know about other stations, but I haven't noticed it lately on Cyberiad. I also haven't been testing this a lot, such as what happens if a wall is deconstructed.

**Comment by Henri215** [comment] 2023-05-11 00:24
> I don't know about other stations, but I haven't noticed it lately on Cyberiad. I also haven't been testing this a lot, such as what happens if a wall is deconstructed.

After testing i believe this issue is related to https://github.com/ParadiseSS13/Paradise/issues/13948 and https://github.com/ParadiseSS13/Paradise/issues/13225.


https://github.com/ParadiseSS13/Paradise/assets/77684085/3d5c2f25-2a5a-4269-a85f-d7f4ad5fea8c

**Comment by Christer2222** [comment] 2023-05-13 03:27
![image](https://github.com/ParadiseSS13/Paradise/assets/25958019/9c0120f8-8bb6-4870-9f4b-090d6394c66d)
Can confirm, it still happens.

**Comment by Henri215** [comment] 2023-05-13 12:06
> ![image](https://user-images.githubusercontent.com/25958019/238109954-9c0120f8-8bb6-4870-9f4b-090d6394c66d.png) Can confirm, it still happens.

Similar to my video method?

**Comment by Christer2222** [comment] 2023-05-23 23:41
> Similar to my video method?

Actually I think that is how I did it too, my bad.  Just refreshing the view.

**Comment by Henri215** [comment] 2023-05-23 23:47
> > Similar to my video method?
> 
> Actually I think that is how I did it too, my bad. Just refreshing the view.

Looks like it is the same as https://github.com/ParadiseSS13/Paradise/issues/13948 then, a problem with all advanced camera consoles.

**Comment by Christer2222** [comment] 2023-05-24 00:00
Ah, very likely. Do I leave this open just in case it is different, or do I close it? And do I do anything special when I close it?

**Comment by Henri215** [comment] 2023-05-24 00:03
Duplicate of https://github.com/ParadiseSS13/Paradise/issues/13948, thanks for reporting :)

**Closed by Henri215** 2023-05-24 00:03 UTC
Labels: Oversight, Duplicate
