### ISSUE TITLE
Ghost "Jump to Area" menu is malformed

### ISSUE THREAD

**Issue by warriorstar-orion** [ParadiseSS13/Paradise#16692] opened 2021-09-11 20:55 UTC
**Issue Description**:

I am on 514.1566. As a ghost, attempting to use the Jump to Area menu to teleport to ghost gang did not work.

**What did you expect to happen**: 

I expected the names of areas to be properly displayed, and for selecting one of them to land me in the appropriate place.

**What happened instead**:

Area names were mangled and attempting to teleport to one of the areas with a mangled name did not occur.

**Steps to reproduce the problem**:

1. Enter a round via Observe.
2. Use the Jump to Area HUD icon.
3. Attempt to find, e.g., "Wizard's Den".

**When did the problem start happening**:

Like yesterday

**Extra information**:

Don't know if this is a known issue, figured I'd file it anyway.

![Paradise Station 13-01_19_53](https://user-images.githubusercontent.com/59303604/132961372-180536ed-cece-49f5-889d-8ada35c00b66.png)

**Comment by SabreML** [comment] 2021-09-12 19:09
This seems to be a Byond issue rather than anything we can fix, unfortunately.
The observer teleport menu uses `SSmapping.ghostteleportlocs` for the list:
https://github.com/ParadiseSS13/Paradise/blob/c4fb435a8af82a60828a86e3e057db2a8b05d5ad/code/modules/mob/dead/observer/observer.dm#L384-L394
I tested on commit 1d47d4a93c4bf671726dd16b01bbfa8970943bbb (the one before #16647 was merged), and this is that same list on both versions:
<details>
<summary><b>Screenshots:</b></summary>

**v513.1542:**
![513](https://user-images.githubusercontent.com/57483089/132999536-9f86830a-5387-4b75-b38a-dc5e20362587.PNG)
**v514.1566:**
![514](https://user-images.githubusercontent.com/57483089/132999544-b3f4e764-81ce-4b83-8590-86fd9f7661c4.PNG)
</details>

(TLDR: `Admin%20Room` on 513, `%ff%16Admin%20Room` on 514.)

This seems to be caused by the `\improper` in the area names not being correctly encoded or decoded, for some reason.
`%ff` (according to https://www.w3schools.com/tags/ref_urlencode.ASP) represents the `ÿ` character, as can be seen in some other cases of `\improper` in the game.
`%16` however, is the [`SYN`](https://en.wikipedia.org/wiki/Synchronous_Idle) control character, and is presumably what's causing the issue.

**Closed** 2021-10-04 19:14 UTC
