### ISSUE TITLE
Cannot remove labels from floors/walls with the hand labeller.

### ISSUE THREAD

**Issue by ReedOni** [ParadiseSS13/Paradise#20529] opened 2023-03-02 14:19 UTC
**Issue Description**:

I cannot remove the label off a floor tile/wall by using the hand labeller.

**What did you expect to happen**: 

To be able to remove the label.

**What happened instead**:

The label remained in place.

**Why is this bad/What are the consequences**:

While it isn't super bad it seems like we should be able to remove labels off the floor/wall. The label can be removed if the tile is also removed and replaced or if the wall is deconstructed, but that requires tools if the floor or wall is removable at all.

**Steps to reproduce the problem**:

Label a floor or wall and try to remove the label like you would with any other item by holding a turned off hand labeler.

**When did the problem start happening**:

Consensus says it's been like this for a while.

**Extra information**:

While this is a very trivial issue, for consistency reasons the hand labeller should be able to remove labels off the floor or walls.

**Comment by ReedOni** [comment] 2023-03-04 08:36
I can confirm the same behaviour is present on walls. Can't remove the label from the wall either.

**Comment by silverplatedelta** [comment] 2024-11-29 17:28
closing as duplicate of #27356

**Closed by silverplatedelta** 2024-11-29 17:28 UTC
Labels: Bug
