### ISSUE TITLE
Taraja don't have good night vision anymore.

### ISSUE THREAD

**Issue by Deelite34** [ParadiseSS13/Paradise#11618] opened 2019-05-30 18:18 UTC
**Problem Description**:
What is the problem?
Tarajan don't have good night vision anymore.
**What did you expect to happen**: 
Why do you think this is an issue?
You are suppossed to see a bit in dark.
**What happened instead**:
How is what happened different from what you expected?
It's pitch dark, as if I had human eyes.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?
I think since new lightning/changes to vision/when toggle darkness was added

**Comment by KasparoVy** [comment] 2019-05-30 19:31
Caused by TG lighting and would be resolved by https://github.com/ParadiseSS13/Paradise/pull/11484

**Closed** 2019-08-04 22:47 UTC
