### ISSUE TITLE
Kida bioluminescence is bugged

### ISSUE THREAD

**Issue by BottomQuarks** [ParadiseSS13/Paradise#8816] opened 2018-03-26 18:38 UTC
**Problem Description**:
Kida bioluminescence is not working at all.
I have noticed Fethas said on forum "Also the kidan biolum is brighter then you think and notable if you actually change the color", I decided to check it. 
1. I was unable to change the color. There is option in "IC" section to "Toggle Reagent Recoloring", I can't see any other option related to colors. Whenever I click it, it states "You're not a slime person!"
2. I tried to turn biolum on in the dark room, there was no light even if it said "You enable your bioluminescence.". I even tried to take off all the clothes. Did not work at all.
I even m-helped that. Miraviel tried to help, still the biolum is mistery.

**What did you expect to happen**: 
Basicly, I'd say it should generate light. And if "Toggle Reagent Recoloring" was supposed to be option to change light color, it should work, and if not then maybe removed from "IC" section.

**What happened instead**:
Well, it didn't work at all!

**Why is this bad/What are the consequences:**
Kida race cannot wear glasses, beeing able to generate light is a little improvement.

**Steps to reproduce the problem**:
Uh.... "You enable your bioluminescence!". It did not work in room without any light source

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: ------------------------------

**Comment by pinatacolada** [comment] 2018-03-26 22:02
the color of the light is the same color as the body markings. idk what the default color is, but if its black, well, you cant really glow black

**Comment by taukausanake** [comment] 2018-03-26 23:40
> you cant really glow black

but damn if you had blacklight lighting that would be sweet af

**Comment by BottomQuarks** [comment] 2018-03-27 04:48
Hm.... that would be it. I will check it on private server later. Could we change it to the color of the eyes? Nobody really has black eyes.

**Comment by pinatacolada** [comment] 2018-03-29 12:29
actually i forgot, its a mix of eye and body marking colors

**Comment by Tayyyyyyy** [comment] 2018-04-03 03:29
@BottomQuarks you should probs close this issue if it's not a bug

**Closed** 2018-04-03 17:04 UTC
