### ISSUE TITLE
Defib's 3 minute grace period doesn't seem to be properly resetting

### ISSUE THREAD

**Issue by Lady-Luck** [ParadiseSS13/Paradise#6992] opened 2017-03-29 22:48 UTC
I defibbed someone with a lot of toxin buildup. They revived, but instantly died. Went and did a dialysis to remove toxin, took like 30 seconds. However, the defib said their heart tissue was too damaged. This does not seem like intentional behavior... and given the SR nerf, it's super fucking punishing.

**Comment by pinatacolada** [comment] 2017-03-30 00:29
Did their time of death update?

**Comment by Lady-Luck** [comment] 2017-03-30 00:30
Didn't think to check.

**Comment by KasparoVy** [comment] 2017-03-30 02:28
I see this happen so much. People inexplicably unrevivable (wish I could view vars to see whats going down) in circumstances where you're sure they should be fine to resuscitate. I wonder how extensive the bug is.

**Comment by pinatacolada** [comment] 2017-03-30 17:09
can't reproduce, needs more info

![adasfaf](https://cloud.githubusercontent.com/assets/13833056/24516832/f257c088-1573-11e7-9618-83d41891e0d6.png)

**Comment by Lady-Luck** [comment] 2017-03-30 19:42
Try loading them up with frost oil. Death upon defibbing was pretty much instantaneous.

**Comment by Fox-McCloud** [comment] 2017-04-04 22:23
Going to attribute this to a once off rare bug; report it again, are absolutely sure of it, and have verified with the health analyzer that it is, in fact, true. CLosing for now

**Closed by Fox-McCloud** 2017-04-04 22:23 UTC
