### ISSUE TITLE
Alien Organ Manipulation doesn't work

### ISSUE THREAD

**Issue by uraniummeltdown** [ParadiseSS13/Paradise#5972] opened 2016-12-10 16:31 UTC
**Problem Description**:
Alien Organ Manipulation on carbon xenos doesn't work

**What did you expect to happen**: 
I tried to manipulate organs with the hemostat

**What happened instead**:
Nothing happened, no feedback, no stopping surgery message, no manipulation

**Why is this bad/What are the consequences:**
You can't extract organs from xenos

**Steps to reproduce the problem**:
Spawn an alien queen, start Alien Organ Manipulation with scalpel/saw, in the last step with hemostat nothing will happen

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Just a normal round with xenos from the event

**Comment by taukausanake** [comment] 2016-12-11 04:39
Duplicate of #5741? Which is also a duplicate of #5710. Huh

**Closed** 2016-12-11 22:26 UTC
