### ISSUE TITLE
Blob Mind Datum Issue

### ISSUE THREAD

**Issue by GuiltyBeans** [ParadiseSS13/Paradise#6578] opened 2017-02-23 23:41 UTC
**Problem Description**:
When prompted to be spawned as a Blob for midround antag I found myself in control of the Blobs eye, and for a while, the core and resources. But after the resources hit 30, and about thirty seconds had passed, another player took control of the core even though I held control of the eye. No resources could be gained when this occured.

**What did you expect to happen**: 
Not two minds to be in the same blob!

**What happened instead**:
Two players took over the same blob, causing resources to not accumulate for the player in control of the eye.

**Why is this bad/What are the consequences:**
If it is reproducible it will cause blob players, midround at least, to fail whenever they spawn in due to being unable to do anything.

**Steps to reproduce the problem**:
So far the only steps were to accept the position as blob as a ghost and wait.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I want to speculate for a moment here. I noticed that I had entered the blob core the moment it spawned... But thirty seconds later another person entered. I think that whatever was changed that let blobs spawn instantly and not with the thirty second delay is causing two people to be pulled to the same core.

**Comment by Kyep** [comment] 2017-02-23 23:42
Duplicate of: https://github.com/ParadiseSS13/Paradise/issues/6572

**Comment by GuiltyBeans** [comment] 2017-02-23 23:43
Well shoot, I need to read through these more. Didn't realize it was already up.

**Comment by Taaketa** [comment] 2017-02-24 02:18
It is literally the issue report below yours :/

**Closed** 2017-02-24 15:45 UTC
Labels: Bug, Duplicate
