### ISSUE TITLE
Station air supply is divided into at least 3 separate networks. 

### ISSUE THREAD

**Issue by Calecute** [ParadiseSS13/Paradise#9407] opened 2018-08-23 23:57 UTC
**Problem Description**:
Station air supply pipes are divided into at least 3 separate networks

**What did you expect to happen**: 
Station air supply should be all in one network

**What happened instead**:
Station air supply is divided into 3 separate networks

**Why is this bad/What are the consequences:**
Atmos have to do a lot of work at the start of the round if they know about the problem. If they don't know most of the station can't be repressurized through normal means. Saw escape stay depressurized for half an hour until someone found out what was wrong, as an example, but it can happen in other areas too. Also it may hamper the ability of using the network for mobility, witch could negatively affect some antags and drones. 

**Steps to reproduce the problem**:
Check pressure in air supply pipes in corridor near cargo, see they have pressure. Go north and check air supply pipes near vault, see they have no pressure. Connect both pipes. Now go to the brig main corridor, see it still have no pressure. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**:
As far as I can tell the 3 networks are: medbay, bridge, cargo, eng and atmos, forming the Aft Port network, the one with actual air in it. The other one is arrivals, fore corridor and the things in it, eva, and it goes into sec lobby, the Fore Port network. And then there’s is the network containing most of brig, dorms, service area, starboard hallway, science and escape, the Fore Starboard Network. Unfortunately, I couldn't check extensively, and did so only inside the game, without a mapping tool that would make it more convenient, so I might be wrong, but it is a place to start.

Also important, this was in the new map, not the regular one

**Comment by taukausanake** [comment] 2018-08-24 13:40
New map? Can you specify the map name? We only use Cyberiad so need to make sure it's not Meta or some other

**Comment by Calecute** [comment] 2018-08-24 15:35
Cyberiad with the edits. New brig and dorms and all

**Comment by taukausanake** [comment] 2018-08-24 20:26
You mean #9379? That's not merged yet. And Sec/dorms hasn't been majorly edited that recently that it's new

**Comment by Calecute** [comment] 2018-08-24 20:29
Yeah that's what i meant.

**Comment by taukausanake** [comment] 2018-08-24 23:59
If the issue is with the unmerged map then you need to voice your concerns in said PR while it is unmerged. After it is merged you can make a separate Issue. Issues are for things in the live code

**Comment by Spartan6** [comment] 2018-08-25 00:33
Except we are currently testmerging it so I can understand the confusion.

**Comment by Calecute** [comment] 2018-08-25 03:07
I will voice my concerns in said PR while it's kinda unmerged then. Should I close this?

**Closed** 2018-08-28 01:30 UTC
