### ISSUE TITLE
Mech Rapid Cable Layer doesnt work

### ISSUE THREAD

**Issue by jjamac** [ParadiseSS13/Paradise#3774] opened 2016-03-06 23:33 UTC
**Problem Description**:
What is the problem?
Trying to lay cable down with the RCL (rapid cable layer) doesnt work. Picking up and eject cable function properly though
**What did you expect to happen**: 
Why do you think this is a bug?
It literally doesnt work
**What happened instead**:
How is what happened different from what you expected?
Nothing happened when i activated the cable layer
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Its a minor issue and one that can be ignored
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Attatch a RCL to a ripley. Pickup some cable set the active component to the RCL and clicked activate. Spammed clicking on both plated and unplated tile. Also tried walking around on plated and unplated tiles with it active and nothing at all happened
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

Tried it on a normal ripley and a fire fighter ripley neither of which worked. I made sure i activated it and selected it.

**Comment by tigercat2000** [comment] 2016-03-06 23:34
duplicate of #3630

**Closed** 2016-03-07 01:19 UTC
