### ISSUE TITLE
QM - Stamp

### ISSUE THREAD

**Issue by BiberDark** [ParadiseSS13/Paradise#3278] opened 2016-01-18 12:39 UTC
The QM -Stamp is the same like the normal granted one. We need a new icon for this.

**Comment by CrAzYPiLoT-SS13** [comment] 2016-01-18 12:45
Duplicate of #2781.

**Comment by Plotron** [comment] 2016-01-18 12:55
I think cargo needs more stamps.
It's cool that QM has a duplicate for stamping manifests for points.

**Closed** 2016-01-18 18:25 UTC
Labels: Duplicate
