### ISSUE TITLE
Switching race from IPC with prosthetics, keeps prosthetics on new race.

### ISSUE THREAD

**Issue by lolzyking** [ParadiseSS13/Paradise#4105] opened 2016-04-05 01:33 UTC
**Problem Description**:
 I'm a robot kitty with robot head chest and lower body

**What did you expect to happen**:
 not be a robot kitty

**What happened instead**:
 above

**Why is this bad/What are the consequences:**
well head types seem important

**Steps to reproduce the problem**:
switch race from ipc with full prosthetics to an organic race

**Comment by lolzyking** [comment] 2016-04-05 01:39
brain is in the ipc head, lmao

**Comment by NTSAM** [comment] 2016-04-05 01:48
i don't get it

**Comment by NTSAM** [comment] 2016-04-05 01:49
oh

**Comment by Crazylemon64** [comment] 2016-04-05 02:24
Yeah, swapping species in the preferences panel doesn't revert to a sane state, so you can get fat IPCs or robo-head tajarans.

**Comment by KasparoVy** [comment] 2016-04-06 03:06
Is this from start-round character setup or by accessing the character setup via the game preferences verb in the preferences tab? Every time without fail, regardless of the race I switch to or the configuration I've my prosthetic parts in, it reverts me to no prosthetics whatsoever by accessing the menu by either means

**Comment by Spacemanspark** [comment] 2016-04-06 03:13
The amusing part is that Polaris actually has this as a feature, in a matter of speaking.

**Comment by lolzyking** [comment] 2016-04-06 08:24
from character setup in at log in

**Comment by KasparoVy** [comment] 2016-04-06 21:22
That's pretty wild, huh. I tried to emulate a case where the SQL might be causing the issue but it didn't seem to be the cause in my setup

I'll do what I can to try and test for if it's because one might be running 509 still

**Comment by Sirryan2002** [comment] 2022-07-13 18:36
duplicate of #4764

**Closed by Sirryan2002** 2022-07-13 18:36 UTC
Labels: Bug, Need Verification
