### ISSUE TITLE
Plant disguise does not revert to original character icon

### ISSUE THREAD

**Issue by Chakirski** [ParadiseSS13/Paradise#4915] opened 2016-07-07 14:42 UTC
**Problem Description**:
Plant icon duplicated, player still is a plant icon after dropping plant.

**What did you expect to happen**: 
You'd think that dropping the plant would disable the disguise.

**What happened instead**:
Plant is dropped, becomes object, player is still the plant icon = 2 plants from 1 plant

**Why is this bad/What are the consequences:**
Stealth factor increased by plant. Plus you're able to use both hands now.

**Steps to reproduce the problem**:
While walking with hotkeys enabled, push q. I was also dragging a protokinectic accelerator but I doubt that has anything to do with this?

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by tigercat2000** [comment] 2016-07-07 14:42
Duplicate of #4814

**Closed** 2016-07-07 14:45 UTC
Labels: Duplicate
