### ISSUE TITLE
Both hands are highlighted instead of just one

### ISSUE THREAD

**Issue by Finalgamer10** [ParadiseSS13/Paradise#18782] opened 2022-08-11 20:33 UTC
**Issue Description**:

Both my hands were highlighted, even though only one was actually used at a time

**What did you expect to happen**: 

It makes it confusing to use items, since one cannot really be sure which hand is selected right now

**What happened instead**:

Both hands were highlighted instead of one.

**Why is this bad/What are the consequences**:

It can cause players to use the wrong item at a given time, since they cannot see which one is selected.

**Steps to reproduce the problem**:

It was a cultist round and i was a doctor. I got a baseball bat made from wood for self defense. Used it a bit while also sometimes managing an item in my other hand. At some point i realized that both my hands were highlighted. I noticed this primarily after i was culted and dropped the bat. Though i think the issue itself might have happened once i used an healing item while also having the bat in the other hand.

**When did the problem start happening**:

Never encountered this issue before, but i also really never used a bat before.

**Extra information**:

Round ID: 32392

**Comment by Adrer** [comment] 2022-08-29 14:50
Can confirm this has happened to me as well, unable to reproduce though.

**Comment by Henri215** [comment] 2023-05-06 12:26
Duplicate of https://github.com/ParadiseSS13/Paradise/issues/19778, closing this one since the other has more information.

**Closed by Henri215** 2023-05-06 12:26 UTC
Labels: Bug, Duplicate
