### ISSUE TITLE
Mindslaving as an operative breaks the HUD icons

### ISSUE THREAD

**Issue by Gatchapod** [ParadiseSS13/Paradise#22516] opened 2023-09-20 16:08 UTC
**Issue Description**:
Mindslaving as a nuclear operative completely overrides operatives' team HUD icons with mindslaving ones, likely completely invisible to other operatives. I could not confirm it due to confusion, but I believe the mindslave master cannot see operatives' icons either.

**What did you expect to happen**: 
To not get slaughtered by my own team who could not immediately identify me as a friendly.

**What happened instead**:
I was chainsawed to death as I tried to explain I'm a friendly, not someone who stole the gear.

**Why is this bad/What are the consequences**:
Due to the above, mindslaving as an operative leads to massive amounts of confusion, which in turn leads to team kills.

**Steps to reproduce the problem**:
Spawn as a nuclear operative with a team.
Purchase a bunch of mindslave implants.
Mindslave non-operatives (I grabbed either 2 or 3 people, I don't remember).
Your nuclear team HUD icon is now replaced with mindslaving one and you likely cannot see HUD icons of your nuclear teammates.

**When did the problem start happening**:
Noticed today, 20th September 2023.
Don't know if it ever worked correctly, since this was the first time I used mindslaving implants as an operative.

**Extra information**:
n/a

**Comment by Contrabang** [comment] 2023-09-20 16:11
Duplicate of #20153. Thank you for the report! I wish I could think of a clear way to solve this...

**Closed by Contrabang** 2023-09-20 16:11 UTC
