### ISSUE TITLE
Balaclava Adjust bug.

### ISSUE THREAD

**Issue by DeathProof92** [ParadiseSS13/Paradise#16149] opened 2021-06-10 16:01 UTC
**Issue Description**:
If you press the "Adjust balaclaca" button in the left Corner, then your balaclava lands in your hands. You can now put it only on the Head. If you put it on the Head you don't have Hairs anymore. If you press "Adjust balaclava" again, its normal again and you can put it back on the Maskslot.

**What did you expect to happen**: 
When you press the "Adjust balaclava" button, normal the balaclava "rolls" out of the Face.

**What happened instead**:
Its lands in your activ Hand and need to put on the Head slot.

**Why is this bad/What are the consequences**:
You need to remove the balaclava instead of press the Button

**Steps to reproduce the problem**:
1. Take a balaclava
2. Press the "Adjust balaclava" Button
3. Success! It lands in your Hand.
4. Try to put it on the Mask slot. Nothing Happend.
5. Put it on the Head slot. Your Hair is lost.
6. Press the "Adjust balaclava" Button again.
7. its normal again!

**When did the problem start happening**:
I join in Midround, go to dorms and find on my way a balaclava. Takes it, use it, and now this bug happend.

**Extra information**:
Not really.
![Bug1](https://user-images.githubusercontent.com/85695988/121558278-d1540300-ca15-11eb-954c-358d6b2e1ec7.png)
![bug2](https://user-images.githubusercontent.com/85695988/121558283-d2853000-ca15-11eb-89dd-42836f974782.png)
![bug3](https://user-images.githubusercontent.com/85695988/121558285-d31dc680-ca15-11eb-8caa-7c7a163adee8.png)
![bug4](https://user-images.githubusercontent.com/85695988/121558289-d3b65d00-ca15-11eb-9253-42101f6495b3.png)
![bug5](https://user-images.githubusercontent.com/85695988/121558293-d44ef380-ca15-11eb-833b-eb49b0ebca8b.png)

**Comment by SabreML** [comment] 2021-06-10 16:34
Duplicate of #7134, although this one is better formatted.
(Also for the record, this effects *every* species including Skrell, and it's absolutely cursed.)
![Paradise Test NSS Cyberiad 2021-06-10 172939](https://user-images.githubusercontent.com/57483089/121563220-1c6c1700-ca12-11eb-9a07-d29fc5f6641f.png) ![Paradise Test NSS Cyberiad 2021-06-10 172932](https://user-images.githubusercontent.com/57483089/121563226-1d04ad80-ca12-11eb-9b62-536af4de1238.png)

**Closed** 2021-07-26 17:10 UTC
