### ISSUE TITLE
Items going to the middle of nowhere

### ISSUE THREAD

**Issue by alexkar598** [ParadiseSS13/Paradise#7673] opened 2017-06-29 22:22 UTC
**Problem Description**:
What is the problem?
If you vomit in a mech with an item in hand the item disappear into the NOWHERE land

**What did you expect to happen**: 
Why do you think this is a bug?
A button similar to speeds pod check under seats

**What happened instead**:
How is what happened different from what you expected?
It's lost 4 ever

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

Maybe it is nuki disky

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Grab item in hand-->getbitten by spooder to get toxin damage and venom-->go in mech with item in hand-->cry as you lose the hos advanced e gun

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

It was the medi mech

**Comment by Crazylemon64** [comment] 2018-08-28 03:08
Duplicate of #3193

**Closed by Crazylemon64** 2018-08-28 03:08 UTC
Labels: Duplicate
