### ISSUE TITLE
Circtuir Imprinters and Metal

### ISSUE THREAD

**Issue by Jountax** [ParadiseSS13/Paradise#7887] opened 2017-07-27 14:18 UTC
**Problem Description**:
There are some things you need metal to print from a circuit imprinter, but circuit imprinters cannot accept metal.

**What did you expect to happen**: 
I would expect to be able to print anything a circuit imprinter can create given the resources for it.

**What happened instead**:
I was unable to insert the require materials.

**Why is this bad/What are the consequences:**
It should be possible, given the materials and tech levels, to print anything a machine is capable of printing.

**Steps to reproduce the problem**:
Attempt to print any network card from a circuit imprinter.

**Comment by taukausanake** [comment] 2017-07-27 14:32
Duplicate of #7515 
Duplicate of #7788

Interestingly enough this issue was tackled with PRs #7797 and #7799 but both got closed

**Closed** 2017-07-27 21:22 UTC
