### ISSUE TITLE
Morgue trays that are opened detach and drift away when gravity is offline

### ISSUE THREAD

**Issue by ExitGame** [ParadiseSS13/Paradise#7129] opened 2017-04-19 19:08 UTC
Turn off the gravity, then open a morgue tray, you'll see it drifting off when you move around it or pull it and then if you close it the morgue tile that drifted away also disappears back into the tray again.

**Comment by SamHPurp** [comment] 2017-04-19 19:12
Duplicate of #2540

**Comment by alexkar598** [comment] 2017-04-19 19:14
Dupe of issue #2540.Next time check before making an issue report.Please close this one.

**Comment by SamHPurp** [comment] 2017-04-19 19:48
>Dupe of issue #2540.Next time check before making an issue report.Please close this one.

Dupe comment of:

>Duplicate of #2540

Next time check before making a comment.

**Comment by alexkar598** [comment] 2017-04-19 19:55
XD

**Comment by alexkar598** [comment] 2017-04-19 19:59
I'm on mobile so the page dose not show new comments until refresh

**Comment by tigercat2000** [comment] 2017-04-19 21:37
As stated above, duplicate, and also a feature:tm:

**Closed** 2017-04-21 21:35 UTC
