### ISSUE TITLE
Eyeglow on camera bug

### ISSUE THREAD

**Issue by IrkallaEpsilon** [ParadiseSS13/Paradise#9531] opened 2018-09-12 19:22 UTC
**Problem Description**:
When AI you can see people with augmented eyes through walls when there are no cameras having line of sight to them.

**What did you expect to happen**: 
Not being able to have a wallhack without having an Xray camera.

**What happened instead**:
You can see people through walls if they have assisted/mechanical eyes.

**Why is this bad/What are the consequences:**
Basicly allows an AI to track people with mechanical eyes more or less through maintenance.

**Steps to reproduce the problem**:
Be AI, watch maintenance. Get someone with mechanical eyes in there (or any glowing eyes for that matter). See them despite not having cameras. Really problematic during Slings.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Any gamemode.

**Comment by Contrabang** [comment] 2023-03-23 04:10
Not able to reproduce, likely fixed one of the many camera refactors

**Closed by Contrabang** 2023-03-23 04:10 UTC
Labels: Bug
