### ISSUE TITLE
Floorbot cannot fix damaged tile, it remove tile but cannot place new one.

### ISSUE THREAD

**Issue by Venuska1117** [ParadiseSS13/Paradise#22479] opened 2023-09-19 09:34 UTC
**Issue Description**:
When you set floorbot to "repair damaged tiles and plating" and "replace floor tiles" floorbot will stuck on one tile trying to repair it, with make it use up all floor tiles on one tile without repairing it.

**What did you expect to happen**: 
Repair floor tile using 1 tile, not ALL tiles.

**What happened instead**:
Used ALL tiles by trying place tile on floor.

**Why is this bad/What are the consequences**:
Floorbot using all tiles to repair one tile is kinda... waste of resources.

**Steps to reproduce the problem**:
1. Make Floorbot.
2. Enable "repair damaged tiles and plating" and "replace floor tiles".
3. watch floorbot remove tile, and try place new tile without placing it, and using up all tiles it have.

**When did the problem start happening**:
Dont know when

**Extra information**:
Its bug, bug need fixes.

**Comment by Henri215** [comment] 2023-09-19 11:18
Duplicate of https://github.com/ParadiseSS13/Paradise/issues/22472, thanks for reporting.

**Closed by Henri215** 2023-09-19 11:18 UTC
Labels: Bug, Duplicate
