### ISSUE TITLE
Bees are noclipping to kill me.

### ISSUE THREAD

**Issue by Komrad822** [ParadiseSS13/Paradise#22633] opened 2023-09-28 21:21 UTC
**Issue Description**:
Bees are passing through solid objects such as windoors to attack people. (Most likely just windoors)

**What did you expect to happen**: 
Expected to look at bees from safety of windoor barrir.

**What happened instead**:

The bees passed through the windoor and attacked me, killing me.

**Why is this bad/What are the consequences**:

It really screws over botany honestly. If they cant contain their murderous bees, they might as well not have them.

**Steps to reproduce the problem**:

1. Have bees
2. Have windoors surround the bees
3. Watch as they dont care and attack you anyway.

**When did the problem start happening**:

Fairly recently. Maybe a week or two ago.

**Extra information**:

![image](https://github.com/ParadiseSS13/Paradise/assets/94168850/6fe24efc-130b-49f1-9d79-bfa3c3a81cbb)

![image](https://github.com/ParadiseSS13/Paradise/assets/94168850/6891cbe4-8483-402c-a054-9ec76ec1f736)

**Comment by Henri215** [comment] 2023-10-01 13:17
Tested and can confirm this is a duplicate of https://github.com/ParadiseSS13/Paradise/issues/22396.
Thank you for making the issue report.

**Closed by Henri215** 2023-10-01 13:17 UTC
Labels: Bug, Duplicate, Literally Everybody Ded
