### ISSUE TITLE
Hair Gradients show up incorrectly in photos taken by a Camera.

### ISSUE THREAD

**Issue by 7erracotta** [ParadiseSS13/Paradise#17457] opened 2022-02-27 14:41 UTC
**Issue Description**:

When your character has a hair gradient and takes a photo of theirself, there is a strange faded square surrounding them.

**What did you expect to happen**: 
I expected the hair gradient to show up correctly on the photo.

Its really strange to look at.

**What happened instead**:
The hair gradient shows up incorrectly on the picture taken

**Why is this bad/What are the consequences**:

It looks really strange and you have to take off your characters hair gradient in order to get a good photo of them.

**Steps to reproduce the problem**:

Play as a character with a hair gradient, then pick up a camera and take a photo of yourself.

**When did the problem start happening**:

I noticed this problem a week ago.

**Extra information**:

**Comment by CinnamonSnowball** [comment] 2022-02-27 15:42
Duplicate of #17116

**Closed** 2022-06-24 14:32 UTC
Labels: Duplicate
