### ISSUE TITLE
Becoming Fat in a Mech Deletes Items

### ISSUE THREAD

**Issue by granodd** [ParadiseSS13/Paradise#8325] opened 2017-10-28 20:47 UTC
**Problem Description**:
Becoming fat while you're inside of an mech will cause your jumpsuit and exosuit to pop off, but not onto the ground, and instead be deleted. This by extension also deletes your ID, belt slot, pocket slots, PDA slot, and to be assumed exosuit suit storage slot.

**What did you expect to happen**: 
The items to all land on the floor beneath the mech for recovery until the fatness was fixed or went away.

**What happened instead**:
The items were outright deleted.

**Why is this bad/What are the consequences:**
This can lead to very valuable items like IDs, hardsuits, PDAs, and other important items like weapons to be deleted if for some reason you become fat in a mech.

**Steps to reproduce the problem**:
1. Be a race that can get fat (I was human at the time)
2. Eat enough food that you will eventually become fat.
3. Be sure to have items equipped in your suit, exosuit, pockets, belt, ID, PDA, and exosuit storage slot
4. Become fat inside of the mech and observe as your items magically disappear into the void

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It was an extended round as far as I was aware, though I doubt this had much to do with the situation. The mech I was using as well was a Ripley, though you may be able to recreate the problem with other mechs.

**Comment by alexkar598** [comment] 2017-10-28 22:18
Actually, the items get dropped at your location but your location is the mech and yours items will be trapped in the content of the mech until it get destroyed

**Comment by FalseIncarnate** [comment] 2017-10-29 04:40
Same base issue as in #7673 and #3193 just with a different way of producing it.

**Comment by Crazylemon64** [comment] 2018-08-28 03:08
Duplicate of #3193

**Closed by Crazylemon64** 2018-08-28 03:08 UTC
Labels: Duplicate
