### ISSUE TITLE
Ketchup packets may not be functioning correctly

### ISSUE THREAD

**Issue by Alex6511** [ParadiseSS13/Paradise#1884] opened 2015-08-28 19:44 UTC
People are reporting they are unable to apply ketchup to food/beakers directly from the packs.

**Comment by Fox-McCloud** [comment] 2015-08-28 20:26
I believe these can only be applied to food.

**Comment by Alex6511** [comment] 2015-08-28 20:36
We suggested that - they said it didn't work, I personally don't play chef so I have no idea.

**Comment by Spacemanspark** [comment] 2015-08-28 21:33
Don't you have to open the packs before trying to apply stuff?
Also, you can use splash those on people and make fake blood, I remember doing that at least once.

**Comment by FalseIncarnate** [comment] 2015-08-29 19:41
I'll check this out tonight. You never could directly go from pack to beaker, have to grind it first.

Transferring from pack to food was the intended function, so I'll look into that

**Comment by FalseIncarnate** [comment] 2015-08-30 05:24
Tested locally on most recent code, worked as intended.

Tested with both ketchup packets and a custom-made packet (from the condi-master). Cannot reproduce, so I'd guess they were doing something wrong (such as trying to put ketchup on something across the room).

**Comment by FalseIncarnate** [comment] 2015-08-30 05:42
Ignore that mistaken reference. Still cannot reproduce, and just typed the wrong issue number in the PR description.

**Closed** 2015-08-30 05:45 UTC
Labels: Bug
