### ISSUE TITLE
Medbay air alarm placement causes inoperative functionality while firelocks closed

### ISSUE THREAD

**Issue by Anticept** [ParadiseSS13/Paradise#8823] opened 2018-03-28 23:47 UTC
See these photos:

![image](https://user-images.githubusercontent.com/521038/38061574-bfa2c120-32bd-11e8-9de4-b2324c47e1a0.png)

![image](https://user-images.githubusercontent.com/521038/38061581-c7f608c8-32bd-11e8-86b6-560d5e993bf7.png)

As closed firelocks block atmos, it is impossible for these air alarms to resolve their own issues.

If this is resolved, an additional air alarm will need to be placed. as there are three zones and two air alarms.

Note that air alarms should never be within one tile of a vent or scrubber, ideally 3 tiles away, considering how atmos works.

**Comment by Crazylemon64** [comment] 2018-08-28 02:34
Duplicate of #9059

**Closed** 2018-10-04 13:31 UTC
Labels: Boxstation, Map Issue
