### ISSUE TITLE
Connector ports behave like tubes. Pumps cannot be turned on 

### ISSUE THREAD

**Issue by Talik6969** [ParadiseSS13/Paradise#22981] opened 2023-10-21 15:38 UTC
**Issue Description**:

I'm using a scheme pomp - connector to fill the canisters. Gases remain in connectors after filling the canisters. Cannot use connectors again for new gases after using them. Cannot turn on a pump to suck gasses from the connectors

**What did you expect to happen**: 

1. Connector ports to the canister must not contain any gasses.
2. Pumps connected to the ports could be turned on and suck gases from them

**What happened instead**:

1. Connector ports keep gasses and temperatures after using them. 
2. Pumps cannot be turned on when connected to the ports (connectors)

**Why is this bad/What are the consequences**:

1. This makes hard to use them again for another gasses because they will mix. 
2. The temperatures will mix too
3. A part of gas disappear after using a connector again and placing an empty canister.
4. Pumps cannot be used to suck gases from tube as they should

**Steps to reproduce the problem**:

1. Place a connector and a pump on a tube line. Fill the canister using them and place an empty canister. The empty canister is been filled after placing. 
2. Place a pump to a port. It cannot be turned on

**When did the problem start happening**:

I don't know

**Extra information**:

Sorry for my english

**Comment by DGamerL** [comment] 2023-10-21 15:38
Could you add some images?

**Comment by Talik6969** [comment] 2023-10-21 17:45
![Untitled-10](https://github.com/ParadiseSS13/Paradise/assets/148638783/b8cb190c-4e18-41fe-a40b-46296b7ed204)
![Untitled-11](https://github.com/ParadiseSS13/Paradise/assets/148638783/72d46312-a02b-4616-ab90-2a196350f82b)

**Comment by Bjamcham** [comment] 2023-10-31 18:51
To clarify, the connector gas storage is a long standing issue caused by the unary/binary devices storing their own air contents. The portable pump not turning on however is an intended feature that was added in https://github.com/ParadiseSS13/Paradise/pull/22357.

**Comment by Spaghetti-bit** [comment] 2024-07-01 08:27
Fixed by https://github.com/ParadiseSS13/Paradise/pull/25328

**Closed by Spaghetti-bit** 2024-07-01 08:27 UTC
Labels: Bug
