### ISSUE TITLE
AI's can use announcements and PDA without power

### ISSUE THREAD

**Issue by Regen1** [ParadiseSS13/Paradise#3507] opened 2016-02-04 11:15 UTC
Not sure if its intended like this, but it really shouldn't be, considering their coms and speech does go down

**Comment by TheDZD** [comment] 2016-02-04 22:42
A lack of power really just seems to make the AI die horribly, doesn't disable anything.

**Comment by Crazylemon64** [comment] 2016-02-04 23:18
It makes them blind, but for some reason it also gives some bizarre text about hacking an APC override or whatever? It doesn't do anything, however... Is that a bug, or is it the memento of something bugged?

**Comment by TheDZD** [comment] 2016-02-04 23:20
Huh, that's quite odd at the very least then.

**Comment by Regen1** [comment] 2016-02-05 16:04
Power literally disables every other mechanical object in the room.
It gives the messages that the powersource is lost, trying to hack and override the APC, in case it was another AI that just turned off the breaker switch or equipment on the APC.

It is very clearly intended to make the AI go night night, but it doesn't.

**Comment by Ar3nn** [comment] 2016-02-12 00:31
The stuff about hacking an APC is that its searching for anywhere it can jack power from by any means necessary to restore functionality. I know in one case I was AI, and my room was bombed from the north side, and my APC was destroyed, so I jacked into the maintenance or the storage room APC and powered off it somehow because there was uninterrupted non-space tiles connecting me to it. Not necessarily power lines, which I think is even more odd.

**Comment by Tastyfish** [comment] 2016-02-12 08:28
Just noticed, this is actually a duplicate of #1878 I'm pretty sure.

**Comment by Ar3nn** [comment] 2016-02-16 09:07
The thing about the PDA, I believe its just a small transceiver in the core, so...I guess, if there's some sort of battery shunting on to keep the AI from dying immediately, it could pulse the transceiver to send a PDA message.

**Closed** 2016-03-26 19:41 UTC
Labels: Inconsistency, Not a Bug
