### ISSUE TITLE
Dragging a deck of cards into an empty slot in a container makes it disappear

### ISSUE THREAD

**Issue by Christer2222** [ParadiseSS13/Paradise#20305] opened 2023-01-28 07:50 UTC
**Issue Description**:

If you drag a deck of cards into an empty slot, it disappears. Might be related to #18560

**What did you expect to happen**: 

For my inventory to get rearranged.

**What happened instead**:

Poof. Gone. I am guessing it is still in there, but not accessible.

**Why is this bad/What are the consequences**:

You shouldn't be able to delete items like this.

**Steps to reproduce the problem**:

1. Get a backpack.
2. Get a deck of cards.
3. Get some other item, like a box or some shoes.
4. Place the deck of cards into the backpack.
5. Place the other item into your backpack.
7. Try to drag the deck into an empty slot.

**When did the problem start happening**:

Noticed today? 28.01.2023.

**Extra information**:

I am supposed to have 1 extra suspicious deck, and 1 normal playing cards deck in this picture. The arrow shows where you would drag the deck for it to disappear.
![image](https://user-images.githubusercontent.com/25958019/215253783-88086870-efb3-461c-9256-613452d37efa.png)

**Comment by warriorstar-orion** [comment] 2023-01-29 15:55
I would go as far as to say this is a duplicate of #18560, but it's good to have another reproduction of it.

**Closed by warriorstar-orion** 2023-01-29 15:55 UTC
