### ISSUE TITLE
Rigsuit Boots sprite swapping

### ISSUE THREAD

**Issue by HereticChurch** [ParadiseSS13/Paradise#3390] opened 2016-01-25 07:39 UTC
If you activate the magboots of most rigsuits, the sprite changes to the normal magboots sprite, and doesn't change back.

**Comment by Fox-McCloud** [comment] 2016-01-27 21:57
Are these RIG RIG suits are hardsuits?

**Comment by HereticChurch** [comment] 2016-01-27 21:59
I guess I should have clarified... It's the bay rigsuits. They sometimes have a magboot option for the boots that slide out, and when you activate them, their sprite goes from something that matches the armor to the standard yellow magboots, They don't change back either.

**Comment by KasparoVy** [comment] 2017-02-21 05:14
I can't reproduce this with the Breacher rigsuit. Spamtoggling the magboots on and off with the suit deployed and sealed.

**Comment by KasparoVy** [comment] 2017-02-21 05:22
I figured I'd test this too since I was messing about with Bay rigsuits and I can't reproduce this bug at all with any of the rigsuits. Pretty sure someone fixed it at some point @Fox-McCloud

They wouldn't allow me to enable magpulse unless the suit was deployed and fully sealed, and when I spamtoggled the magpulse it didn't mess up the sprites

**Comment by AffectedArc07** [comment] 2021-03-04 15:56
Closed by purging rigsuits.

**Closed by AffectedArc07** 2021-03-04 15:56 UTC
Labels: Sprites
