### ISSUE TITLE
bioluminescence lantern broken

### ISSUE THREAD

**Issue by Nukkel** [ParadiseSS13/Paradise#9852] opened 2018-10-14 15:39 UTC
**Problem Description**:
bio-luminescence lantern doesnt  work

**What did you expect to happen**: 
I thought I would light up if I  pressed the ability

**What happened instead**:
I undressed myself completely and I didnt light up, instead everything stayed dark.

**Why is this bad/What are the consequences:**
No cool ability  for ant-man

**Steps to reproduce the problem**:
Clicked the bio-luminescence  lantern ability.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nope.

**Comment by Spartan6** [comment] 2018-10-14 16:10
Were you naked?

**Comment by Nukkel** [comment] 2018-10-14 16:14
Naked, and tried it with crew uniform on aswell.

**Comment by SamHPurp** [comment] 2018-10-20 13:54
I cannot re-produce.

**Comment by Superhats** [comment] 2018-10-24 09:21
What color were your body markings?

**Comment by Superhats** [comment] 2018-10-24 09:22
That's important, because your bioluminescence is determined by the color of your body markings, and black markings means you won't glow at all.

**Comment by variableundefined** [comment] 2018-10-25 13:49
Cannot be reproduced. Closing.

**Closed by variableundefined** 2018-10-25 13:49 UTC
Labels: Bug
