### ISSUE TITLE
Air alarm bluescreen on Shepardstation

### ISSUE THREAD

**Issue by Dovixx** [ParadiseSS13/Paradise#18600] opened 2022-07-27 13:28 UTC
**Issue Description**:

Air alarm by the hop line bluescreened on the shepard station. Not sure if its a map thing or just air alarm.

**What did you expect to happen**: 

Air alarm to work properly

**What happened instead**:

Bluescreen

**Why is this bad/What are the consequences**:

it no work :(

**Steps to reproduce the problem**:

Unsure what caused it to bluescreen

**When did the problem start happening**:

Today 2022-07-27

**Extra information**:

![image](https://user-images.githubusercontent.com/37041561/181258688-60c439db-c916-4dea-b75e-4c13a7052039.png)

**Comment by Inadvizable** [comment] 2022-07-27 13:28
Was it facing something solid like a wall?

**Comment by kugamo** [comment] 2022-07-27 13:31
![image](https://user-images.githubusercontent.com/16618648/181259373-4c2af580-bf8a-4d67-9da7-f8ef09041d2d.png)

I believe this was the air alarm in question.

**Comment by Sirryan2002** [comment] 2022-07-27 16:06
duplicate of #18517

**Closed by Sirryan2002** 2022-07-27 16:06 UTC
