### ISSUE TITLE
Potential NoClip bug with mining shuttle zone

### ISSUE THREAD

**Issue by dojoman500** [ParadiseSS13/Paradise#21125] opened 2023-05-19 00:21 UTC
**Problem Description**:
Being between mining shuttle airlocks caused ejection from station

**What did you expect to happen**: 
Expected the outer door to prevent me from being launched to space

**What happened instead**:
somehow noclipped through outer door, was killed within 2 minutes of new round by shuttle spawning on me

**Why is this bad/What are the consequences:**
Lead to instant death

**Steps to reproduce the problem**:
Exact occurrence unknown, though I was entering the tile before the door when it closed, somehow clipped through

**When did the problem start happening**:
If your report is about something that used to work but no longer does, when was the last time you remember it working?

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was anything else out of the ordinary happening?)**:
Anything else you can tell us.

**Comment by dojoman500** [comment] 2023-05-19 00:29
Map was farragus

**Comment by dojoman500** [comment] 2023-05-19 00:47
Possible fix: if an entity somehow clips through to a place they shouldn't, teleport them back within the playing area. could be implemented by making walls kick people to their previous tile, if there is no possible way for them to get to the new one and they somehow do

**Comment by GDNgit** [comment] 2023-05-19 00:52
Did you enter the mining airlock while the shuttle was being sent? If so you probably just walked into space, this isn't a bug, airlocks won't close while mobs are in them unless safeties are off. 

Space also isn't an out of bounds area, it's part of the game world, you can go there and there's stuff to do in space.

**Comment by Contrabang** [comment] 2023-05-19 01:11
If you're already on the tile when the door closes (that includes while moving to it), the door wont crush you and instead reopen. Im pretty sure atmos just got the better of you there and sucked you out into space. Not really a noclip but... you got unlucky.

**Comment by dojoman500** [comment] 2023-05-19 02:22
> Did you enter the mining airlock while the shuttle was being sent? If so you probably just walked into space, this isn't a bug, airlocks won't close while mobs are in them unless safeties are off.
> 
> Space also isn't an out of bounds area, it's part of the game world, you can go there and there's stuff to do in space.

I was between the two doors when it sent, the external one should have blocked me, rather than death I shoulda just been trapped

**Comment by Contrabang** [comment] 2023-05-21 22:03
Im not able to reproduce this, and I don't see any way for you to actually clip through the door. Even if you somehow clipped through it, I believe it would be more of an engine problem, which we don't have access to.

**Closed by Contrabang** 2023-05-21 22:03 UTC
Labels: Cannot Reproduce
