### ISSUE TITLE
Catching a Thrown Object Still Hurts You

### ISSUE THREAD

**Issue by granodd** [ParadiseSS13/Paradise#6978] opened 2017-03-28 19:59 UTC
A revival of #3300 

Activating your throw when an object is thrown at you will allow you to catch that item. However as it is currently iterated, catching the object will still treat it as though you were hit by that object when you caught it. This makes very little sense.

For example: I ask for my engibro to throw me a multitool, I catch it in my hand, but somehow it still hits my chest (???). This is true for every other object as well, and sort of defeats the purpose of catching objects/makes it to where if someone wants to quickly have something passed to them they'll still be hit by it, which isn't very good if I'm tossing something like an RPED to someone when they ask for it from science.

**Comment by tigercat2000** [comment] 2017-03-28 20:00
Stated duplicate of issue #3300  😛 
We know this is an issue, and the other report is still open, there's no reason to make a new one

**Comment by Anoonki** [comment] 2017-03-28 20:04
*Stated bump of issue #3300 
ftfy
:^)

**Comment by taukausanake** [comment] 2017-03-28 20:05
If you're going to bump, bump the original Issue. Don't make a new one

**Comment by granodd** [comment] 2017-03-28 20:19
@taukausanake I only made a new one due to bringing this up and being told that it was so old that it may be worth making a dupe. But I don't use github all that often so you'll have to forgive me or something. Either way, **one year old issue**

**Comment by KasparoVy** [comment] 2017-03-28 21:20
There's a PR up that fixes it :thinking:

**Comment by Fox-McCloud** [comment] 2017-03-28 22:01
DOn't make duplicate issue reports if you know they already exist.

**Closed by Fox-McCloud** 2017-03-28 22:01 UTC
