### ISSUE TITLE
Magboots

### ISSUE THREAD

**Issue by orelbon** [ParadiseSS13/Paradise#977] opened 2015-05-09 00:16 UTC
Magboots wont stop you from moving when the atmosphere is shifting

**Comment by Fox-McCloud** [comment] 2015-05-09 01:44
Not a bug. This is how it's meant to function on LINDA.

This may be changed, but it's not a bug.

**Comment by Spacemanspark** [comment] 2015-05-09 06:47
Ya... This should be changed.

**Comment by fj45** [comment] 2015-05-09 09:43
Really needs to be changed. That makes mags useless.

**Comment by Robertha89** [comment] 2015-05-10 13:13
it's technically a Linda oversight

**Comment by ZomgPonies** [comment] 2015-05-11 14:23
Fixed via #988

**Closed by ZomgPonies** 2015-05-11 14:23 UTC
Labels: not a bug
