### ISSUE TITLE
Beepsky can see you in ethereal jaunt

### ISSUE THREAD

**Issue by MischievousGremlin** [ParadiseSS13/Paradise#8030] opened 2017-08-31 08:32 UTC
**Problem Description**:
If beepsky/a securitron has started chasing you and then you ethereal jaunt, he will follow the jaunting player's location until they manifest again

**What did you expect to happen**: 
Beepsky not be able to follow something that doesn't exist

**What happened instead**:
Chased around by a beepsky who followed me until I was outside a window in space and reformed

**Why is this bad/What are the consequences:**
People following beepsky to track a mistformed/jaunted player

**Steps to reproduce the problem**:
Get beepsky mad at you, use ethereal jaunt, watch as he chases you around

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I was simply a mime who had ethereal jaunt and got chased by a beepsky on a traitor round despite ethereal jaunting

**Comment by Spacemanspark** [comment] 2017-08-31 16:22
Beepsky is an ethereal being, the matters of time and space are not an issue to him.

**Comment by Crazylemon64** [comment] 2017-08-31 17:51
Dupe of #3110

**Closed by Crazylemon64** 2017-08-31 17:51 UTC
