### ISSUE TITLE
Got changeling but got sent to lobby like it couldnt find any roles for me

### ISSUE THREAD

**Issue by xuvari** [ParadiseSS13/Paradise#12643] opened 2019-10-24 11:03 UTC
**Issue Description**:
i got changeling, the sound byte and some goals and everything, yet got sent to lobby.
When i joined manually, no changeling

**What did you expect to happen**: 
getting assigned a role as changeling.

**What happened instead**:
i got changeling, the sound byte and some goals and everything, yet got sent to lobby.
When i joined manually, no changeling

**Why is this bad/What are the consequences**:

**Steps to reproduce the problem**:
set several roles to low, maybe?

**When did the problem start happening**:
happened once

**Extra information**:

**Comment by xuvari** [comment] 2019-10-24 11:05
apparantly i also looked like a changeling from the admins side.

**Comment by craftxbox** [comment] 2019-10-24 11:25
I have never been able to intentionally reproduce this, but have accidentally, and i theorize this is a mixture of antags rolling before roles, return to lobby when prefs unavailable and roles happening to all be unavailable.
If you choose a role that can't be that antag, you'll have the flags still but be de-antagged (ie ai, sec, Capt) however if you choose an antag capable role, then you will get antag and it will work normally, but you'll have been able to pick your job based on your objectives. Highly RNG based issue.

**Comment by farie82** [comment] 2019-10-24 21:05
dupe of #11739

**Closed** 2020-03-14 19:41 UTC
