### ISSUE TITLE
Cerebron Scichem request console spawns off wall

### ISSUE THREAD

**Issue by Zorazi-Teo-Daedalus** [ParadiseSS13/Paradise#22569] opened 2023-09-23 23:04 UTC
**Issue Description**:

The science requests console in Cerebron scichem isn't on the wall, it's on the floor, on a rack in a pile of objects.

**What did you expect to happen**: 

For it to be on the wall, like it should.

**What happened instead**:

Janky mapping.

**Why is this bad/What are the consequences**:

We hate jank in this house.

**Steps to reproduce the problem**:

Be miserable enough to be on Cerebron, find yet another mapping issue with it.

**When did the problem start happening**:

Not sure exactly when.

**Extra information**:

![image](https://github.com/ParadiseSS13/Paradise/assets/71111573/2f319b85-fef2-4421-8f17-fff0291af97d)

**Comment by DGamerL** [comment] 2023-09-23 23:08
Duplicate of #21985 
Thank you for the report!

**Closed by DGamerL** 2023-09-23 23:08 UTC
Labels: Oversight, Duplicate
